### PR TITLE
obs-ffmpeg: Fix SRT listener bug

### LINKED ISSUE #10504: Streaming to local server with SRT in listener mode using "Start streaming" without a connection occurring prevents OBS from closing
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

Other

### OBS Studio Version (Other)

30.1.2

### OBS Studio Log URL

https://obsproject.com/logs/AWe6fUonS1skxhOO

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When attempting to stream locally in listener mode using SRT with the "Start Streaming" button, if no client connects to OBS to view the stream. OBS should close properly when exiting.

### Current Behavior

When attempting to stream locally in listener mode using SRT with the "Start Streaming" button, if no client connects to OBS to view the stream. OBS seems to close when clicking the exit button, but the process is still running (icon can be seen in the system tray) and not responsive. Closing OBS requires ending the process through task manager

### Steps to Reproduce

1. In settings, set the service to custom and the server to srt://[local ip address]:[port]?mode=listener
2. Click "Start Streaming" to begin stream
3. Click "Exit" to exit OBS
4. OBS seems to exit, but process is still running and icon will still be present in system tray

### Anything else we should know?

Please provide an option to cancel the connection when attempting to stream in listener mode using SRT with the streaming function

### PR DESCRIPTION
**Pull request by pkviet**
### Description
Fixes #10504.
When starting an SRT stream in listener mode, if no connection is made by a client, the socket was not closed when exiting obs. This fixes the issue so that SRT is closed properly.

### Motivation and Context
Bugs are bad.

### How Has This Been Tested?
Bug is fixed.
SRT in caller mode still works.

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — CHANGES_REQUESTED** [review]
Commit message nit:
* obs -> OBS

File: plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c [hunk 1]
```diff
@@ -608,10 +603,13 @@ static void close_mpegts_url(struct ffmpeg_output *stream, bool is_rist)
...
 
 	/* close custom avio_context for srt or rist */
-	avio_flush(stream->s);
-	stream->s->opaque = NULL;
-	av_freep(&stream->s->buffer);
-	avio_context_free(&stream->s);
+	AVIOContext *s = stream->s;
+	if (!s)
+		return;
+	avio_flush(s);
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c:609]: Put a newline between the previous `if` contents and this, or enclose the previous `if` contents in curly braces.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Formatting nit.

File: plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c (hunk 1 above)
Comment (pkviet) [reply plugins/obs-ffmpeg/obs-ffmpeg-mpegts.c:610]: done

**Comment by tt2468** [comment]
Unfortunately, this does not appear fully fixed. Here's what I'm seeing on Ubuntu 22.04:

- Start stream with `srt://0.0.0.0:6969?mode=listener`
- Don't connect a client
  - Stream will never fully "start"
  - OBS begins spamming the log with `error: [obs-ffmpeg mpegts muxer / libsrt]: Connection rejected, Unknown or erroneous` messages
- Close OBS
- OBS will unload fully, however the program will segfault on finalization:
```
info: Number of memory leaks: 0
Segmentation fault (core dumped)
```

It completely fails to shut down the socket if I connect a client, then disconnect the client, then try stopping stream or shutting down OBS. To be completely honest, I think we need to just remove rendezvous and listener modes from our SRT output.

**Comment by pkviet** [comment]
@tt2468 i tested on win 11 and didn't get that segmentation fault. Unfortunately i don't have a ubuntu 22.04 distro to test with. I'll investigate more on my side with win 11 to see if there are errors i overlooked.

**Comment by pkviet** [comment]
@tt2468 the FFmpeg fix for the listener bug was exactly our issue.
I checked that listener now works properly:
- OBS is not stuck into "Connecting ..." in listener mode but displays "Streaming" because the libsrt_open now returns, even if no client is calling obs.
- the socket therefore closes correctly.
Reference for the fix:
https://git.videolan.org/?p=ffmpeg.git;a=commit;h=87677c2195e86b126c3438439a05d0a46ae5bb50
https://trac.ffmpeg.org/ticket/9142

**Review by tt2468 — APPROVED** [review]
