### PR TITLE
mac-capture: Don't crash when migrating unknown display IDs

### LINKED ISSUE #9606: 30.0.0 beta 3 SEGV on start with MacOS 12.6.6 & old profile from 29.x
### Operating System Info

macOS 12

### Other OS

_No response_

### OBS Studio Version

Other

### OBS Studio Version (Other)

3.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/AnbXRkDC55v0Ztib

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

OBS should run - or at least not segfault.

### Current Behavior

Segfault on program start. 

### Steps to Reproduce

1. Run obs studio 30.0.0 beta 3 (with my profile from 29.1.2 still around)
2. Wait for it to crash.
3.
...

### Anything else we should know?

It's a beta, I get that.  Just thought y'all should know 30.0.0 beta 3 is SEGV on start for MacOS.  If I delete ${HOME}/Library/Application Support/obs-studio/, then it starts okay, but all my previously configured scenes are obviously gone.  Possibly OBS should nuke the old profile, or offer to do so?

Feel free to close this issue if you don't feel it's worth addressing.

### PR DESCRIPTION
**Pull request by gxalpha**
### Description

The current code assumes that a display UUID can be created with the stored ID, but that's not always the case, e.g. when the user doesn't have the display connected. As such, we need to null check this, and fall back to the invalid ID (0) when the ID cannot be migrated.

The current code also only migrates on source creation, which yields weird behaviour where if the user opens properties and then cancels it would still show the first display, but only for the session. This is why the code was factored out of the creation function and now is always used when an ID needs to be acquired from OBS Data settings, including when the source is updated.

The deprecated display capture still doesn't like when the display doesn't exist (it returns false/NULL on creation leading to the source basically being "dead" and the user not able to do anything with it but delete it), but this is the same on 29.1 and I'm not too worried about that source anyways.

### Motivation and Context

Got reports of crashes in mac-capture when the UUID gets created.
This can be reproduced easily by (first removing "display_uuid" if it exists and then) setting the "display" setting in the scene collection json to a number higher than the number of connected displays.

Fixes #9606

### How Has This Been Tested?

macOS 14
Tested that with a variety of different settings (existing "display", nonexistent "display", existing "display_uuid", nonexistent "display_uuid", and combinations of the keys) that previous behavior is restored, where when the display isn't found, nothing is shown but the properties let you select one of the available displays.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by PatTheMav** [comment]
So the crash is not related to an invalid UUID, but an invalid C-string being passed into the CoreFoundation method generating a `CFUUIDRef`?

**Comment by gxalpha** [comment]
With the crash that I can reproduces (and where the crash stack pretty much matches the one in the report I've seen) `CGDisplayCreateUUIDFromDisplayID` returns `NULL` (because the `display_id` refers to a display that the system doesn't know), which is then passed into `CFUUIDCreateString` which crashes.

I'm not sure what you mean exactly with "invalid UUID" - are you referring to a string that's not formatted as a UUID or to a UUID that the system doesn't know? Although neither of these cases appear to crash on master on my system.

**Comment by PatTheMav** [comment]
Ok, so the crash is limited to cases of migrating from the old displayID-based setting to the UUID-based setting but with an invalid displayID, got it.

**Review by PatTheMav — APPROVED** [review]

**Comment by RytoEX** [comment]
Does this fix #9606?

**Comment by gxalpha** [comment]
Yes.

File: plugins/mac-capture/window-utils.h [hunk 1]
```diff
@@ -31,3 +31,8 @@ void window_defaults(obs_data_t *settings);
 void add_window_properties(obs_properties_t *props);
 
 void show_window_properties(obs_properties_t *props, bool show);
+
+/** Get the display ID of a display and simultaniously migrate pre-30.0 display IDs to 30.0 UUIDs.
```
Comment (RytoEX) [inline plugins/mac-capture/window-utils.h:35]:
```suggestion
/** Get the display ID of a display and simultaneously migrate pre-30.0 display IDs to 30.0 UUIDs.
```

**Review by RytoEX — CHANGES_REQUESTED** [review]

File: plugins/mac-capture/window-utils.h (hunk 1 above)
Comment (gxalpha) [reply plugins/mac-capture/window-utils.h:35]: Thanks.

**Review by RytoEX — APPROVED** [review]
