### PR TITLE
obs-qsv11: Fix target usage values

### LINKED ISSUE #2527: QSV Target Usage dropdown menu
## Expected Behavior
Is that something used for x264?
What is "fasterveryfast"? Maybe it should separate as "faster" and "veryfast"?

## Current Behavior
QSV

### PR DESCRIPTION
**Pull request by RytoEX**
### Description

PR #1937 (commit b9ad1ce) added QSV target usage options, but there was a comma missing between two of the array entries. This resulted in "faster" and "veryfast" becoming "fasterveryfast", which is not valid.

Code style changes were required by .clang-format.

### Motivation and Context

Fixes #2527.  The encoder doesn't complain, and the log doesn't indicate which usage target was selected, but this should be fixed.

### How Has This Been Tested?

Compiled on Windows 10 1903 (Build 18362.720) 64-bit using VS2017 (15.9.21) with latest OBS deps.  Confirmed that the target usage entries are listed correctly and that recordings work with either selected.
image

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

File: plugins/obs-qsv11/QSV_Encoder.h [hunk 1]
```diff
@@ -74,17 +74,10 @@ static const struct qsv_rate_control_info qsv_ratecontrols[] = {
...
-					      "balanced",
-					      "speed",
-					      "veryslow",
-					      "slower",
-					      "slow",
-					      "medium",
-					      "fast",
-					      "faster"
-					      "veryfast",
-					      0};
```
Comment (Mishasama) [inline plugins/obs-qsv11/QSV_Encoder.h]: Maybe you should keep lines for easy readings.

Comment (Mishasama) [inline plugins/obs-qsv11/QSV_Encoder.h]: Maybe you should keep lines for easy readings.

**Comment by RytoEX** [comment]
> Maybe you should keep lines for easy readings.
@Mishasama 
I considered it, but then it would somewhat defeat the purpose of the clang-format requirements, and it was causing CI to fail the build jobs on macOS and Linux.  In any case, the code is already merged for now.  If someone can come up with a way to write that code with better readability that conforms to the clang-format requirements, they're welcome to submit a PR.
