### PR TITLE
libobs-d3d11,win-capture: Add Force SDR for DXGI duplicator

### LINKED ISSUE #7970: Display Capture appears dim with HDR enabled
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

Other

### OBS Studio Version (Other)

Normally 28.1.2, but reproduced with 29.0.0-beta3

### OBS Studio Log URL

https://obsproject.com/logs/sGhGGeUd-1rt_dHo

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Recording should have looked like this (as screenshotted with Snipping Tool / ShareX):

ShareX screenshot of desktop

### Current Behavior

Actual recording appears dim (screenshotted by OBS):

OBS screenshot of desktop

### Steps to Reproduce

1. Enable HDR through Windows
2. Launch OBS and use a Display Capture source

### Anything else we should know?

- Other sources like Browser, Image, and Game Capture are correctly exposed, regardless of Auto HDR.
- Issue appears for Window Capture, except when "Force SDR" is enabled in the properties, then it has the expected brightness.
- Issue is persistent across different color format/spaces, e.g. `NV12 + Rec.709 [Limited Range]` and `P010 + Rec.2100 (PQ) [Full Range]`, although the 10-bit format is slightly brighter than 8-bit.
- Toggling Windows's "hardware-accelerated GPU scheduling" had no effect.

To make it clear, I'm intending to record SDR content while using HDR.

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Same function as the checkbox in window capture for forcing SDR capture when HDR is enabled on a display in Windows settings.

Also plumb support for wide SDR although DXGI chooses narrow anyway?

Stacks on top of #7974.

FIxes #7970.

### Motivation and Context
Users don't want to disable HDR in their Windows settings to capture SDR, and that's reasonable.

### How Has This Been Tested?
Checked display capture of SDR and HDR monitor with and without checkbox enabled.

Checked log output for display capture DXGI/WGC, force on/off, and window capture BitBlt/WGC, force on/off.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jpark37** [comment]
PR is ready, but holding in draft until the other PR is merged.

**Comment by Adega-Studio** [comment]
[jpark37](https://github.com/jpark37) Hello. I don't know how to write to you personally. I'll ask here. Here is a solution to remove stuttering frames will be under the new versions of the obs? https://github.com/obsproject/obs-studio/actions/runs/1244236413

**Comment by RytoEX** [comment]
This can be undrafted now that #7974 has been merged.

File: libobs-d3d11/d3d11-subsystem.cpp [hunk 1]
```diff
@@ -1237,6 +1190,54 @@ static ULONG GetSdrWhiteNits(HMONITOR monitor)
...
+							gs_monitor_color_info(
+								hdr,
+								desc1.BitsPerColor,
+								GetSdrWhiteNits(
+									desc1.Monitor)))
+						.second;
+				}
+			}
+		}
+	}
```
Comment (jp9000) [inline libobs-d3d11/d3d11-subsystem.cpp:1236]: Just a minor nitpick, is there any way to unsquish this code at all?

Comment (jpark37) [reply libobs-d3d11/d3d11-subsystem.cpp:1236]: Either `continue` statements or helper functions. Which do you prefer?

Comment (jpark37) [reply libobs-d3d11/d3d11-subsystem.cpp]: I push a little tidier version without doing either.
