### PR TITLE
obs-ffmpeg: Use Libva to enable FFmpeg VA-API

### LINKED ISSUE #3184: [VAAPI] CBR/VBR displayed on hardware that doesnt support it
## Platform
Operating system and version: Ubuntu 20
OBS Studio version: 25.0.8

## Expected Behavior
We should not display rate controls that will fail.

## Current Behavior
Newer intel hardware particularly those laptop chips that only support low power only support CQP. E.g.
```
13:42:37.338: CPU Name: Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz
13:42:37.338: CPU Speed: 3786.312MHz
13:42:37.338: Physical Cores: 2, Logical Cores: 4
13:42:37.338: Physical Memory: 7684MB Total, 5737MB Free
13:42:37.338: Kernel Version: Linux 5.4.0-40-generic
13:42:37.338: Distribution: "Ubuntu" "20.04"
13:42:37.442: Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics 620 (WHL GT2)
13:42:37.443: OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 20.0.8, shading language 4.60
```
```
libva info: VA-API version 1.7.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.7 (libva 2.6.0)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 20.1.1 ()
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            : VAEntrypointVLD
      VAProfileMPEG2Main              : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointVLD
      VAProfileH264Main               : VAEntrypointEncSliceLP
      VAProfileH264High               : VAEntrypointVLD
      VAProfileH264High               : VAEntrypointEncSliceLP
      VAProfileJPEGBaseline           : VAEntrypointVLD
      VAProfileJPEGBaseline           : VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline: VAEntrypointVLD
      VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          : VAEntrypointVLD
      VAProfileHEVCMain               : VAEntrypointVLD
      VAProfileHEVCMain10             : VAEntrypointVLD
      VAProfileVP9Profile0            : VAEntrypointVLD
      VAProfileVP9Profile2            : VAEntrypointVLD
```

## Steps to Reproduce
Attempt to stream with VAAPI using CBR. Encoder fails to initialize.

## Additional information
Made more painful by the fact that rate control will get overwritten by enforcing service settings which often set CBR.

### PR DESCRIPTION
**Pull request by tytan652**
**Testers: would please add to your feedback the output of the `vainfo --all` command and if issues a log of OBS with `--verbose` for debug log.**
### Description

Fixes #3184

With this change `obs-ffmpeg` is directly linked to Libva.

Only DRI device with H264 encode endpoint will be shown.
If none of them have it, the encoder is not registered.

Also only compatible rate control are shown.

My Nvidia driver only have decoding implemented through VA-API driver. 

Before on 27.2.4:
VAAPI-1
The `VAAPI Codec` was removed on master with #6590.

After on master with this PR:
VAAPI-2

If the environment variable `LIBVA_DRIVER_NAME` is set, a warning will be logged. This variable is usually set by advanced user.

if set it could load the wrong driver on the DRI device.

If set to `nvidia` on my machine:
```
warning: LIBVA_DRIVER_NAME variable is set, this could prevent FFMPEG VAAPI from working correctly
info: VAAPI: API version 1.15
debug: VAAPI: 'VA-API NVDEC driver' in use for device '/dev/dri/renderD128'
debug: VAAPI: 'VA-API NVDEC driver' in use for device '/dev/dri/renderD129'
info: FFMPEG VAAPI H264 encoding not supported
```
If not set (the libva error is normal):
```
info: VAAPI: API version 1.15
debug: VAAPI: 'VA-API NVDEC driver' in use for device '/dev/dri/renderD128'
libva error: /usr/lib/dri/iHD_drv_video.so init failed
debug: VAAPI: 'Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1' in use for device '/dev/dri/renderD129'
info: FFMPEG VAAPI H264 encoding supported
```

If set with `iHD`:
```
warning: LIBVA_DRIVER_NAME variable is set, this could prevent FFMPEG VAAPI from working correctly
DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
libva error: /usr/lib/dri/iHD_drv_video.so init failed
error: VAAPI: Fail to initialise
libva error: /usr/lib/dri/iHD_drv_video.so init failed
error: VAAPI: Fail to initialise
info: FFMPEG VAAPI H264 encoding not supported
```

### Motivation and Context

Non-compatible DRI device should not be shown.

### How Has This Been Tested?

Without the change, the encoder show my Nvdia card.

With it, it does not.

And with `LIBVA_DRIVER_NAME` set to a wrong driver to simulate no H264 endpoint, the encoder is not registered.

### Types of changes

- New feature (non-breaking change which adds functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by WizardCM** [comment]
This doesn't seem to work as intended on my Intel NUC. 

```
Intel Core i7-10710U CPU @ 1.10GHz
Loading up OpenGL on adapter Intel Mesa Intel(R) UHD Graphics (CML GT2)
OpenGL loaded successfully, version 4.6 (Core Profile) Mesa 22.0.1, shading language 4.60

```


Here's how it works on latest master (driver only supports CQP, but it works).
[2022-07-02 12-19-51.txt](https://github.com/obsproject/obs-studio/files/9032259/2022-07-02.12-19-51.txt)


And this is with this PR. Notice that it logs `FFMPEG VAAPI H264 encoding not supported`. UI doesn't list VAAPI at all.
[2022-07-02 12-18-01.txt](https://github.com/obsproject/obs-studio/files/9032260/2022-07-02.12-18-01.txt)

**Comment by tytan652** [comment]
I need to cover more profile while testing, I thought that checking for H264 Constrained Baseline was enough.

Can I have the output of the `vainfo --all` command to see each profile and endpoint with their compatible control rate.

**Comment by WizardCM** [comment]
> I need to cover more profile while testing, I thought that checking for H264 Constrained Baseline was enough.
> 
> Can I have the output of the `vainfo --all` command to see each profile and endpoint with their compatible control rate of your iGPU.

[vainfo.txt](https://github.com/obsproject/obs-studio/files/9032431/vainfo.txt)

**Comment by tytan652** [comment]
- Low power entrypoints are now allowed.
- Only compatible rate control are shown.
- Defaults is adapted against the first supported device.

**Comment by thecookie94** [comment]
[log_cookie.txt](https://github.com/obsproject/obs-studio/files/9033085/log_cookie.txt)
[vainfo_cookie.txt](https://github.com/obsproject/obs-studio/files/9033086/vainfo_cookie.txt)

Here ya go, log&vainfo.

**Comment by denisschultz** [comment]
On my side, the patch work. I can see my vaapi device normal.

As a addition, my vainfo:

```
vainfo: VA-API version: 1.14 (libva 2.14.0)
vainfo: Driver version: Mesa Gallium driver 22.1.2 for AMD Radeon RX 5500 XT (navi14, LLVM 13.0.1, DRM 3.44, 5.17.15-1-MANJARO)
vainfo: Supported config attributes per profile/entrypoint pair
VAProfileMPEG2Simple/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileMPEG2Main/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileVC1Simple/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileVC1Main/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileVC1Advanced/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileH264ConstrainedBaseline/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileH264ConstrainedBaseline/VAEntrypointEncSlice
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
    VAConfigAttribRateControl              : VA_RC_CBR
                                             VA_RC_VBR
                                             VA_RC_CQP
    VAConfigAttribEncPackedHeaders         : VA_ENC_PACKED_HEADER_NONE
    VAConfigAttribEncMaxRefFrames          : l0=1
                                             l1=0
    VAConfigAttribEncRateControlExt        : max_num_temporal_layers_minus1=3 temporal_layer_bitrate_control_flag=1

VAProfileH264Main/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileH264Main/VAEntrypointEncSlice
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
    VAConfigAttribRateControl              : VA_RC_CBR
                                             VA_RC_VBR
                                             VA_RC_CQP
    VAConfigAttribEncPackedHeaders         : VA_ENC_PACKED_HEADER_NONE
    VAConfigAttribEncMaxRefFrames          : l0=1
                                             l1=0
    VAConfigAttribEncRateControlExt        : max_num_temporal_layers_minus1=3 temporal_layer_bitrate_control_flag=1

VAProfileH264High/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileH264High/VAEntrypointEncSlice
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
    VAConfigAttribRateControl              : VA_RC_CBR
                                             VA_RC_VBR
                                             VA_RC_CQP
    VAConfigAttribEncPackedHeaders         : VA_ENC_PACKED_HEADER_NONE
    VAConfigAttribEncMaxRefFrames          : l0=1
                                             l1=0
    VAConfigAttribEncRateControlExt        : max_num_temporal_layers_minus1=3 temporal_layer_bitrate_control_flag=1

VAProfileHEVCMain/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileHEVCMain/VAEntrypointEncSlice
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
    VAConfigAttribRateControl              : VA_RC_CBR
                                             VA_RC_VBR
                                             VA_RC_CQP
    VAConfigAttribEncPackedHeaders         : VA_ENC_PACKED_HEADER_SEQUENCE
    VAConfigAttribEncMaxRefFrames          : l0=1
                                             l1=0

VAProfileHEVCMain10/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422
                                             VA_RT_FORMAT_YUV420_10
                                             VA_RT_FORMAT_YUV420_10BPP

VAProfileHEVCMain10/VAEntrypointEncSlice
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV420_10
                                             VA_RT_FORMAT_YUV420_10BPP
    VAConfigAttribRateControl              : VA_RC_CBR
                                             VA_RC_VBR
                                             VA_RC_CQP
    VAConfigAttribEncPackedHeaders         : VA_ENC_PACKED_HEADER_SEQUENCE
    VAConfigAttribEncMaxRefFrames          : l0=1
                                             l1=0

VAProfileJPEGBaseline/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileVP9Profile0/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422

VAProfileVP9Profile2/VAEntrypointVLD
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV422
                                             VA_RT_FORMAT_YUV420_10
                                             VA_RT_FORMAT_YUV420_10BPP

VAProfileNone/VAEntrypointVideoProc
    VAConfigAttribRTFormat                 : VA_RT_FORMAT_YUV420
                                             VA_RT_FORMAT_YUV420_10
                                             VA_RT_FORMAT_RGB32
                                             VA_RT_FORMAT_YUV420_10BPP
```

**Comment by tytan652** [comment]
@WizardCM since you have a Intel iGPU, I need a verbose log made with this PR Flatpak.
This is to check if I'm not the only one not having the Intel VAAPI extension enabled on the Flatpak.

`flatpak run com.obsproject.Studio --command="obs --verbose"`

**Comment by tytan652** [comment]
Now callback set to use `blog` rather than Libva original method to log message.

```
info: VAAPI: API version 1.15
debug: VAAPI: 'VA-API NVDEC driver' in use for device '/dev/dri/renderD128'
libva error: /usr/lib/dri/iHD_drv_video.so init failed
debug: VAAPI: 'Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1' in use for device '/dev/dri/renderD129'
info: FFMPEG VAAPI H264 encoding supported
```
Become:
```
info: VAAPI: API version 1.15
debug: VAAPI: 'VA-API NVDEC driver' in use for device '/dev/dri/renderD128'
debug: LIBVA ERROR: /usr/lib/dri/iHD_drv_video.so init failed
debug: VAAPI: 'Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1' in use for device '/dev/dri/renderD129'
info: FFMPEG VAAPI H264 encoding supported
```

File: plugins/obs-ffmpeg/obs-ffmpeg.c [hunk 1]
```diff
@@ -351,10 +358,18 @@ bool obs_module_load(void)
...
 	}
-#if !defined(_WIN32) && defined(LIBAVUTIL_VAAPI_AVAILABLE)
-	if (vaapi_supported()) {
-		blog(LOG_INFO, "FFMPEG VAAPI supported");
+#ifdef LIBAVUTIL_VAAPI_AVAILABLE
+	const char *libva_env = getenv("LIBVA_DRIVER_NAME");
+	if (!!libva_env)
+		blog(LOG_WARNING,
+		     "LIBVA_DRIVER_NAME variable is set,"
+		     " this could prevent FFMPEG VAAPI from working correctly");
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg.c:366]: Nit: FFmpeg

here and throughout

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 2]
```diff
@@ -0,0 +1,319 @@
...
+	if (drm_fd < 0) {
+		blog(LOG_ERROR, "VAAPI: Failed to open device '%s'",
+		     device_path);
+		return NULL;
+	}
+
+	va_dpy = vaGetDisplayDRM(drm_fd);
+
+	if (!va_dpy) {
+		blog(LOG_ERROR, "VAAPI: Failed to initialise drm display");
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:39]: Nit: initalize

Prefer US English.

Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:39]: If "drm" is an acronym, capitalize appropriately.

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 3]
```diff
@@ -0,0 +1,319 @@
...
+	va_status = vaQueryConfigProfiles(dpy, profile_list, &num_profiles);
+	if (va_status != VA_STATUS_SUCCESS) {
+		blog(LOG_ERROR,
+		     "VAAPI: Fail to query profiles from device '%s'",
+		     device_path);
+		goto error;
+	}
+
+	for (int i = 0; i < num_profiles; i++) {
+
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:151]: Remove blank line.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nits.

File: plugins/obs-ffmpeg/obs-ffmpeg.c (hunk 1 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg.c]: I fixed the naming in the whole encoder code.

**Comment by tytan652** [comment]
Just removed unused variable that I forgot to remove.

**Comment by tytan652** [comment]
Made the encoder fail if CBR is enforced and not supported by the device.

**Need review about this decision/change.**

**Comment by denisschultz** [comment]
> Made the encoder fail if CBR is enforced and not supported by the device.
> 
> **Need reviews about this decision/change.**

I don't know, if that help you by testing on a device that allowed it. But when it is relevant: It didn't break on my side. I can use it with CBR as intended.

File: plugins/obs-ffmpeg/data/locale/en-US.ini [hunk 4]
```diff
@@ -14,8 +14,7 @@ Level="Level"
 
 BFrames="Max B-frames"
 
-VAAPI.Codec="VAAPI Codec"
-VAAPI.Device="VAAPI Device"
+VAAPI.Device="VA-API Device"
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/data/locale/en-US.ini:17]: The official wiki uses VAAPI, while other/older sources use VA-API. I'm not sure there's merit in making this string change unless there is some official consensus that one is correct and one is not.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Just a nit on the string VA-API vs. VAAPI, per my inline comment:
> The official wiki uses VAAPI, while other/older sources use VA-API. I'm not sure there's merit in making this string change unless there is some official consensus that one is correct and one is not.

https://www.freedesktop.org/wiki/Software/vaapi/
vs.
https://01.org/linuxmedia/vaapi

**Comment by tytan652** [comment]
@WizardCM I need to know how the encoder actually (without the PR) behave with device that does not support CBR with OBS that enforce it with services.

In the last UI/UX my last changes was debated and the decision to remove it for now was taken.

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 5]
```diff
@@ -0,0 +1,311 @@
...
+	VADisplay va_dpy;
+	VAStatus va_status;
+	int major, minor;
+	const char *driver;
+
+	va_dpy = vaapi_open_display_drm(device_path);
+	if (!va_dpy)
+		return NULL;
+
+	blog(LOG_DEBUG, "VAAPI: Initialising display in %s", func_name);
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:94]: Prefer US English.
Initialising -> Initializing

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 6]
```diff
@@ -0,0 +1,311 @@
...
+	VAEntrypoint entrypoint;
+	int num_entrypoints;
+
+	profile_list = bmalloc(vaMaxNumProfiles(dpy) * sizeof(VAProfile));
+	entrypoint_list = bmalloc(vaMaxNumProfiles(dpy) * sizeof(VAEntrypoint));
+
+	va_status = vaQueryConfigProfiles(dpy, profile_list, &num_profiles);
+	if (va_status != VA_STATUS_SUCCESS) {
+		blog(LOG_ERROR,
+		     "VAAPI: Fail to query profiles from device '%s'",
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:145]: Fail -> Failed

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 7]
```diff
@@ -0,0 +1,311 @@
...
+			continue;
+
+		va_status = vaQueryConfigEntrypoints(
+			dpy, profile, entrypoint_list, &num_entrypoints);
+		if (va_status == VA_STATUS_ERROR_UNSUPPORTED_PROFILE)
+			continue;
+
+		if (va_status != VA_STATUS_SUCCESS) {
+			blog(LOG_ERROR,
+			     "VAAPI: Fail to query entrypoints from the %s of the device '%s'",
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:163]: Fail -> Failed

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 8]
```diff
@@ -0,0 +1,311 @@
...
+
+			va_status = vaGetConfigAttributes(
+				dpy, profile, entrypoint, attrib_list, 1);
+			if (va_status == VA_STATUS_ERROR_UNSUPPORTED_PROFILE ||
+			    va_status == VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT)
+				continue;
+
+			if (va_status != VA_STATUS_SUCCESS) {
+				blog(LOG_ERROR,
+				     "VAAPI: Fail to get RC attribute from the %s %s of the device '%s'",
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:186]: Fail -> Failed

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 9]
```diff
@@ -0,0 +1,311 @@
...
+	entrypoint_list = bmalloc(vaMaxNumProfiles(dpy) * sizeof(VAEntrypoint));
+
+	va_status = vaQueryConfigEntrypoints(dpy, profile, entrypoint_list,
+					     &num_entrypoints);
+	if (va_status == VA_STATUS_ERROR_UNSUPPORTED_PROFILE)
+		goto error;
+
+	if (va_status != VA_STATUS_SUCCESS) {
+		blog(LOG_ERROR,
+		     "VAAPI: Fail to query entrypoints from the %s of the device '%s'",
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:272]: Fail -> Failed

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 10]
```diff
@@ -0,0 +1,311 @@
...
+
+		va_status = vaGetConfigAttributes(dpy, profile, entrypoint,
+						  attrib_list, 1);
+		if (va_status == VA_STATUS_ERROR_UNSUPPORTED_PROFILE ||
+		    va_status == VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT)
+			continue;
+
+		if (va_status != VA_STATUS_SUCCESS) {
+			blog(LOG_ERROR,
+			     "VAAPI: Fail to get RC attribute from the %s %s of the device '%s'",
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/vaapi-utils.c:295]: Fail -> Failed

**Review by RytoEX — CHANGES_REQUESTED** [review]
Some additional string nits.

**Comment by tytan652** [comment]
Strings fixed.

**Comment by WizardCM** [comment]
I've retested this, and the UI now correctly names my integrated GPU and correctly hides unsupported modes.

image

However it seems that in a profile I previously used now shows "No properties available" for a pre-configured streaming profile. Switching to x264 and back does restore the properties. Additionally, the other 3 Profiles I have configured with VAAPI don't have this issue. It could be an edge case.

image

It does look like all VAAPI configs that previously had non-CQP rate controls enabled are now visually set to CQP in the UI,

-----

Separately, if an invalid GPU is selected somehow (unsure how, likely from a previous iteration of this PR), then attempting to go live will fail.

```
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
info: ---------------------------------
info: [FFmpeg VAAPI encoder: 'advanced_video_recording'] settings:
	device:       /dev/dri/by-path/pci-0000:09:00.0-render
	rate_control: CQP
	profile:      578
	level:        40
	qp:           16
	bitrate:      0
	maxrate:      0
	keyint:       120
	width:        1920
	height:       1080
	b-frames:     0

[AVHWDeviceContext @ 0x556c9969ac00] No VA display found for device /dev/dri/by-path/pci-0000:09:00.0-render.
warning: [FFmpeg VAAPI encoder: 'advanced_video_recording'] Failed to create VAAPI device context: Invalid argument
```

Then, attempting to change the device and rate control to the same element in the dropdown will cause an immediate crash.

```
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: VAAPI: Failed to open device '/dev/dri/by-path/pci-0000:09:00.0-render'
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: VAAPI: Failed to query profiles from device '/dev/dri/by-path/pci-0000:09:00.0-render'
info: Settings changed (outputs)
info: ------------------------------------------------
#0 0x7fad01d787b3 <unknown>
#1 0x7fad01e1e6fc <unknown>
#2 0x7fad01e1e5d0 <unknown>
#3 0x7fad01e0f6cd <unknown>
#4 0x7fad01e384ba <unknown>
#5 0x7fad01d8fa88 <unknown>
#6 0x7fad00358738 <unknown>
#7 0x7fad0033399f <unknown>
#8 0x7fad00333693 <unknown>
#9 0x7fad003541bd <unknown>
#10 0x7fad01e37b30 <unknown>
#11 0x7fad01f7c7ad <unknown>
#12 0x7fad01e37e91 <unknown>
#13 0x7fad01ddf7dd <unknown>
#14 0x7fad01db141b <unknown>
#15 0x7fad01df7df8 <unknown>
#16 0x7facffd1a660 <unknown>
#17 0x7fad01df7f82 <unknown>
#18 0x7fad01e1a4ef <unknown>
#19 0x7fad93641b43 <unknown>
Trace/breakpoint trap (core dumped)
```

Unfortunately the config was saved so the crash is no longer an issue on my setup so I can't get a proper trace.

**Comment by tytan652** [comment]
I need to care about previous version profile.

Does the bmalloc warnings appeared because of my PR ?

**Comment by tytan652** [comment]
I found the reason of the crash, forgot to close the va display on a callback.

**Comment by tytan652** [comment]
I made a re-work of this, now the VAAPI code is less H264-centric.

**Comment by norihiro** [comment]
I tested with Radeon RX 6600 and Intel Core i7-7700 with this PR rebased to the latest master. It looks ok; both Navi 23 and HD Graphics 630 are listed on the output settings.
https://obsproject.com/logs/ns3sBPWL9RZUGt2H

**Comment by tytan652** [comment]
OK, I need to add test for all h264 profile ans control rate then.

**Comment by Fenrirthviti** [comment]
What is left that we need to test for this one? Can we get a summary of what is left, so that we can get the last bit of testing for this done?

**Comment by tytan652** [comment]
@Fenrirthviti:
- Not show card that don't support H264 encode was tested on my machine (Desktop with GTX 970 + Intel iGPU).
- Show only compatible rate control was tested by @WizardCM.
- I got positive feedback from Denis (Tiberium) and Cookie who are AMD users.

I guess there is nothing left to test as it is.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c [hunk 11]
```diff
@@ -511,18 +512,73 @@ static void set_visible(obs_properties_t *ppts, const char *name, bool visible)
 
 static void vaapi_defaults(obs_data_t *settings)
 {
-	obs_data_set_default_string(settings, "vaapi_device",
-				    "/dev/dri/renderD128");
+	const char *device = vaapi_get_h264_default_device();
+	VADisplay va_dpy;
```
Comment (kkartaltepe) [inline plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:516]: Declare `va_dpy` where it is assigned instead.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c [hunk 12]
```diff
@@ -511,18 +512,73 @@ static void set_visible(obs_properties_t *ppts, const char *name, bool visible)
...
+	va_dpy = vaapi_open_device(device, "vaapi_defaults");
+
+	if (vaapi_device_rc_supported(VAProfileH264ConstrainedBaseline, va_dpy,
+				      VA_RC_CBR, device))
+		obs_data_set_default_string(settings, "rate_control", "CBR");
+	else if (vaapi_device_rc_supported(VAProfileH264ConstrainedBaseline,
+					   va_dpy, VA_RC_CQP, device))
+		obs_data_set_default_string(settings, "rate_control", "CQP");
+	else
+		obs_data_set_default_string(settings, "rate_control", "VBR");
```
Comment (kkartaltepe) [inline plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:538]: Why change the default mode to VBR from CBR? I can understand adding a fallback here for things like intel that only support CQP on free drivers, but VBR is just as unsupported as CBR on these drivers.

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 13]
```diff
@@ -0,0 +1,263 @@
...
+
+	char path[32] = "/dev/dri/renderD1";
+	for (int i = 28;; i++) {
+		sprintf(path, "/dev/dri/renderD1%d", i);
+		if (access(path, F_OK) != 0)
+			break;
+
+		ret = vaapi_device_h264_supported(path);
+		if (ret) {
+			default_h264_device = strdup(path);
```
Comment (kkartaltepe) [inline plugins/obs-ffmpeg/vaapi-utils.c:252]: this side effect is hard to see, personally id prefer you just move this code into `vaapi_get_h264_default_device` function and move `default_h264_device` into a function local static so you can return it immediately if its non-null. In  ffmpeg you can try and get the default device and if we return a null string we can assume no vaapi devices exist and return appropriately.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c [hunk 14]
```diff
@@ -511,18 +512,73 @@ static void set_visible(obs_properties_t *ppts, const char *name, bool visible)
...
+	vaapi_close_device(va_dpy);
+}
+
+static bool vaapi_device_modified(obs_properties_t *ppts, obs_property_t *p,
+				  obs_data_t *settings)
+{
+	UNUSED_PARAMETER(p);
+
+	const char *device = obs_data_get_string(settings, "vaapi_device");
+	VADisplay va_dpy = vaapi_open_device(device, "vaapi_device_modified");
```
Comment (kkartaltepe) [inline plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:549]: va_dpy is used unchecked here.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c [hunk 15]
```diff
@@ -511,18 +512,73 @@ static void set_visible(obs_properties_t *ppts, const char *name, bool visible)
...
 	obs_data_set_default_int(settings, "level", 40);
 	obs_data_set_default_int(settings, "bitrate", 2500);
 	obs_data_set_default_int(settings, "keyint_sec", 0);
 	obs_data_set_default_int(settings, "bf", 0);
 	obs_data_set_default_int(settings, "rendermode", 0);
-	obs_data_set_default_string(settings, "rate_control", "CBR");
 	obs_data_set_default_int(settings, "qp", 20);
 	obs_data_set_default_int(settings, "maxrate", 0);
+
+	va_dpy = vaapi_open_device(device, "vaapi_defaults");
```
Comment (kkartaltepe) [inline plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:529]: va_dpy is used unchecked here.

File: plugins/obs-ffmpeg/vaapi-utils.c [hunk 16]
```diff
@@ -0,0 +1,263 @@
...
+static const char *default_h264_device = NULL;
+
+static VADisplay vaapi_open_display_drm(const char *device_path)
+{
+	VADisplay va_dpy;
+
+	if (!device_path)
+		return NULL;
+
+	drm_fd = open(device_path, O_RDWR);
```
Comment (kkartaltepe) [inline plugins/obs-ffmpeg/vaapi-utils.c:29]: `vaapi_open` is being called from callbacks, id prefer if we actually handle the `drm_fd` in a reentrant way.

**Review by kkartaltepe — APPROVED** [review]

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c (hunk 12 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:538]: We have no guarantee that a driver will provide CBR, VBR and CQP or only CQP.

It just avoid to put a wrong value as default.

Comment (kkartaltepe) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:538]: sorry i mean, if we are going to have an else branch and change it from CBR it seems the best choice is CQP not VBR. Since CQP is more supported on intel and amd just supports all 3 mostly?

Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:538]: `else` is now CQP

Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c:538]: It was mistake from me for the order.

File: plugins/obs-ffmpeg/vaapi-utils.c (hunk 13 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/vaapi-utils.c:255]: Making `vaapi_get_h264_default_device` "local static" is not possible since I want to keep all pure VAAPI function in only one C file.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c (hunk 11 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c]: Changes done waiting for your re-review before squashing.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c (hunk 14 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c]: Changes done waiting for your re-review before squashing.

File: plugins/obs-ffmpeg/vaapi-utils.c (hunk 16 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/vaapi-utils.c]: Changes done waiting for your re-review before squashing.

File: plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c (hunk 15 above)
Comment (tytan652) [reply plugins/obs-ffmpeg/obs-ffmpeg-vaapi.c]: Changes done waiting for your re-review before squashing.

File: plugins/obs-ffmpeg/vaapi-utils.c (hunk 13 above)
Comment (kkartaltepe) [reply plugins/obs-ffmpeg/vaapi-utils.c]: Sorry im not sure what the appropriate name for what i mean is. https://gist.github.com/kkartaltepe/ce473226346f95c98470e5e9f5fd41a3 this is what i mean (but also just deleting the `vaapi_h264_supported` and calling `vaapi_get_h264_default_device` in the ffmpeg portion is probably even better).

Comment (tytan652) [reply plugins/obs-ffmpeg/vaapi-utils.c]: Made the change, to get rid of `vaapi_h264_supported` I added a comment to explain why `vaapi_get_h264_default_device` is used to check if H264 is supported.

**Comment by kkartaltepe** [comment]
looks good to me, feel free to squash up the changes.

**Review by WizardCM — APPROVED** [review]
Looks good to me.

image
