### PR TITLE
win-capture: Invert destination pixels when drawing monochrome cursors

### LINKED ISSUE #3129: Despite mouse capture being turned on, the mouse doesn't get recorded in the code editor tab of JetBrains programs (tested with Android Studio & IntelliJ)
## Platform
Operating system and version: Windows 10 Pro Version 1903
OBS Studio version: 24.0.3

## Expected Behavior
When mouse capture is turned on for screen captures, it should always capture the mouse.

## Current Behavior
In JetBrains programs the mouse doesn't get captured only in the code editor tab (tested with Android Studio and IntelliJ).

## Steps to Reproduce
This is how it looks like:
https://streamable.com/zzzj0h
Someone told me, this doesn't happen on Linux, however I don't have any evidence for that. To reproduce it, just use my OBS version with Windows and a JetBrains program such as Android Studio.

### LINKED ISSUE #6794: Monochrome cursors on Windows are recorded as all-black instead of the correct color
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When a monochrome cursor is visible on top of a black background, it should appear white in the OBS recording

### Current Behavior

When a monochrome cursor is visible on top of a dark background, it currently appears black. It will be completely invisible on a black background, or very hard to see on a dark grey background.

### Steps to Reproduce

1. Start recording in OBS on Windows
2. Hover cursor over any application that uses a dark background and a monochrome cursor such as the I-Beam (Visual Studio dark mode, VS Code, etc)
3. Observe that the cursor recorded by OBS is nearly invisible because it is black instead of white

### Anything else we should know?

There are two types of cursors in windows: coloured, and monochrome. 

For coloured cursors, there are two bitmaps (`hbmColor` and `hbmMask`) and the usage is straight forward. This is working correctly in OBS.
image of coloured cursors

For monochrome cursors, there is only a single bitmap (`hbmMask`). This is currently **not working** in OBS, it will always be shown as black and will not correctly invert what is underneath it.
image of monochrome cursor

When drawing the cursor on to the captured surface, the top half of this monochrome cursor must first be applied with an AND operation to the recorded frame. In the example image provided above, this is a no-op because it is all white. The bottom half of the monochrome bitmap must then be applied to the recorded frame as XOR operation, so it will invert any colour underneath it. Using this technique a monochrome cursor is capable of drawing always-black, always-white, or background-inverted pixels. 

For example:
 - A pixel that is black in both the top and bottom half will always be black in the final image
 - A pixel that is black in the top and white in the bottom will always be white in the final image
 - A pixel that is white in the top and white in the bottom will invert (XOR) the colour underneath it.
 - A pixel that is white in the top and black in the bottom is a no-op.

The [current implementation of `cursor_capture_icon`](https://github.com/obsproject/obs-studio/blob/db8145e8a2f1e1d0a3cba671504f6a56c2e2200c/plugins/win-capture/cursor-capture.c#L159) seems to flatten both halves of the monochrome cursor in `copy_from_mask` into a single bitmap of half the height which is then returned in `cursor_data`. It's important however that both the AND and XOR layers of the monochrome cursor are preserved until they are drawn on to the recording.

### PR DESCRIPTION
**Pull request by caesay**
### Issue / Motivation
Currently all monochrome cursors are always rendered all-black, meaning they are invisible on dark backgrounds (see #6794).

### Description
This updates the blend mode from GS_BLEND_SRCALPHA to GS_BLEND_INVDSTCOLOR when drawing monochrome cursors, so they are visible on both light and dark backgrounds.

The following monochrome cursor rendering requirements are complete: 
- [x] A pixel that is black in both the top and bottom half will always be black in the final image.
- [x] A pixel that is black in the top and white in the bottom will always be white in the final image.
- [x] A pixel that is white in the top and white in the bottom will invert (XOR) the colour underneath it.
- [x] A pixel that is white in the top and black in the bottom is a no-op.

### How Has This Been Tested?
Tested on Windows 10 x64 with all of the baked-in Windows cursors. All color cursors remain unchanged, monochrome cursors (such as the I-Beam and Crosshair) are now rendered inverted instead of black. This should have no impact on any other areas of the code.

### Types of changes
Bug Fix

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

Maintainer Edit: Fixes #3129, fixes #6794

### CODE REVIEW

**Comment by caesay** [comment]
This potentially fixes/closes the following issues: #6794 #3454 #3129.

**Comment by caesay** [comment]
Squashed two commits together and rebased to 1a7e5babc2033200381a208d3c90e51a309178fe

File: plugins/win-capture/cursor-capture.c [hunk 1]
```diff
@@ -228,9 +237,13 @@ void cursor_draw(struct cursor_data *data, long x_offset, long y_offset,
 
 	if (data->visible && !!data->texture) {
 		gs_blend_state_push();
-		gs_blend_function_separate(GS_BLEND_SRCALPHA,
-					   GS_BLEND_INVSRCALPHA, GS_BLEND_ONE,
-					   GS_BLEND_INVSRCALPHA);
+
+		auto blendMode = data->monochrome ? GS_BLEND_INVDSTCOLOR
```
Comment (jpark37) [inline plugins/win-capture/cursor-capture.c:241]: This is old-school auto and implied int. Please use the real type.

**Comment by caesay** [comment]
I have made the requested changes and rebased to `release/28.1`.

**Comment by RytoEX** [comment]
> I have made the requested changes and rebased to `release/28.1`.

Always rebase to master when targeting the master branch. While the branches may sometimes be in sync, this is not always the case and is never guaranteed.

**Review by RytoEX — APPROVED** [review]
Tested on Windows 10 with Display Capture with DXGI with Visual Studio in dark mode and confirmed that this fixes the linked Issues.
