### PR TITLE
linux-v4l2: fixup mjpeg pixel format computation

### LINKED ISSUE #5821: 4:2:0 camera is being treated as 4:2:2 (No auto  detection) in Motion JPEG
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

Git

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/tU1WEc26GRSSFL4l

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Clean video, v4l2 
https://www.youtube.com/watch?v=VlyNBIg4goQ&feature=youtu.be
qv4l2 works fine

### Current Behavior

https://www.youtube.com/watch?v=VqWTLZN6VgI
Glitching

### Steps to Reproduce

1. Load up  camera
2. Pick mjpeg
3. Select any resolution
...

### Anything else we should know?

To me it seems to be with avcodec or the implementation of avcodec for decoding mjpeg. Testing qv4l2 to display an image, it works fine this program atleast from what I can tell it's own decoder to decode mjpeg.

Edit:
Camera model: avermedia pw513

This is the only camera that acts up that I have.
Does not work properly in guvcview
Works in qv4l2 though.

### PR DESCRIPTION
**Pull request by kkartaltepe**
### Description

Previously we assumed mjpeg was always decoded to 422 but it seems some
cameras provide different pixel formats such as 420.

This change delays setting the obs frame pixel format until after we
have decoded the v4l2 frame.

fixes #5821

### Motivation and Context

People prefer when their webcams render correctly.

### How Has This Been Tested?

My c920 with mjpeg remains unchanged. Hopefully the users from the issue can test this with their webcams.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/linux-v4l2/v4l2-mjpeg.c [hunk 1]
```diff
@@ -45,7 +45,7 @@ int v4l2_init_mjpeg(struct v4l2_mjpeg_decoder *decoder)
 	}
 
 	decoder->context->flags2 |= AV_CODEC_FLAG2_FAST;
-	decoder->context->pix_fmt = AV_PIX_FMT_YUVJ422P;
+	// decoder->context->pix_fmt = AV_PIX_FMT_YUVJ422P;
```
Comment (RytoEX) [inline plugins/linux-v4l2/v4l2-mjpeg.c:48]: Would prefer removing this line entirely before merging.

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nitpick about commented out code.

File: plugins/linux-v4l2/v4l2-mjpeg.c (hunk 1 above)
Comment (kkartaltepe) [reply plugins/linux-v4l2/v4l2-mjpeg.c]: Yea forgot to clean that up. Done

**Comment by fbievan** [comment]
Works fine for me.

**Comment by fbievan** [comment]
https://www.youtube.com/watch?v=zBeAQCnFCy0
heres my demonstration of it. First camera (the one that looks decent) is yuvj420 whileas other is yuvj442. GG

**Review by GeorgesStavracas — CHANGES_REQUESTED** [review]
Hi @kkartaltepe, not an expert in v4l2 but I think the code is correct. Could you please reword the commit title to something like `linux-v4l2: Use proper video format for MJPEG`?

**Comment by kkartaltepe** [comment]
Updated.

**Review by GeorgesStavracas — APPROVED** [review]
This should be cherry-picked into 27.2
