### PR TITLE
libobs: Fix deferred update sometimes using stale data

### LINKED ISSUE #3236: plugin update callback not called with most recent settings when callback is slow
## Platform

Operating system and version: Windows + Linux
OBS Studio version: master

## Current Behavior 

Observe the log output (and the visual preview). See that the log message prints the width with values like `1` `12` `123` but never `1234` (in my 10 tests). See that the input  field contains `1234`.

## Expected Behavior

The update callback should be called with `1234`. It might also be called with partial input but definitely with the final one.

## Steps to Reproduce

I am using the color source to illustrate my point. Modify the `update` callback to be slow by adding a one second sleep and logging the user settings.

```diff
diff --git a/plugins/image-source/color-source.c b/plugins/image-source/color-source.c
index b2e08747..c9a087c1 100644
--- a/plugins/image-source/color-source.c
+++ b/plugins/image-source/color-source.c
@@ -1,4 +1,5 @@
 #include <obs-module.h>
+#include <threads.h>
 
 struct color_source {
 	uint32_t color;
@@ -25,6 +26,8 @@ static void color_source_update(void *data, obs_data_t *settings)
 	context->color = color;
 	context->width = width;
 	context->height = height;
+    blog(LOG_WARNING, "update %u %u", context->width, context->height);
+    thrd_sleep(&(struct timespec){.tv_sec=1}, NULL);
 }
 
 static void *color_source_create(obs_data_t *settings, obs_source_t *source)
```

1. Start obs with this modified version (I compile everything from scratch).
2. Create an image source.
3. Go into its properties.
4. Go into the `Width` input field, select the whole text and delete so that the box is empty. 
5. With one quick rolling motion on your keyboard enter `1234`.

## Additional information

This means that the source did not update to the correct most recent settings despite the user interface showing this as the current value.
This is related to the callback being slow. Without the sleep I could not reproduce this. I originally noticed this when debugging a real third party plugin whose update is naturally slow (not as bad as 1 second slow, but haven't measured the real time).

### PR DESCRIPTION
**Pull request by e00E**
### Description

Currently we use a bool flag to signal the video thread that it should
call obs_source_deferred_update. This does not work correctly when the
update callback is slow and the update is triggered faster than the
callback can complete.

For example:
* the settings are set to state A
* defer_update is set
* obs_source_deferred_update is called and enters into the callback
* the callback starts making use of the settings in state A
* the settings are set to state B
* defer_update stays set
* the callback finishes
* defer_update is set to false

Now defer_update is false but the callback has only observed settings in
state A but not B.

This commit fixes this bug by keeping an update counter. If the counter
has changed while we were in the callback we know that we need to update
again.

The counter is atomic. The current version uses a plain bool which is a
data race as the value is written and read in parallel.

### Motivation and Context

Fixes #3236 .

### How Has This Been Tested?

Tested with the diff and reproduction steps in the issue. The callback is called until it has observed the most recent update.

### Types of changes

- Bug fix (non-breaking change which fixes an issue) -->

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch. (I'm assuming this refers to my branch but I don't understand why it's relevant.)
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: libobs/obs-internal.h [hunk 1]
```diff
@@ -17,6 +17,8 @@
 
 #pragma once
 
+#include <stdatomic.h>
```
Comment (e00E) [inline libobs/obs-internal.h:20]: I see that other code in this file is using volatile even though atomic is more appropriate. If there is an underlying reason let me know and we can use volatile here, too.

File: libobs/obs-source.c [hunk 2]
```diff
@@ -860,11 +860,15 @@ uint32_t obs_get_source_output_flags(const char *id)
...
-
-	source->defer_update = false;
+	if (source->context.data && source->info.update) {
+		uint32_t count;
+		do {
+			count = source->defer_update_count;
+			source->info.update(source->context.data,
+					    source->context.settings);
+		} while (!atomic_compare_exchange_strong(
+			&source->defer_update_count, &count, 0));
```
Comment (e00E) [inline libobs/obs-source.c:870]: Alternatively if we are afraid of blocking for too long, we can only do one update instead of the loop and let the next update be handled by the next video tick.

**Comment by e00E** [comment]
Build failures because MSVC does not support stdatomic. Will change to use `libobs/util/threading.h`.

File: libobs/obs-source.c [hunk 3]
```diff
@@ -860,11 +861,16 @@ uint32_t obs_get_source_output_flags(const char *id)
...
-	source->defer_update = false;
+	if (source->context.data && source->info.update) {
+		long count;
+		do {
+			count = os_atomic_load_long(
+				&source->defer_update_count);
+			source->info.update(source->context.data,
+					    source->context.settings);
+		} while (!os_atomic_compare_swap_long(
+			&source->defer_update_count, count, 0));
```
Comment (e00E) [inline libobs/obs-source.c:872]: Alternatively if we are afraid of blocking for too long, we can update only once instead of the loop and let the next update be handled by the next video tick.

Comment (kkartaltepe) [reply libobs/obs-source.c:871]: If there are 10 deferred updates this loop does not look like it will apply each of the 10 updates one after another. It looks like it will instead apply the latest update 10 times.

Comment (kkartaltepe) [reply libobs/obs-source.c:871]: Oh i see its a swap 0 not a dec. Sorry.

Comment (kkartaltepe) [reply libobs/obs-source.c:871]: But yes i do think it should be deferred again if someone made a new change. Applying all the updates now would stall rendering.

**Comment by kkartaltepe** [comment]
Thanks, I was able to replicate the issue in the bug report and this does fix it for me.
