### PR TITLE
libobs,obs-outputs: Fix librtmp1 dependency interference on some linuxes

### LINKED ISSUE #6226: Build Issues Interfering with RTMP Streaming
### Operating System Info

Other

### Other OS

Debian "Sid" (Unstable)

### OBS Studio Version

Git

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/NCBsaJp3j5vJGQOs

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

OBS should be able to connect to streaming services without crashing.

### Current Behavior

There are at least two issues here:

  1. A modification to `plugins/obs-outputs/CMakeLists.txt` in commit 49e9d49 caused symbols defined in obs-outputs to be made public.  This causes a recurrence of bug #98 where the plugin dynamically links to librtmp (if installed) instead of resolving the symbols internally.  The result is OBS crashes the instant you attempt streaming.
  2. Once the above link issue is resolved by setting default symbol visibility as hidden, OBS then claims to not be able to find the symbol `obs_load_module` in the obs-outputs plugin.  This is because the `EXPORT` macro in `libobs/util/c99defs.h` doesn't actually do anything on non-MSVC builds.

Additionally, if `ENABLE_RTMPS` is configured to `AUTO`, then cmake doesn't appear to correctly detect if the system package `libmbedtls-dev` is installed, and RTMP support won't be enabled.

### Steps to Reproduce

1. Install your system's `librtmp1` and `libmbedtls-dev` packages.
2. `git clone` obs-studio from top-of-tree
3. Create `build` directory; `ccmake ..` from it to configure and generate Makefiles.  (You may need to ensure `ENABLE_RTMPS` is set to `AUTO`.)
4. Build and install OBS.
5. Run OBS.  Click on Start Streaming.  The program will crash.  GDB backtrace will show the obs-outputs plugin is calling in to librtmp1.so, not its own RTMP functions.

### Anything else we should know?

The following patches seem to help get OBS working properly.  The first fixes the broken `EXPORT` macro.  The second ensures all symbols not explicitly exported are marked as hidden.

```diff
diff --git a/libobs/util/c99defs.h b/libobs/util/c99defs.h
index 995e179d3..1d0bb3dc6 100644
--- a/libobs/util/c99defs.h
+++ b/libobs/util/c99defs.h
@@ -50,7 +50,8 @@
 #ifdef _MSC_VER
 #define EXPORT __declspec(dllexport)
 #else
-#define EXPORT
+/*  This is a GNU C-ism; might not work in clang.  */
+#define EXPORT __attribute__((visibility("default")))
 #endif
 
 #include <stddef.h>
diff --git a/plugins/obs-outputs/CMakeLists.txt b/plugins/obs-outputs/CMakeLists.txt
index 124df673f..cde40922f 100644
--- a/plugins/obs-outputs/CMakeLists.txt
+++ b/plugins/obs-outputs/CMakeLists.txt
@@ -96,9 +96,11 @@ if(ENABLE_RTMPS STREQUAL "AUTO" OR ENABLE_RTMPS STREQUAL "ON")
       target_link_libraries(obs-outputs PRIVATE ${FOUNDATION_FRAMEWORK}
                                                 ${SECURITY_FRAMEWORK})
       set_target_properties(obs-outputs PROPERTIES CXX_VISIBILITY_PRESET hidden)
+      set_target_properties(obs-outputs PROPERTIES C_VISIBILITY_PRESET hidden)
 
     elseif(OS_POSIX)
       set_target_properties(obs-outputs PROPERTIES CXX_VISIBILITY_PRESET hidden)
+      set_target_properties(obs-outputs PROPERTIES C_VISIBILITY_PRESET hidden)
     endif()
   endif()
 else()
```

### PR DESCRIPTION
**Pull request by tt2468**
### Description
Details in #6226, basically this fixes an issue where OBS links to the system-installed librtmp1, which is incompatible with our librtmp.

Closes #6226 

### Motivation and Context
Spent all day trying to fix an ambiguous issue only to find that this hasn't been PR'd yet.

### How Has This Been Tested?
Without PR: OBS crashes when starting stream to RTMP server
With PR: No OBS crash any longer

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: libobs/util/c99defs.h [hunk 1]
```diff
@@ -50,7 +50,8 @@
 #ifdef _MSC_VER
 #define EXPORT __declspec(dllexport)
 #else
-#define EXPORT
+/*  This is a GNU C-ism; might not work in clang.  */
+#define EXPORT __attribute__((visibility("default")))
```
Comment (tytan652) [inline libobs/util/c99defs.h:54]: Clang seems to have it, so I think the comment can be removed right ?
Multiple version docs about this:
- https://releases.llvm.org/8.0.0/tools/clang/docs/LTOVisibility.html
- https://releases.llvm.org/10.0.0/tools/clang/docs/LTOVisibility.html
- https://clang.llvm.org/docs/LTOVisibility.html

**Comment by LGCW** [comment]
This sorted the RTMP crash on Debian 11.
