### PR TITLE
UI: Detect other instances of obs on Linux

### LINKED ISSUE #3053: [BUG] BSD and Linux can start multiple obs-studio instances without --multi warning
## Update:
MacOS part fixed by commit #3558 
Linux part fixed by #3654 

## Platform
Operating system and version:
FreeBSD 12.2 and current
~~Ubuntu mate Linux 20.04 & MacOS High Sierra 10.13.6~~
OBS Studio version:
25.03 & 25.08 & git commit build 05c9ddd

## Running multiple instances of obs-studio
Running multiple instances of obs-studio is actually a feature if used "responsible", however doing this unresponsible is sadly the case for BSD ~~and Linux and MacOS~~ users. Running another obs-studio instance while another is already running is easily done by accidently clicking its icon or running its command a second time which can have serieus affects on the current broadcast session like framedrops, blocking network ports, overwriting files etc besides confusing users with another instances where the capture devices are suddenly all black...

## Expected Behavior
When starting a second(/third/multiple) instance(s) of "obs-studio" while "obs-studio" was already running on BSD ~~and Linux and or MacOS~~, a warning window should pop up like on Microsoft Windows version of obs-studio which prevents the start of the second "obs-studio" instance until allowed explicitly by pressing "Launch Anyway".

## Current Behavior
The current wrong behaviour for BSD ~~and Linux and MacOS~~  is the same behaviour as using the Windows obs studio started with  `obs64.exe --multi` argument, which skips the warning Window. Using the "--multi" argument on BSD ~~and Linux and or MacOS~~ doesn't affect anything. ~~However MacOS is only affected when obs-studio has been started from the terminal since MacOS has its own sanitizing mechanism to prevent GUI apps to be run multiple times!~~

## Steps to Reproduce Ubuntu mate Linux 20.04 
0. open a terminal window
1. `sudo apt install obs-studio #default apt repository version 25.03 also affected`
2. `#run obs from terminal or from menu icon`
3. `#run another obs instance from terminal or from menu icon`
4. now you have two instances of obs-studio without a warning...

## Steps to Reproduce MacOS
1. Install latest OBS-Studio 25.08
2. run obs by clicking the application
3. open a terminal and run obs from the cli
4. `/Applications/OBS.app/Contents/MacOS/obs`
5. now you have two instances of obs-studio without a warning...

## Additional information
This file in the source code is probably the cause and maybe some ifdef unix:
https://github.com/obsproject/obs-studio/blob/master/UI/obs-app.cpp#L1800

### PR DESCRIPTION
**Pull request by clockley**
fixes: obsproject#3053

### Description
Detect multiple instances of OBS using anonymous socket the first instance
will be able to bind, subsequent instances will not. An advantage of this approach
is that the socket will be automatically be deleted if OBS crashes and the
socket will never be saved to disk. This disadvantage of this approach is that is not
portable to FreeBSD.

### How Has This Been Tested?

Include details of your testing environment (hardware, OS version, etc.)
Intel(R) Xeon(R) CPU E5-2697 
Fedora 23

Opened multiple copies of OBS and received prompt about multiple instances which does
not happen on linux without this patch.
### Types of changes

        - Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by kkartaltepe** [comment]
In the future, please dont open a new PR to make changes. You can force push your branch to make updates to your PR.

**Comment by clockley** [comment]
> In the future, please dont open a new PR to make changes. You can force push your branch to make updates to your PR.

Ok, I'll do that next time.

File: UI/platform-x11.cpp [hunk 1]
```diff
@@ -27,8 +27,34 @@
...
 using namespace std;
 
+
+#ifdef __linux__
+void RunningInstanceCheck(bool &already_running)
+{
+	int uniq = socket(AF_LOCAL, SOCK_DGRAM, 0);
+
+	if (uniq == -1) {
+		blog(LOG_ERROR, "socket: %i", errno);
```
Comment (kkartaltepe) [inline UI/platform-x11.cpp:45]: It seems like we should just return here and startup normally, since there is no hope of bind succeeding at this point no reason to prompt the user with something that may be wrong either.
Please also make the blog more useful "Failed to check for running instance, socket: %d".

**Comment by kkartaltepe** [comment]
Thanks for the fix. Works as expected on my machine.

File: UI/platform-x11.cpp (hunk 1 above)
Comment (clockley) [reply UI/platform-x11.cpp:45]: Ok, will change that

**Comment by alinsavix** [comment]
Instead of trying to bind to a socket, consider using flock(2), which will work on any open fd (even a read-only one). What I will frequently do in my own code is to have the code open a read-only fd of the application binary itself, and then flock on that fd. This has the advantage of being (slightly) simpler code, _and_ should also work on *BSD and pretty much any other unixy OS. 

(The downside is that if you replace the binary while OBS is running, it won't notice the existing instance if you fire up the new binary, assuming you use the OBS binary as the file you lock against., anyhow)

**Comment by kkartaltepe** [comment]
This is using a socket in the abstract namespace to avoid touching actual fd's or filesystems and dealing with any of of the downsides mentioned including whether or not locks are implemented on your fs. Though this abstract namespace is a linux extension or so the man page proclaims, im not a BSD expert.

**Comment by clockley** [comment]
> Instead of trying to bind to a socket, consider using flock(2), which will work on any open fd (even a read-only one). What I will frequently do in my own code is to have the code open a read-only fd of the application binary itself, and then flock on that fd. This has the advantage of being (slightly) simpler code, _and_ should also work on *BSD and pretty much any other unixy OS.
> 
> (The downside is that if you replace the binary while OBS is running, it won't notice the existing instance if you fire up the new binary, assuming you use the OBS binary as the file you lock against., anyhow)

The only safe option would be to create a lock/pid file in $HOME and check that. With Flatpack/snap and other sandboxes becoming  can't rely on being able to access the filesystem.

**Comment by clockley** [comment]
> > Instead of trying to bind to a socket, consider using flock(2), which will work on any open fd (even a read-only one). What I will frequently do in my own code is to have the code open a read-only fd of the application binary itself, and then flock on that fd. This has the advantage of being (slightly) simpler code, _and_ should also work on *BSD and pretty much any other unixy OS.
> > (The downside is that if you replace the binary while OBS is running, it won't notice the existing instance if you fire up the new binary, assuming you use the OBS binary as the file you lock against., anyhow)
> 
> The only safe option would be to create a lock/pid file in $HOME and check that. With Flatpack/snap and other sandboxes becoming can't rely on being able to access the filesystem.

**Comment by alinsavix** [comment]
> including whether or not locks are implemented on your fs

For the record, flock(2) does not need, want, or use any kind of locking support offered by a filesystem.

**Comment by clockley** [comment]
So after thinking about this for way too long it became clear that a naive flock() based approach could never work, I'll show why with the following example:
a) Instance 1 starts acquires lock to readlink("/proc/self/exe")
b) Instance 2 sees lock and warns user
c) Instance 1 exits/destroys lock
d) Instance 2 fails to acquire lock to file or acquires lock after...
e) Instance 3 check for lock does not find and/or and locks file. Instance 3 starts without warning user while instance 2 is running

Although the likelihood of this happening could be decreased considerably if Instance 2 blocks on lock acquisition in another thread, we cannot guarantee the kernel will schedule Instance 2 before Instance 3.
The only way to fix this issue is to use some kind of global mutex/semaphore or a list of kernel objects that persist the life of each instance.

I've attached a small program to demonstrate this phenomenon, first start one instance, start another, kill first then start another. You will note that second instance is not protected.
//-----------------------------------------------------------------------------------
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <sys/types.h>
#include <sys/file.h>

int main(void) {
	char buf[1024] = {0};
	readlink("/proc/self/exe", buf, sizeof(buf));
	
	int fd = open(buf, O_RDONLY|O_CLOEXEC);
	
	if (flock(fd, LOCK_EX|LOCK_NB) == 0) {
		printf("Gucci\n");
	} else {
		printf("locked up\n");
	}
	
	sleep(60);
}
//-----------------------------------------------------------------------------------

**Comment by kkartaltepe** [comment]
> So after thinking about this for way too long it became clear that a naive flock() ...

Its not clear to me how this is different in regards to the example run you outlined.

Currently you have been making a lot of changes to this PR. Please mark it as a WIP until you reach a design you are happy with.

**Comment by clockley** [comment]
So this patch creates/binds an abstract socket for each instance then triggers a warning if the number is greater than 1. bind() is atomic so reading /proc/net/unix will not introduce a race condition

**Comment by clockley** [comment]
The initial version of this or had the same race condition as the flock version, so I changed this patch. Although I could use a semaphore in a shared memory segment that would require code the cleanup on exit and crash detection
