### PR TITLE
frontend: Optimize audio mixer updates

### LINKED ISSUE #13300: Scene list type-to-select is laggy since 32.1.0 and no longer matches multi-letter input correctly
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

32.1.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/mUSROvuyclO5F2hX

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When typing multiple letters quickly in the Scenes list, OBS should treat them as one search string and jump directly to the matching scene name, as in OBS 32.0.4.
For example, typing abc should select the scene abc, or the first scene whose name starts with abc.

### Current Behavior

Since OBS 32.1.0, typing multiple letters quickly in the Scenes list no longer works correctly.
For example, when typing abc, OBS first jumps to the first scene starting with a, then the UI briefly lags, and after that it jumps to the first scene starting with b instead of matching abc.
During the short UI lag, UI elements cannot be interacted with.

https://github.com/user-attachments/assets/90c9878c-6fd1-4eac-8098-8e0c08557b0d

### Steps to Reproduce

1. Open OBS with a large scene collection
2. Click into the Scenes list
3. Quickly type the first letters of a scene name, for example abc
4. Observe that OBS processes the letters separately instead of as one combined string

### Anything else we should know?

- Also tested in Safe Mode
- The issue did not occur in OBS 32.0.4
- The issue started in OBS 32.1.0
- I have a large scene collection, which may make the issue more noticeable
- In the attached video, the blue key overlay shows which keys I am pressing for clarification

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
A few small changes for performance reasons to how the audio mixer handles updates.

- Avoid recreating the button icons every time state changes (oops)
- Only update control labels when layout changes, rather than the full state update calculation
- Hide widgets when their audio becomes inactive rather than delete them
- Skip unpolish when forcing style repaints, it's expensive and seems unneeded in my testing

### Motivation and Context
Looked into the report in #13300 and confirmed there was a regression in UI responsiveness with a very large number of audio sources in a scene.

My test collection has about 30 audio sources and seemed okay, but doubling that amount did make the issue more obvious.
The issue report above features a scene collection with well over 400.

Fixes #13300

### How Has This Been Tested?
The difference in performance is immediately noticeable, but I performed a rudimentary test anyway. I took screen recordings of the Scene list dock while holding down an arrow key and noted the time it took to reach the end of the list going down and then up.

#### Results
```
32.0.4
-------------------------
0.58s     Top    -> Bottom
0.62s     Bottom -> Top

32.1.1
-------------------------
1.48s     Top    -> Bottom
1.43s     Bottom -> Top

This PR
-------------------------
0.57s     Top    -> Bottom
0.65s     Bottom -> Top
```

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)
- Performance enhancement (non-breaking change which improves efficiency)

### Checklist:

- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.md).
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] My code follows the project's [**style guidelines**](https://github.com/obsproject/obs-studio/blob/master/CODESTYLE.md)
- [x] My code is not on the master branch.
- [x] My code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Review by RytoEX — APPROVED** [review]
Seems fine at a glance.

File: frontend/widgets/AudioMixer.cpp [hunk 1]
```diff
@@ -1053,8 +1054,8 @@ void AudioMixer::obsSourceAudioDeactivated(void *data, calldata_t *params)
 
 	if (flags & OBS_SOURCE_AUDIO) {
 		auto uuidPointer = obs_source_get_uuid(source);
-		QMetaObject::invokeMethod(static_cast<AudioMixer *>(data), "removeSource", Qt::QueuedConnection,
-					  Q_ARG(QString, QString::fromUtf8(uuidPointer)));
+		QMetaObject::invokeMethod(static_cast<AudioMixer *>(data), "updateControlVisibility",
```
Comment (PatTheMav) [inline frontend/widgets/AudioMixer.cpp]: Keeping an extra line around to hold the result of the cast would improve maintainability and debugging, but that's a nice-to-have.

**Review by PatTheMav — COMMENTED** [review]
So the main change is to create and cache the icons when a `VolumeControl` is created rather than lazily when each state is encountered the first time?

It also seems to me that if the control switches from unmuted to muted that the `QIcon` for the unmuted state is then destroyed and would need to be recreated when the source is unmuted again (which is when the "muted" `QIcon` is destroyed in turn)?

I'm also not sure whether `QIcon` should be kept as part of `VolumeControl`'s memory layout, because right now you effectively inserted the memory layout of that class 5x into the memory layout of the container:

```
Q_OBJECT Stuff
struct MixerStatus
std::unique_ptr<idian:Utils> utils
OBSWeakSource weakSource_
const char* uuid
<...>
QIcon unassignedIcon
    enum Mode
    enum State
    enum class ThemeIcon
    <...>
QIcon mutedIcon
    enum Mode
    enum State
    enum class ThemeIcon
    <...>
<and so on and so forth>
```
Which also means that if the memory layout of `QIcon` changes, the memory layout of `VolumeControl` implicitly changes with it. If this were instead pointers, their size would be "stable", but obviously require a bit more memory management.

**Comment by Warchamp7** [comment]
> So the main change is to create and cache the icons when a `VolumeControl` is created rather than lazily when each state is encountered the first time?

I think that change might actually be the least impactful of them all. But before, the icon was being created every time the state changed, not just the first time.

> It also seems to me that if the control switches from unmuted to muted that the QIcon for the unmuted state is then destroyed and would need to be recreated when the source is unmuted again (which is when the "muted" QIcon is destroyed in turn)?

With the changes in this PR, no. The changes in this PR create all the different icons when the widget is created, and swap _which_ of those icons is used on the buttons when state changes.

I updated the PR to make those icons static which should be cleaner and also better overall due to Qt's implicit sharing for QIcons.

File: frontend/widgets/AudioMixer.cpp [hunk 2]
```diff
@@ -1015,9 +1016,11 @@ void AudioMixer::obsSourceActivated(void *data, calldata_t *params)
 	uint32_t flags = obs_source_get_output_flags(source);
 
 	if (flags & OBS_SOURCE_AUDIO) {
+		auto mixer = static_cast<AudioMixer *>(data);
 		auto uuidPointer = obs_source_get_uuid(source);
-		QMetaObject::invokeMethod(static_cast<AudioMixer *>(data), "updateControlVisibility",
-					  Qt::QueuedConnection, Q_ARG(QString, QString::fromUtf8(uuidPointer)));
+
+		QMetaObject::invokeMethod(mixer, "updateControlVisibility", Qt::QueuedConnection,
```
Comment (derrod) [inline frontend/widgets/AudioMixer.cpp:1022]: This is minor but I do wonder if we should start always referencing the method directly, i.e. `QMetaObject::invokeMethod(mixer, &AudioMixer:updateControlVisibility, ...)`. It would prevent issues with broken connections (e.g. if the method was renamed or removed, which we had happen occasionally), and maybe improve performance because it doesn't need to do the name lookup either?

Comment (Warchamp7) [reply frontend/widgets/AudioMixer.cpp:1022]: We can't right now due to Ubuntu keeping us on a version of Qt that doesn't support that form.

Once we drop support for 24.04 I plan to replace every single one of these with a function pointer because I hate the headaches this already causes.

File: frontend/widgets/AudioMixer.cpp [hunk 3]
```diff
@@ -39,7 +39,7 @@
 
 #include "moc_AudioMixer.cpp"
 
-constexpr int GLOBAL_SOURCE_TOTAL = 6;
+constexpr int kGlobalSourceTotal = 6;
```
Comment (PatTheMav) [inline frontend/widgets/AudioMixer.cpp:42]: Semantically I would have no idea what a "global source total" is? Total of what? Not blocking for a merge, but a bit of a smell.

**Review by PatTheMav — COMMENTED** [review]
Nothing further jumped at me apart from the style nit.

File: frontend/widgets/AudioMixer.cpp (hunk 3 above)
Comment (Warchamp7) [reply frontend/widgets/AudioMixer.cpp:42]: It's the number of output sources to loop over via `obs_get_output_source(n)`.

It's a magic total for a magic internal detail and I'm not really sure what would be better.
