### PR TITLE
libobs: Duplicate URL string for OBS_BUTTON_URL

### LINKED ISSUE #5712: Link button not working
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

27.1.3

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/H539xmaggfEcaaGL

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When I click the Test button in the script, the URL opens in my browser.

### Current Behavior

Nothing happened.

### Steps to Reproduce

1. Add script below

```python3
import obspython as obs

def do_nothing():
    pass

def script_description():
    return "test"

def script_properties():
    props = obs.obs_properties_create()

    button = obs.obs_properties_add_button(props, "button", "Test", do_nothing)
    obs.obs_property_button_set_type(button, obs.OBS_BUTTON_URL)
    obs.obs_property_button_set_url(button, "https://localhost")

    return props
```
2. Click Test button

### Anything else we should know?

It worked normally when the lua script doing the same thing.

### PR DESCRIPTION
**Pull request by usakhelo**
### Description
The change includes allocation of a new string to store the string passed to the Python function

### Motivation and Context
Fixes #5712 

### How Has This Been Tested?
Tested using Python script from the issue description.
MacBook Air M1, MacOS 12.3

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [ ] I have included updates to all appropriate documentation.

### CODE REVIEW

File: libobs/obs-properties.c [hunk 1]
```diff
@@ -1119,7 +1119,7 @@ void obs_property_button_set_url(obs_property_t *p, char *url)
 	if (!data)
 		return;
 
-	data->url = url;
+	data->url = bstrdup(url);
```
Comment (WizardCM) [inline libobs/obs-properties.c:1122]: This value should be freed.

Comment (usakhelo) [reply libobs/obs-properties.c:1130]: Sorry I overlooked that. Added a cleanup function.

Comment (usakhelo) [reply libobs/obs-properties.c:1130]: Rebased and squashed commits.
