### PR TITLE
linux-v4l2: Change search strategy for v4l2loopback devices

### LINKED ISSUE #4347: linux-v4l2 : loopback device not found if video_nr > 63
## Platform

Operating system and version: Linux Fedora 33
OBS Studio version: obs-studio-26.1.2-1.fc33.x86_64
OBS Log file:

## Expected Behavior
Virtual Camera should be started when clicking the [Start Virtual Camera]  button

## Current Behavior
Nothing happens.
The log reveals : 
`warning: Failed to start virtual camera`

## Steps to Reproduce
1. sudo modprobe v4l2loopback
2. obs

## Additional information
/etc/modprobe.d/v4l2-loopback.conf contains : 
`options v4l2loopback devices=1 video_nr=99 card_label=VirtCam exclusive_caps=1`

OBS iterates over /dev/videoX, where X=0-63 ; this is probably due to **MAX_DEVICES=64** : 
https://github.com/obsproject/obs-studio/blame/9eb32eed18214eb3b292449fe46cd7749db86788/plugins/linux-v4l2/v4l2-output.c#L8

As a result, devices with a **video_nr >=64** (99 in the above example) are not found.

This neglects what @tovrstra already suggested in https://github.com/obsproject/obs-studio/pull/3182#discussion_r493162462 , i.e. iterating over the values in /sys/module/v4l2loopback/parameters/video_nr , which should resolve this issue.

### PR DESCRIPTION
**Pull request by fzwoch**
### Description

For Linux virtual camera output.

Don't blindly try all `/dev/video<0-63>` devices if they exist and can be opened, but instead scan
`/dev/` directory and try to open all `/dev/videoX` devices that are present in the tree.

Sorting of the tree is done with GLIBC's `versionsort` extension. So that `/dev/video9` is tried
before `/dev/video10`.

### Motivation and Context

Trying to fix #4347.

### How Has This Been Tested?

```shell
$ rmmod v4l2loopback
$ modprobe v4l2loopback video_nr=100
$ obs
```
Starting OBS virtual camera then correctly opens `/dev/video100`

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/linux-v4l2/v4l2-output.c [hunk 1]
```diff
@@ -175,19 +171,40 @@ static bool try_connect(void *data, int device)
...
+	int n;
 
 	if (!loopback_module_loaded()) {
 		if (loopback_module_load() != 0)
 			return false;
 	}
 
-	for (int i = 0; i < MAX_DEVICES; i++) {
-		if (!try_connect(vcam, i))
+	n = scandir("/dev", &list, NULL, versionsort);
```
Comment (kkartaltepe) [inline plugins/linux-v4l2/v4l2-output.c:183]: Trying to connect to every device is not appropriate, add a filter to restrict this list to video devices.

Comment (kkartaltepe) [reply plugins/linux-v4l2/v4l2-output.c:183]: I see you have the filter below consider moving it in here.

Comment (fzwoch) [reply plugins/linux-v4l2/v4l2-output.c]: Thanks for the feedback. Should be addressed by the latest push.

File: plugins/linux-v4l2/v4l2-output.c [hunk 2]
```diff
@@ -172,22 +168,45 @@ static bool try_connect(void *data, int device)
...
+			break;
+		}
 	}
 
+	while (n--)
+		free(list[n]);
+	free(list);
+
+	if (success)
+		return true;
```
Comment (GeorgesStavracas) [inline plugins/linux-v4l2/v4l2-output.c:208]: Very minor nitpick, but I'd suggest:

```c
	if (!success)
		blog(LOG_WARNING, "Failed to start virtual camera");

	return success
```

File: plugins/linux-v4l2/v4l2-output.c [hunk 3]
```diff
@@ -6,7 +6,8 @@
 #include <fcntl.h>
 #include <unistd.h>
 
-#define MAX_DEVICES 64
+#define __USE_GNU
```
Comment (GeorgesStavracas) [inline plugins/linux-v4l2/v4l2-output.c:9]: Is this really correct / okay to do here? According to [this old email](https://gcc.gnu.org/legacy-ml/fortran/2005-10/msg00365.html), `__USE_GNU` is not supposed to be defined by applications - apparently `_GNU_SOURCE` is what should be defined.

**Review by GeorgesStavracas — COMMENTED** [review]
Gave a quick look, had a couple of comments / questions

File: plugins/linux-v4l2/v4l2-output.c (hunk 2 above)
Comment (fzwoch) [reply plugins/linux-v4l2/v4l2-output.c]: I agree, that looks nicer.

File: plugins/linux-v4l2/v4l2-output.c (hunk 3 above)
Comment (fzwoch) [reply plugins/linux-v4l2/v4l2-output.c]: I had a feeling about that. I guess i simply followed the man page or peeked header file. Also I believe I tried `_GNU_SOURCE` before but didn't work on first try. I think it really just needed to be on the very top of the `#includes`, thanks.

Comment (GeorgesStavracas) [reply plugins/linux-v4l2/v4l2-output.c]: Would you mind explaining (in the commit message) why defining `_GNU_SOURCE` is necessary? Actually, does this commit work if you just don't define it?

Comment (fzwoch) [reply plugins/linux-v4l2/v4l2-output.c]: Yes it is necessary.
```C
n = scandir("/dev", &list, scanfilter, versionsort);
```
Here `versionsort` is a callback function that is a GNU extension.

Any suggestion for a log message wording?

Comment (GeorgesStavracas) [reply plugins/linux-v4l2/v4l2-output.c]: Perhaps something like:

```
Since versionsort() is a GNU extension, define _GNU_SOURCE at
the top of the source file.
```

Comment (fzwoch) [reply plugins/linux-v4l2/v4l2-output.c]: My brain came up with something similar. I hope that fits.

Comment (GeorgesStavracas) [reply plugins/linux-v4l2/v4l2-output.c]: Thank you!

**Review by GeorgesStavracas — APPROVED** [review]
Look great now, thank you!

**Review by kkartaltepe — APPROVED** [review]
