### PR TITLE
obs-filters: RTX denoiser initialization fix and code cleanup

### LINKED ISSUE #4441: obs-filters: NVAFX filter errors out when first added
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

Other

### OBS Studio Version (Other)

27.0-rc1

### OBS Studio Log URL

https://obsproject.com/logs/SuuBYH830bc3Tz0D

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Suppression intensity should be adjustable.

### Current Behavior

Intensity is not adjustable until OBS is restarted.

### Steps to Reproduce

1. Add filter
2. Try changing intensity
3. Notice no worky

### Anything else we should know?

Logs gets spammed with errors when trying to change intensity.

### PR DESCRIPTION
**Pull request by pkviet**
### Description
This fixes #4441 (first commit).
The second commit is a minor code cleanup:
- sets defaults intensity of RTX denoiser to max.
- adds an initialization check of nvafx.
- splits nvafx initialization from channel allocation for better
readability of the code.
- moves the intensity update from the filter_audio process function
to the plugin update function.
- logs the error code in case nvafx returns an error when running.
(useful for devs; I haven't translated the error codes which are
available in the sdk).

### Motivation and Context
- Fixes an issue.
- Code cleanup will make maintainance easier.

### How Has This Been Tested?
Tested that the issue is fixed and that the plugin works fien after the code cleanup.

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 
- Code cleanup (non-breaking change which makes code smaller or more readable) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/obs-filters/noise-suppress-filter.c [hunk 1]
```diff
@@ -325,29 +356,44 @@ static void noise_suppress_update(void *data, obs_data_t *s)
...
+	if (ng->nvafx_initialized && ng->use_nvafx) {
+		int err;
+		for (int i = 0; i < MAX_PREPROC_CHANNELS; i++) {
+			err = NvAFX_SetFloat(
+				ng->handle[i],
+				NVAFX_PARAM_DENOISER_INTENSITY_RATIO,
+				ng->intensity_ratio);
+			if (err != NVAFX_STATUS_SUCCESS) {
+				do_log(LOG_ERROR,
+				       "NvAFX_SetFloat(Intensity Ratio: %d) failed, error %i",
```
Comment (derrod) [inline plugins/obs-filters/noise-suppress-filter.c:377]: Is there a reason you're using `%d` here instead of `%f` the float?

**Comment by derrod** [comment]
Seems to fix it for me.

File: plugins/obs-filters/noise-suppress-filter.c (hunk 1 above)
Comment (pkviet) [reply plugins/obs-filters/noise-suppress-filter.c]: yeah i goofed. Thx
