### PR TITLE
linux-jack: Prepend devices with "OBS Studio: "

### LINKED ISSUE #7988: Jack client's name doesn't contain "OBS Studio" in it
### Operating System Info

Other

### Other OS

FreeBSD

### OBS Studio Version

28.1.2

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

n/a

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

n/a

### Current Behavior

it just says "JACK Input Client".
image
it should be "OBS Studio: JACK Input Client" instead.

### Steps to Reproduce

n/a

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by univrsal**
### Description
Prepends all devices created by the jack input client source with "OBS Studio: ".

### Motivation and Context
This makes it more clear that the device belongs to OBS.
Fixes #7988

screenshot

Since this changes the name of the clients this might impact existing setups that rely on the old device names without the prefix. 

### How Has This Been Tested?
- Created a Jack Input Client source
- Checked qpwgraph or any other patch bay for the prefix
- Exited obs and checked log to make sure there are no memory leaks

### Types of changes

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/linux-jack/jack-input.c [hunk 1]
```diff
@@ -76,8 +77,14 @@ static void jack_update(void *vptr, obs_data_t *settings)
 	if (!data->device || strcmp(data->device, new_device) != 0) {
 		if (data->device)
 			bfree(data->device);
-		data->device = bstrdup(new_device);
+		/* prefix all devices to make it clear that they belong to obs */
+		struct dstr device;
+		dstr_init(&device);
+		dstr_cat(&device, "OBS Studio: ");
+		dstr_cat(&device, new_device);
```
Comment (tytan652) [inline plugins/linux-jack/jack-input.c:84]:
```suggestion
		dstr_catf(&device, "OBS Studio: %s", new_device);
```

**Review by tytan652 — CHANGES_REQUESTED** [review]
Remove the unrelated submodule change.

**Review by GeorgesStavracas — APPROVED** [review]
