### PR TITLE
frontend: Audio Mixer bug fixes and adjustments

### LINKED ISSUE #13239: Horizontal Audio Mixer UI width pushed by dB indicator
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

32.1.0

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/2IUCMxtZAznh8B37

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When the Audio Mixer is in horizontal view, adjusting the volume level should not impact the width of the audio meter.

### Current Behavior

When the Audio Mixer is in horizontal view, adjusting the volume level also changes the width of the audio meter based on the current width of the decibel level indicator text.

Image

### Steps to Reproduce

1. Create any source that will appear in the Audio Mixer
2. Reduce the Audio Mixer dock to its minimum width
3. Change the audio level of any source using any method - each meter will get wider or narrower as the dB value changes

### Anything else we should know?

This is a fairly minor UI issue that doesn't have any functionality impact, but it would seem to be unintended behavior and is distracting to see, especially when making volume changes from external software/hardware.

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
- Add missing tooltips
  - Mute, Monitor and Toggle Hidden buttons were missing them
- Changed layout of the mixer in horizontal mode
  - Category labels are less visually noisy
  - Fixes #13239 indirectly
  - Rows are actually smaller than the old mixer now

|Old | Before | After |
| ------------- | ------------- | ------------- |
| image | image |image |

- Fix disabled sources appearing in the mixer
  - This was partially addressed in [#13118](https://github.com/obsproject/obs-studio/issues/13118) but another check was missed
- Fix mixer sorting weights
  - Pinned sources were incorrectly appearing before Global
- Improve VolumeMeter size calculation
  - Fixes a bug where the new mixer's minimum size was larger than the old one

| Old | Before | After |
| ------------- | ------------- | ------------- |
| image | image | image |
 
| Old | Before | After |
| ------------- | ------------- | ------------- |
| image | image | image |

- Fix mixer light theme colors
  - Wrong font color was used for some category labels
  - Changed some of the colors to look better
  
| Before | After |
| ------------- | ------------- |
| image | image |
  
- Add the toolbar actions to the options menu
obs64_V4eTCJgkaH

### Motivation and Context
Multiple fixes and adjustments based on user bug reports and feedback. Some of these are inadvertent regressions, some are mistakes, and some are changes based off feedback.

### How Has This Been Tested?
👁 on Windows

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality) 

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: frontend/components/VolumeMeter.cpp [hunk 1]
```diff
@@ -861,6 +853,14 @@ void VolumeMeter::paintEvent(QPaintEvent *)
 
 void VolumeMeter::resizeEvent(QResizeEvent *event)
 {
+	tickFont = font();
+	QFontInfo info(tickFont);
+	tickFont.setPointSizeF(info.pointSizeF() * meterFontScaling);
+
+	QFontMetrics metrics(tickFont);
+	// This is a quick and naive assumption for widest potential tick label.
+	tickTextTokenRect = metrics.size(Qt::TextSingleLine, "-88");
```
Comment (RytoEX) [inline frontend/components/VolumeMeter.cpp]: I suppose there isn't a way to get the label text (or largest label text), so we're just picking a negative double digit number to try to get the largest possible width?

Comment (Trying-Two-Code) [reply frontend/components/VolumeMeter.cpp]: Wouldn't it be better practice to at least create a variable above it assigned "-88" called widestTickLabel?

Comment (PatTheMav) [reply frontend/components/VolumeMeter.cpp]: Yeah I agree, given that this is supposed to be a "worst case" maximum value, it should only be computed once (if it cannot be determined statically). This could be made into a local runtime-initialised constant, so the size is not recalculated at every resize event (which I expect to happen very often, possibly even on every repaint)?

File: frontend/components/VolumeMeter.cpp [hunk 2]
```diff
@@ -888,13 +888,13 @@ QSize VolumeMeter::sizeHint() const
 
 	if (vertical) {
 		int width = meterRect.width() + tickTextTokenRect.width() + TICK_SIZE + 10;
-		int height = (labelTotal * tickTextTokenRect.height()) + INDICATOR_THICKNESS;
+		int height = (labelTotal * tickTextTokenRect.height() * 0.8) + INDICATOR_THICKNESS;
```
Comment (PatTheMav) [inline frontend/components/VolumeMeter.cpp]: In general we should avoid magic numbers and use proper `constexpr` values instead, with the added benefit of the constant name also providing context and meaning.

File: frontend/components/VolumeName.cpp [hunk 3]
```diff
@@ -26,6 +26,21 @@
 
 #include "moc_VolumeName.cpp"
 
+namespace {
+QString getPlainText(const QString &text)
+{
+	QString plainText = text;
+
+	if (plainText.contains("<") && plainText.contains(">")) {
```
Comment (PatTheMav) [inline frontend/components/VolumeName.cpp]: This is a quite expensive operation as potentially the entire string is scanned once (if no "<" is found) or even twice (if "<" is found, attempting to find the matching ">"), only to be scanned another time to create the `QTextDocument` and finally a last time to extract the plain text variant.

How regularly is this being executed? Why is there even HTML content in the String?

File: frontend/components/VolumeName.cpp [hunk 4]
```diff
@@ -72,13 +90,32 @@ QSize VolumeName::sizeHint() const
...
 	QSize contentsSize = style()->sizeFromContents(QStyle::CT_PushButton, &opt, QSize(width, height), this);
+
+	contentsSize.rwidth() += indicatorWidth;
+
 	return contentsSize;
 }
 
+QSize VolumeName::sizeHint() const
+{
+	QString plainText = getPlainText(fullText);
```
Comment (PatTheMav) [inline frontend/components/VolumeName.cpp:101]: See above, how often is the `sizeHint` call used?

File: frontend/widgets/AudioMixer.cpp [hunk 5]
```diff
@@ -179,6 +179,9 @@ AudioMixer::AudioMixer(QWidget *parent) : QFrame(parent)
 	toggleHiddenButton->setCheckable(true);
 	toggleHiddenButton->setChecked(showHidden);
 	toggleHiddenButton->setText(QTStr("Basic.AudioMixer.HiddenTotal").arg(0));
+	QString hiddenTooltip = showHidden ? QTStr("Basic.AudioMixer.HideHidden")
```
Comment (PatTheMav) [inline frontend/widgets/AudioMixer.cpp:182]: I find it a bit wasteful that we're not caching the `QString` instances created from the localisation strings, particularly as the strings will not chance between volume meter instances (and Qt will not "detect" that it's the same string underneath and combine all those `QString` instances into the same one.

I don't think a language change is done without an application relaunch, so those L10N strings can be created _once_ and cached throughout the application lifetime (even if just on the mixer itself) and then switching between the different tooltip texts would just involve replacing the underlying shared pointer of the new `QString`.

(Ideally `QTStr` would do all this caching behind the scenes, keeping a map of localisation identifiers to `QString` instances and lazily fill that map.)

File: frontend/widgets/AudioMixer.cpp [hunk 6]
```diff
@@ -644,27 +652,27 @@ void AudioMixer::updateVolumeLayouts()
...
 			}
 
-			if (!isGlobal) {
-				sortingWeight += 20;
-			}
-
-			if (!isPinned) {
-				sortingWeight += 20;
+			if (isGlobal) {
+				sortingWeight = 0;
```
Comment (PatTheMav) [inline frontend/widgets/AudioMixer.cpp:656]: All this code would benefit from named constants over magic numbers, as it would also force us to come up with a proper set of weight constants and not add arbitrary numerical values (as the current approach tempts one to do).

File: frontend/components/VolumeName.cpp (hunk 3 above)
Comment (Warchamp7) [reply frontend/components/VolumeName.cpp]: Because unfortunately the SourceTree labels support rich text. This is a dirty way to check for tags.

image

It does look like Qt itself has a `mightBeRichText` helper I can use instead though.
https://doc.qt.io/qt-6/qt-sub-qtgui.html#mightBeRichText

File: frontend/widgets/AudioMixer.cpp (hunk 6 above)
Comment (Warchamp7) [reply frontend/widgets/AudioMixer.cpp:656]: It's on my radar to do this a better way in the future.

File: frontend/components/VolumeName.cpp (hunk 4 above)
Comment (Warchamp7) [reply frontend/components/VolumeName.cpp:101]: Whenever the containing layout needs to reorder widgets. So when volume controls are added/removed, or the order changes.

File: frontend/widgets/AudioMixer.cpp (hunk 5 above)
Comment (Warchamp7) [reply frontend/widgets/AudioMixer.cpp:182]: Definitely an optimization I think we should look into outside this PR. We'd need a way to handle strings with arguments too.

File: frontend/components/VolumeMeter.cpp [hunk 7]
```diff
@@ -16,6 +16,9 @@ constexpr int INDICATOR_THICKNESS = 3;
 constexpr int CLIP_FLASH_DURATION_MS = 1000;
 constexpr int TICK_SIZE = 2;
 constexpr int TICK_DB_INTERVAL = 6;
+
+constexpr const char *TICK_LABEL_TOKEN = "-88";
```
Comment (RytoEX) [inline frontend/components/VolumeMeter.cpp:20]: Should this be ` -88 ` (with surrounding spaces) like the string it's replacing? Or is this sufficient?

File: frontend/data/themes/Yami.obt [hunk 8]
```diff
@@ -1764,26 +1768,30 @@ VolumeControl #volLabel {
 }
 
 #hVolumeWidgets .mixer-category {
-    min-width: 72px;    
     margin: var(--spacing_base);
+    padding: 0px var(--padding_xlarge);
```
Comment (RytoEX) [inline frontend/data/themes/Yami.obt:1772]:
```suggestion
    padding: 0 var(--padding_xlarge);
```

File: frontend/components/VolumeMeter.cpp (hunk 7 above)
Comment (Warchamp7) [reply frontend/components/VolumeMeter.cpp:20]: What

File: frontend/data/themes/Yami.obt (hunk 8 above)
Comment (Warchamp7) [reply frontend/data/themes/Yami.obt:1772]: What

File: frontend/components/VolumeMeter.cpp (hunk 7 above)
Comment (RytoEX) [reply frontend/components/VolumeMeter.cpp:20]: The original string is " -88 ", with surrounding spaces. This does not have surrounding spaces. My question is: did the surrounding spaces contribute to the width calculation in a meaningful way that is necessary to maintain here?

https://github.com/obsproject/obs-studio/pull/13244/changes#diff-9be536c20d790d97328fd240930a9feb04a7cc7ba2e870e8183693435cbc6722L498

Comment (Warchamp7) [reply frontend/components/VolumeMeter.cpp:20]: Ah. It was changed because the calculation logic itself has changed. So it was deliberate.

Comment (RytoEX) [reply frontend/components/VolumeMeter.cpp:20]: Got it. Thanks.

File: frontend/components/VolumeMeter.cpp [hunk 9]
```diff
@@ -16,6 +16,9 @@ constexpr int INDICATOR_THICKNESS = 3;
 constexpr int CLIP_FLASH_DURATION_MS = 1000;
 constexpr int TICK_SIZE = 2;
 constexpr int TICK_DB_INTERVAL = 6;
```
Comment (winex) [inline frontend/components/VolumeMeter.cpp:18]: i know this is correct mathematically, but (for halving) you will **never** teach 99.999% of users to **divide by 6** instead!

### suggestion
convert this to configurable option please, like IEC type vs other: 
- meter ticks: `5dB`, `6dB` (pro level)
- meter labels: every `5|6dB`, every `10|12dB` (pro level)

_p.s. finding this change wasn't trivial - it's behind 3 commits and refactoring in-between, bleh_
