### PR TITLE
frontend: Fix UI deadlock

### LINKED ISSUE #12456: Application freezes when opening Source properties after update to 31.1.2
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

31.1.2

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/9BdWkCukFyfT17RC

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

The Properties window should open so that the source can be configured.

### Current Behavior

The application freezes and must be force quit.

### Steps to Reproduce

1. Open OBS Studio
2. Add or select an existing Source (e.g., Video Capture Device, Image, Browser Source, etc.)
3. Right-click the Source and choose Properties
4. OBS immediately becomes not responding

Image

### Anything else we should know?

_No response_

### LINKED ISSUE #12499: OBS hangs forever when opening any source's properties
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

31.1.2

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/EwX8CvxLKi38W5BN

### OBS Studio Crash Log URL

https://obsproject.com/logs/jk31ZaXtuLIDVN7Y

### Expected Behavior

I expect to be able to open and modify a source object's properties as normal.

### Current Behavior

Currently, opening any source's properties has the properties window open; however, the main content does not scale to the entire width of the window, and the program hangs indefinitely.
https://github.com/user-attachments/assets/41e8dfe0-d24b-4ea6-b8ff-fb6bb0a00ce2

### Steps to Reproduce

1. Open OBS.
2. Open any source that has properties.
3. Hang OBS permanently. OBS never unhangs, so the Task Manager is required to kill the process.

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
Adds a single shot timer to delay opening the properties window after double clicking a source in the sources list.

Fixes #12499
Fixes #12456

### Motivation and Context
This works around a bug on Windows seemingly introduced around Qt 6.8.

When the Windows setting 'Snap mouse to default button in dialog boxes' is enabled, OBS hangs after double clicking the sources list. This seems to be some bizarre interaction between the drag event loop and the main application loop.

A QTimer of 1ms stops the program from completely hanging, but the application does not respond to events until the mouse is moved back over the sources list to presumably "finish" the started drag event.

20ms failed in a very very small number of cases so 200ms seems like a safe value as a bandaid here.

### How Has This Been Tested?
Opened properties a **lot** of times

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by notr1ch** [comment]
This workaround should probably be gated by a check for that mouse setting being turned on, or it will contribute to the application feeling slow.

**Comment by Warchamp7** [comment]
> This workaround should probably be gated by a check for that mouse setting being turned on, or it will contribute to the application feeling slow.

Added a check for the Windows setting being enabled

File: frontend/components/SourceTreeItem.cpp [hunk 1]
```diff
@@ -3,6 +3,10 @@
 #include <components/OBSSourceLabel.hpp>
 #include <widgets/OBSBasic.hpp>
 
+#ifdef _WIN32
+#include <windows.h>
+#endif
```
Comment (RytoEX) [inline frontend/components/SourceTreeItem.cpp]: Use WIN32_LEAN_AND_MEAN, and move this to just above the `moc\*.cpp` include.

File: frontend/components/SourceTreeItem.cpp [hunk 2]
```diff
@@ -268,7 +272,22 @@ void SourceTreeItem::mouseDoubleClickEvent(QMouseEvent *event)
 		obs_source_t *source = obs_sceneitem_get_source(sceneitem);
 		OBSBasic *main = OBSBasic::Get();
 		if (obs_source_configurable(source)) {
+#if defined(_WIN32)
+			/* This timer works around a bug introduced around Qt 6.8.3 that causes
+			 * the application to hang when double clicking the sources list and the
+			 * Windows setting 'Snap mouse to default button in dialog boxes' is enabled
+			 */
```
Comment (RytoEX) [inline frontend/components/SourceTreeItem.cpp]:
```suggestion
			/* This timer works around a bug introduced around Qt 6.8.3 that causes
			 * the application to hang when double clicking the sources list and the
			 * Windows setting 'Snap mouse to default button in dialog boxes' is enabled.
			 */
```

Would like to see a QTBUG opened for this.

**Comment by RytoEX** [comment]
Fixed feedback need to rebase.
