### PR TITLE
libobs: Fix PulseAudio monitoring when device is set to default

### LINKED ISSUE #8877: No sound from audio monitoring
### Operating System Info

Ubuntu 22.04

### Other OS

Linux Mint 21.1

### OBS Studio Version

29.1.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/wVZjZaNtJw0ik7Ov

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Have sound when monitoring is active

### Current Behavior

No sound when monitoring is active

### Steps to Reproduce

1. Set the Audio Monitoring of an audio source from the Audio Mixer to «Monitor Only» or «Monitor and Output»

### Anything else we should know?

Tested with the flatpak and the PPA version. Audio monitoring works in 29.0.2, but not in 29.1.0 and 29.1.1.

The audio output itself has no problem.

### PR DESCRIPTION
**Pull request by jp-bennett**
### Description
When the monitoring device is set to default, this bit of code was appending the no-longer-needed ".monitor' to the device name.

### Motivation and Context
Fixes #8877

### How Has This Been Tested?
Tested by Penwywern on Discord.

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by norihiro** [comment]
Please fold the commit message at 72 columns and fix the unmatched pair of double-quote and single-quote.

```patch
-When the monitoring device is set to default, this bit of code was appending the no-longer-needed ".monitor' to the device name.
+When the monitoring device is set to default, this bit of code was 
+appending the no-longer-needed ".monitor" to the device name.
```

**Comment by RytoEX** [comment]
To link a PR to an Issue, use magic keywords:
* https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests
* https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

**Comment by kkartaltepe** [comment]
I think i was able to replicate this the one time I tried after seeing the report but couldnt replicate it again... So im assuming this right given someone reported this working on bug and that I couldnt find anything broken with it.

Fixed up the commit message.

**Review by kkartaltepe — APPROVED** [review]

**Comment by norihiro** [comment]
For the monitoring, I think this is the right change.

However, this will break the prevention of the feedback-loop. Another function `devices_match` also depends on `get_default_id` and having `strcat(name2, ".monitor");`

Conditions to reproduce the failure of the feedback-loop prevention are as below. Be careful, this will result in outputting a huge noise.
- Leave `Desktop Audio` to the default.
- Set the monitor device (not default but set the device that is currently default).
- Enable the monitor of `Desktop Audio`.

**Comment by jp-bennett** [comment]
Yes, there's a problem there, I think. That compare function is now not consistent on whether it's using the ".monitor" names or not. I need to do some debugging work to make sure those values are getting set to what I think they are.

**Comment by jp-bennett** [comment]
@norihiro Second commit addresses that finding, thanks for pointing it out!

File: libobs/audio-monitoring/pulse/pulseaudio-wrapper.c [hunk 1]
```diff
@@ -61,28 +61,43 @@ void get_default_id(char **id)
...
+ *	selected monitoring output (id2).
+ */
 bool devices_match(const char *id1, const char *id2)
 {
 	bool match;
+	char *name_default = NULL;
 	char *name1 = NULL;
 	char *name2 = NULL;
 
+	get_default_id(&name_default);
```
Comment (kkartaltepe) [inline libobs/audio-monitoring/pulse/pulseaudio-wrapper.c:75]: Move this after the early return so that it wont leak the allocated string.

**Review by kkartaltepe — APPROVED** [review]

File: libobs/audio-monitoring/pulse/pulseaudio-wrapper.c (hunk 1 above)
Comment (jp-bennett) [reply libobs/audio-monitoring/pulse/pulseaudio-wrapper.c]: Good catch. Fixed.

**Comment by norihiro** [comment]
Thank you. I tested it and the feedback is ok.

The commit should be squashed into one. (but I hope this can be done when merging by Jim.)

I have a few minor cleanup comments in the change.
- Like the code for macOS and Windows, I'd like to suggest moving `get_default_id` inside the `if` clauses.
- Instead of `bzalloc(strlen(id1) + 9)`, `bstrdup` is fine for this.

```patch
diff --git a/libobs/audio-monitoring/pulse/pulseaudio-wrapper.c b/libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
index 50f637b3b..bb8b76973 100644
--- a/libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
+++ b/libobs/audio-monitoring/pulse/pulseaudio-wrapper.c
@@ -75,18 +75,18 @@ bool devices_match(const char *id1, const char *id2)
 	if (!id1 || !id2)
 		return false;
 
-	get_default_id(&name_default);
-
 	if (strcmp(id1, "default") == 0) {
+		get_default_id(&name_default);
 		name1 = bzalloc(strlen(name_default) + 9);
 		strcat(name1, name_default);
 		strcat(name1, ".monitor");
 	} else {
-		name1 = bzalloc(strlen(id1) + 9);
-		strcat(name1, id1);
+		name1 = bstrdup(id1);
 	}
 
 	if (strcmp(id2, "default") == 0) {
+		if (!name_default)
+			get_default_id(&name_default);
 		name2 = bzalloc(strlen(name_default) + 9);
 		strcat(name2, name_default);
 		strcat(name2, ".monitor");
```

File: libobs/audio-monitoring/pulse/pulseaudio-wrapper.c [hunk 2]
```diff
@@ -54,36 +54,50 @@ void get_default_id(char **id)
...
 	}
 
 	bfree(pdo);
 	pulseaudio_unref();
 }
 
+/**
+ * Checks whether a the sound source (id1) is the .monitor device for the
+ *	selected monitoring output (id2).
+ */
```
Comment (norihiro) [inline libobs/audio-monitoring/pulse/pulseaudio-wrapper.c:67]: I'm sorry I should have mentioned this as well at the comment yesterday.
There should be just one article for a noun. A  space is preferable inside the comment.
```suggestion
/**
 * Checks whether the sound source (id1) is the .monitor device for the
 * selected monitoring output (id2).
 */
```

Comment (jp-bennett) [reply libobs/audio-monitoring/pulse/pulseaudio-wrapper.c]: Looked at that comment fifteen times, and never saw the typo. Thanks!

**Review by norihiro — COMMENTED** [review]
Thank you so much for a lot of fixes.
I tested on Fedora 36 (using `pipewire-pulseaudio-0.3.67-1.fc36.x86_64`) and it works fine.
I think this can be merged (need to be squashed when merging).

**Review by RytoEX — APPROVED** [review]
Approved by @kkartaltepe off-thread.
