### PR TITLE
obs-outputs: Fix AV1 packet priority in RTMP

### LINKED ISSUE #10383: AV1 YouTube bitrate drop until stream restart
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

30.1.0

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/VJcmhy0uy4lERRpI

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

A stable AV1 stream to YouTube with a fairly beefy dedicated streaming PC.

### Current Behavior

Nvidia AV1 stream to YouTube randomly drops bitrate to ~160kbps and stays there until stream is restarted.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

I have been trying to stream with Nvidia AV1 for about a year now (since AV1 OBS release) and tried every new update. I never have similar issues with other encoders, so I dont think it has anything to do with my ISP. Im afraid the log doesnt show anything except :
**13:31:45.549: Output 'adv_stream': Number of dropped frames due to insufficient bandwidth/connection stalls: 6283 (1.0%)**
But let me repeat, my internet runs just fine and this only happens with AV1.

**During my stream (usually 16000 kbps), the bitrate drops to ~160kbps and stays there until I restart the stream.** Nothing seems to trigger this unfortunately and it happens at random time intervals (sometimes runs fine for days, other times drops every 10 minutes)

This issue seems to be random, but I think it happens more during weekends and busy hours. (So possibly YT servers?)

I have been searching for other users with similar problems and I found a lot of them, but noone seems to have a clue about why this could be happening: https://obsproject.com/forum/threads/av1-live-streaming-on-youtube-not-working-please-help.168513/

### PR DESCRIPTION
**Pull request by derrod**
### Description

Adds parsing of AV1 frame type to AV1 OBU parsing to set drop priority of keyframes correctly.

Somewhat janky but matches what we did in 722ca8447e3be1ad4cd10ba1e8c8dd41e341a20f and should be good enough™ for our use case.

### Motivation and Context

Should fix #10383

### How Has This Been Tested?

Verified priority now gets set.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by derrod** [comment]
Adjusted the priorities based on feedback from people that know more than me about AV1. Should hopefully be good enough to keep us running for a while :)

File: plugins/obs-outputs/rtmp-av1.c [hunk 1]
```diff
@@ -536,19 +544,47 @@ size_t obs_parse_av1_header(uint8_t **header, const uint8_t *data, size_t size)
 	return output.bytes.num;
 }
 
+static void compute_av1_keyframe_priority(const uint8_t *buf, bool *is_keyframe,
+					  int *priority)
+{
+	/* Skip if the packet already has a priority, e.g. assigned by the
```
Comment (RytoEX) [inline plugins/obs-outputs/rtmp-av1.c:550]:
```suggestion
	/* Skip if the packet already has a priority, e.g., assigned by the
```

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nit only, otherwise seems fine.

**Comment by norihiro** [comment]
The prefixes of the commit titles should be `obs-outputs` instead of `obs-output`.

File: plugins/obs-outputs/rtmp-av1.c [hunk 2]
```diff
@@ -564,15 +600,15 @@ static void serialize_av1_data(struct serializer *s, const uint8_t *data,
...
-			if (state == START_FOUND)
-				state = END_FOUND;
 			break;
+		case AV1_OBU_FRAME:
+		case AV1_OBU_FRAME_HEADER:
+			compute_av1_keyframe_priority(buf + start_pos,
+						      is_keyframe, priority);
+#ifdef __GNUC__
+			__attribute__((fallthrough));
+#endif
```
Comment (RytoEX) [inline plugins/obs-outputs/rtmp-av1.c:610]: It seems we normally use this instead:
```c
/* Falls through. */
```
or
```c
/* FALLTHROUGH */
```

**Review by RytoEX — CHANGES_REQUESTED** [review]

File: plugins/obs-outputs/rtmp-av1.c (hunk 2 above)
Comment (derrod) [reply plugins/obs-outputs/rtmp-av1.c:610]: If we ever get C23 we can do `[[fallthrough]]` but until then it's either a comment or this. I don't think it matters.

Comment (RytoEX) [reply plugins/obs-outputs/rtmp-av1.c:610]: It doesn't matter too much, I was just looking for consistency because I didn't want to have to try to find all the different variants we used along the way if/when we switch to C23.

**Review by RytoEX — APPROVED** [review]
Looks okay to me. User tests were promising.

**Review by Lain-B — APPROVED** [review]
