### PR TITLE
libobs: Prevent D3D11 projectors from tearing

### LINKED ISSUE #6936: Windows 11: Fullscreen projector has constant tearing for Dual PC streaming/recording but not the windowed projector
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

all versions after 27.1-rc3

### OBS Studio Log URL

https://obsproject.com/logs/7V0vLxx3JsUKH6tN

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Fullscreen projector should has not tearing and behave as the same as windowed projector in updated Windows 11.

### Current Behavior

My setup:
      Gaming PC: i7-9700k, RTX 3080, OBS 27.2.4, Windows 11 22622.450
      Streaming PC: i7-6820HK, GTX1070, OBS 27.2.4, Windows 10 19044.1806
      Capture card: Avermedia GC553 @ 1440p60hz

I mostly do streaming/recording with FPS games, e.g., Apex, COD, CSGO etc. And the mentioned setup works flawlessly when my gaming pc was Windows 10.

After my gaming rig was updated to Windows 11, I suddenly found constant screen tearing in my streaming/recording. And after some research, I found that the Fullscreen Projector is to blame. With windowed Projector, there is no tearing at all. 

Fullscreen projector:
full

Windowed screen projector:
windowed

### Steps to Reproduce

1.Setup Dual PC streaming with a capture card and download OBS after 27.1 rc2 with Windows 11.
2.Set capture card as extended monitor and use Fullscreen projector.
3.Play some FPS game and move the angle quickly.
4.Same 1-3 steps with windowed projector.
...

### Anything else we should know?

I find five temporary solutions but they all has some drawbacks:
1. Not using projector and clone my monitor to capture card, but some games' UI are broken;
2. Revert the OBS back to 27.1-rc2 (which has no implementation of D3D swap enhancements) to minimize the screen tearing; This one lead to stutter for my streaming/recording and not as smooth as the 27.2.4;
3. Use windowed projector, but I cannot get rid of the caption bar;
4. Use VSync on OBS with Nvidia control panel, but this one leads to severe rendering latency;
5. Use legacy OpenGL rendering, but again it's not smooth as D3D11.

Things I tried:
Tested lots of OBS version, with no 3rd plugins;
HAGS on/off;  Admin or not;  VRR on/off; "Optimization for windowed game" on/off; "Disable Fullscreen Optimizations" on/off
Switch between WGC/DXGI capture method
Change projector origin(source/scene/preview)
Upgrade gaming rig to Windows 11 Insider build; 
Upgrade firmware of capture card;
Change different Hz of capture card and fps settings of OBS;
Set OBS for a single CPU core;
Messing with FILP_DISCARD and ALLOW_TEARING in libobs-d3d11/d3d11-subsystem.cpp and compiled modified versions, turns out without ALLOW_TEARING has rendering latency problem;

My current two cents:
1. D3D swap chain enhancements are introduced by Microsoft to boost performance for rendering.
2. OBS Devs added these swap chain enhancements, but test cases didn't cover all situations.
3. These enhancements are not working exactly the same for Fullscreen borderless window in Windows 11 and Windows 10, or Microsoft broke somethings in Windows 11 (The FILP_DISCARD and ALLOW_TEARING combo works under Windows 10 in my case).
4. Maybe it's related to how the projector's window created/rendered since Fullscreen borderless has tearing while windowed not.
5. In rare cases, the Fullscreen projector can work flawless without tearing, but it's not stable and the tearing may occur during the streaming/recording. Maybe something happened and cause the rendering of Fullscreen borderless window out-of-sync?

Possible related pulls:
[D3D swap chain enhancements #2064](https://github.com/obsproject/obs-studio/pull/2064)
[Fix Windows 11 responsiveness using FLIP_DISCARD #5265](https://github.com/obsproject/obs-studio/pull/5265)
[libobs-d3d11: Use ALLOW_TEARING if supported #5266](https://github.com/obsproject/obs-studio/pull/5266)

Possible related posts: (There are lots of them I just list some)
[Preview screen tearing](https://obsproject.com/forum/threads/preview-screen-tearing-issue-from-obs-studio-27-1-rc3-and-onward-not-present-in-rc2-and-earlier.153499/)
[Constant screen tearing](https://www.reddit.com/r/elgato/comments/u6s55z/any_luck_with_dual_pc_streaming_without_screen/)
[Dual pc screen tearing](https://www.reddit.com/r/Twitch/comments/s32fxi/dual_pc_screen_tearing_issue/)

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Some users stream projectors, so don't let them tear. Use the waitable
object to check the flip queue, and only flip if there's space.

Fixes #6936

### Motivation and Context
Want to both have tear-free flip, and avoid stalling the graphics thread.

### How Has This Been Tested?
Used temporary instrumentation to both verify flip/no-flip repeating pattern for 120 Hz video on 60 Hz monitor, and that Present calls normally last 50-60 µs in the new setup.

### Types of changes
- Tweak (non-breaking change to improve existing functionality)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: libobs-d3d11/d3d11-subsystem.cpp [hunk 1]
```diff
@@ -298,12 +288,9 @@ gs_swap_chain::gs_swap_chain(gs_device *device, const gs_init_data *data)
 	if (flags & DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT) {
 		ComPtr<IDXGISwapChain2> swap2 = ComQIPtr<IDXGISwapChain2>(swap);
 		hWaitable = swap2->GetFrameLatencyWaitableObject();
-		if (hWaitable) {
-			hr = swap2->SetMaximumFrameLatency(40);
-			if (FAILED(hr))
-				throw HRError("Could not relax frame latency",
-					      hr);
-		}
+		if (FAILED(hr))
```
Comment (norihiro) [inline libobs-d3d11/d3d11-subsystem.cpp:291]: Is this intentional to check `hr`, not `hWaitable`?

Comment (jpark37) [reply libobs-d3d11/d3d11-subsystem.cpp:291]: It is not. Thanks.

**Comment by jpark37** [comment]
Actually, I want to test for present readiness earlier to avoid scribbling into the swap buffer unnecessarily. Will probably add something like `bool gs_is_present_ready()` that returns true for other renderers.
