### PR TITLE
graphics-hook: Fix crash with Vulkan DirectDisplay

### LINKED ISSUE #11581: Crash in graphics-hook64.dll on call to vkCreateSwapchainKHR when using Vulkan Direct Display
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

30.2.3

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/83BBFOiQVhsO906Y

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

This isn't a crash in OBS Studio itself, rather the graphics-hook64.dll causing other applications to crash. OBS doesn't need to be running, just installed. Direct Display is a new Vulkan feature that allows an app to directly output to a monitor without interacting with the Windows desktop. I would not expect graphics-hook64.dll to cause other applications to crash, especially when OBS isn't even active.

### Current Behavior

If OBS is installed on the machine, trying to use this feature crashes due to a bug in graphics-hook64.dll. Likely not handling this new extension properly.

### Steps to Reproduce

1. You need Windows 11 Pro for Workstations or Windows 11 Enterprise to reproduce this. This is because the feature to 'remove a monitor from the desktop' is locked behind those versions.
2. Uninstall OBS, just so we can see the Direct Display working first.
3. Download and build Nvidia' sample project for Direct Display: https://github.com/nvpro-samples/vk_ddisplay
4. You can ignore the sections about mosaic and the config files. Just download the https://www.nvidia.com/en-us/drivers/ddisplay-utility/ and open an admin cmd prompt use: 
5. `configureDdisplay.exe status` to see the displays on the machine
6. `configureDdisplay.exe remove-from-desktop -i 1`, for example, to remove monitor index 1 from the desktop.
7. Run the sample. You should see hairy torus object rotating on the monitor that isn't part of your Windows desktop anymore.
8. Shut down and install OBS, then try running again. It should crash.

Thanks for looking into this.

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by mbechard**
Vulkan Direct Display uses extensions:
VK_KHR_display/VK_EXT_direct_mode_display
This workflow allows creating swapchains that arn't active on the desktop, so they don't have HWNDs.
Avoid trying to create swap_data when a HWND can't be found.

Fixes #11581

### Description
VK_KHR_display/VK_EXT_direct_mode_display extensions created swapchains without HWND handles.
Avoid trying to work with HWND when they can't be found.

### Motivation and Context
The old behavior causes crashes when applications using Direct Display.

### How Has This Been Tested?
The only thing I tested was that the crash doesn't occur. If avoiding filling the `swap_data` has
greater ramifications, then I'll need feedback from devs more familiar with OBS.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by jjulianoatnv** [comment]
This change makes sense. Not every VkSurfaceKHR/VkSwapchainKHR is associated with an hwnd. Assuming there is an associated hwnd results in undefined behavior (possibly application crash.) 

The only caller of `add_surf_data()` is `OBS_CreateWin32SurfaceKHR()`. When a VkSurfaceKHR is created using a Vulkan command other than VkCreateWin32SurfaceKHR, then `add_surf_data` is not called for that surface.  `vkCreateDisplayPlaneSurfaceKHR()` is one example of an alternate way to create a surface. There might be additional ways to create a surface.

The proposed change adds defense against both of the following fallacies:
- It is a flaw to assume that all methods of creating a surface are wrapped by the win-capture plugin.
- It is a flaw to assume that all methods of creating a surface associate the surface with an hwnd.

**Review by Lain-B — APPROVED** [review]

**Comment by mbechard** [comment]
What's next to get this merged in?

File: plugins/win-capture/graphics-hook/vulkan-capture.c [hunk 1]
```diff
@@ -509,7 +509,9 @@ static void add_surf_data(struct vk_inst_data *idata, VkSurfaceKHR surf, HWND hw
 static HWND find_surf_hwnd(struct vk_inst_data *idata, VkSurfaceKHR surf)
 {
 	struct vk_surf_data *surf_data = (struct vk_surf_data *)get_obj_data(&idata->surfaces, (uint64_t)surf);
-	return surf_data->hwnd;
+	if (surf_data)
+		return surf_data->hwnd;
+	return 0;
```
Comment (RytoEX) [inline plugins/win-capture/graphics-hook/vulkan-capture.c:514]: In hindsight, I would have preferred a blank line here to separate it from the `if` contents above.

**Review by RytoEX — COMMENTED** [review]
Something I missed before merge.

**Comment by RytoEX** [comment]
We will probably have to increment the graphics-hook version before the next release.
