### PR TITLE
libobs: Use autoreleasepool for graphics thread

### LINKED ISSUE #2293: macOS 10.15.1 GL context creation refcount overflow
## Expected Behavior
I should be able to leave my computer stream indefinitely without a crash.

## Current Behavior
After about 4-5 days of continuous streaming, it crashes in `-[NSOpenGLContext makeCurrentContext]` with the following message: `Refcount overflow in NSResponder or subclass. Too many unbalanced -retains!`.

Sounds like a missing `release` call somewhere.

## Steps to Reproduce
1. Start streaming and leave it on for a few days. Last two crashes were at a 3 day interval.

## Additional information

I'm running a Hackintosh with a Radeon RX 580. The computer is set to not go to sleep, but the displays are going to sleep.

Here's a crashlog:

```
Process:               obs [92736]
Path:                  /Applications/OBS.app/Contents/MacOS/obs
Identifier:            com.obsproject.obs-studio
Version:               24.0.6 (24.0.6)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           obs [92736]
User ID:               501

Date/Time:             2019-12-29 03:54:39.949 +0200
OS Version:            Mac OS X 10.15.1 (19B88)
Report Version:        12
Anonymous UUID:        7AC5143E-30C5-5709-608E-1A0AA98F8004

Sleep/Wake UUID:       7F4DABAF-E533-4668-B3C1-CAB2D8A25496

Time Awake Since Boot: 2000000 seconds
Time Since Wake:       2000000 seconds

System Integrity Protection: disabled

Crashed Thread:        3  libobs: graphics thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [92736]

Application Specific Information:
Refcount overflow in NSResponder or subclass. Too many unbalanced -retains!

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff70f51166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff70f516cc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3992f36b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff3992e907 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff3992dfe3 CFRunLoopRunSpecific + 499
5   com.apple.HIToolbox           	0x00007fff384b567d RunCurrentEventLoopInMode + 292
6   com.apple.HIToolbox           	0x00007fff384b53bd ReceiveNextEventCommon + 600
7   com.apple.HIToolbox           	0x00007fff384b5147 _BlockUntilNextEventMatchingListInModeWithFilter + 64
8   com.apple.AppKit              	0x00007fff36b3a864 _DPSNextEvent + 990
9   com.apple.AppKit              	0x00007fff36b395d4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1352
10  com.apple.AppKit              	0x00007fff36b33d76 -[NSApplication run] + 658
11  libqcocoa.dylib               	0x00000000077fb8dd 0x77d2000 + 170205
12  org.qt-project.QtCore         	0x0000000108b9f2be QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 398
13  org.qt-project.QtCore         	0x0000000108ba3e91 QCoreApplication::exec() + 369
14  com.obsproject.obs-studio     	0x0000000105baa570 main + 5248
15  libdyld.dylib                 	0x00007fff70e082e5 start + 1

Thread 1:: audio-io: audio thread
0   libsystem_kernel.dylib        	0x00007fff70f55032 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff70ed80fa nanosleep + 196
2   libsystem_c.dylib             	0x00007fff70ed7ff4 usleep + 53
3   libobs.0.dylib                	0x000000010839491c audio_thread + 460
4   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
5   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 2:: video-io: video thread
0   libsystem_kernel.dylib        	0x00007fff70f511a2 semaphore_wait_trap + 10
1   libobs.0.dylib                	0x00000001083a8ad0 os_sem_wait + 16
2   libobs.0.dylib                	0x0000000108393345 video_thread + 885
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 3 Crashed:: libobs: graphics thread
0   com.apple.AppKit              	0x00007fff3722d20a -[NSResponder _tryRetain] + 92
1   libobjc.A.dylib               	0x00007fff6fa9fe1d objc_loadWeakRetained + 351
2   libobjc.A.dylib               	0x00007fff6faa1adc objc_loadWeak + 15
3   com.apple.AppKit              	0x00007fff36e9b494 -[NSOpenGLContext makeCurrentContext] + 271
4   libobs.0.dylib                	0x0000000108384d20 gs_enter_context + 112
5   libobs.0.dylib                	0x00000001083f6bcf obs_graphics_thread + 1855
6   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
7   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff70f511a2 semaphore_wait_trap + 10
1   libobs.0.dylib                	0x00000001083a8ad0 os_sem_wait + 16
2   libobs-scripting.dylib        	0x000000000b4cfae9 defer_thread + 25
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 5:: AMCP Logging Spool
0   libsystem_kernel.dylib        	0x00007fff70f511a2 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff6d007ec6 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff6d003442 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff6d006a14 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff6d006b64 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff70f511a2 semaphore_wait_trap + 10
1   com.apple.audio.caulk         	0x00007fff6d007ec6 caulk::mach::semaphore::wait() + 16
2   com.apple.audio.caulk         	0x00007fff6d003442 caulk::semaphore::timed_wait(double) + 106
3   com.apple.audio.caulk         	0x00007fff6d006a14 caulk::concurrent::details::worker_thread::run() + 30
4   com.apple.audio.caulk         	0x00007fff6d006b64 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*> > >(void*) + 45
5   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 7:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	0x00007fff70f51166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff70f516cc mach_msg + 60
2   com.apple.audio.CoreAudio     	0x00007fff3908b0c3 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 111
3   com.apple.audio.CoreAudio     	0x00007fff38f85462 invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 2677
4   com.apple.audio.CoreAudio     	0x00007fff390bb61c HALB_IOThread::Entry(void*) + 72
5   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 8:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libvlc.5.dylib                	0x000000001488196b 0x14873000 + 59755

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015072 _pthread_cond_wait + 751
2   libvlccore.9.dylib            	0x000000001480586a vlc_cond_timedwait + 170
3   ???                           	0x000020a000000000 0 + 35871566856192

Thread 10:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff70f51166 mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff70f516cc mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff3992f36b __CFRunLoopServiceMachPort + 322
3   com.apple.CoreFoundation      	0x00007fff3992e907 __CFRunLoopRun + 1695
4   com.apple.CoreFoundation      	0x00007fff3992dfe3 CFRunLoopRunSpecific + 499
5   com.apple.AppKit              	0x00007fff36b41dba _NSEventThread + 132
6   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
7   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 12:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 13:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 14:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 15:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 16:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 17:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 18:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 19:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 20:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 21:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 22:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 23:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 24:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 25:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 26:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 27:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 28:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 29:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 30:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 31:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 32:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 33:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x000000001440082b threadpool_thread_internal + 123
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 34:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libx264.155.dylib             	0x00000000144001ed lookahead_thread_internal + 205

Thread 35:: rtmp-stream: send_thread
0   libsystem_kernel.dylib        	0x00007fff70f511a2 semaphore_wait_trap + 10
1   libobs.0.dylib                	0x00000001083a8ad0 os_sem_wait + 16
2   obs-outputs.so                	0x0000000014241588 send_thread + 1560
3   libsystem_pthread.dylib       	0x00007fff71014d36 _pthread_start + 125
4   libsystem_pthread.dylib       	0x00007fff7101158f thread_start + 15

Thread 36:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015072 _pthread_cond_wait + 751
2   libvlccore.9.dylib            	0x000000001480586a vlc_cond_timedwait + 170

Thread 37:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libvlccore.9.dylib            	0x00000000147f6185 picture_pool_Wait + 85

Thread 38:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libavcodec_plugin.dylib       	0x0000000017fd5a8d 0x177e0000 + 8346253
3   ???                           	0x000020a000000000 0 + 35871566856192

Thread 39:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libavcodec_plugin.dylib       	0x0000000017fd5a8d 0x177e0000 + 8346253
3   ???                           	0x000020a000000000 0 + 35871566856192

Thread 40:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libavcodec_plugin.dylib       	0x0000000017fd5a8d 0x177e0000 + 8346253
3   ???                           	0x000020a000000000 0 + 35871566856192

Thread 41:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libavcodec_plugin.dylib       	0x0000000017fd5a8d 0x177e0000 + 8346253
3   ???                           	0x000020a000000000 0 + 35871566856192

Thread 42:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libavcodec_plugin.dylib       	0x0000000017fd5a8d 0x177e0000 + 8346253
3   ???                           	0x000020a000000000 0 + 35871566856192

Thread 43:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701
2   libavcodec_plugin.dylib       	0x0000000017fd48cb 0x177e0000 + 8341707
3   ???                           	0x0000700003bce000 0 + 123145365020672
4   ???                           	0x00007fcfe7778000 0 + 140530918326272

Thread 44:
0   libsystem_kernel.dylib        	0x00007fff70f54916 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff71015040 _pthread_cond_wait + 701

Thread 45:
0   libsystem_pthread.dylib       	0x00007fff7101156c start_wqthread + 0

Thread 3 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000000793c3e0  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x000000001f08000c  rbp: 0x0000700004277d40  rsp: 0x0000700004277d30
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x00007fff7ae0418a  r13: 0x00007fcff7137d50  r14: 0x00007fff9ace8b40  r15: 0x00007fff9ace8080
  rip: 0x00007fff3722d20a  rfl: 0x0000000000010206  cr2: 0x00007fff9ae460a0
  
Logical CPU:     6
Error Code:      0x00000000
Trap Number:     6


Binary Images:
         0x77d2000 -          0x7928ff7 +libqcocoa.dylib (0) <ACAA48D6-9282-35B1-BEC9-2490BAD54923> /Applications/OBS.app/Contents/Plugins/platforms/libqcocoa.dylib
         0x796e000 -          0x7999ffb +org.qt-project.QtPrintSupport (5.10 - 5.10.1) <7D87076B-A68E-3956-83EA-7F0E06AAD0D6> /Applications/OBS.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
         0x9d30000 -          0x9d57ffb +libqmacstyle.dylib (0) <010481BF-26A1-3244-8A54-7D4F47408872> /Applications/OBS.app/Contents/Plugins/styles/libqmacstyle.dylib
         0x9f7f000 -          0x9f85fff +libqgif.dylib (0) <4BF8C3B6-EF03-3D11-BEB2-ADCBC927E37C> /Applications/OBS.app/Contents/Plugins/imageformats/libqgif.dylib
         0x9f89000 -          0x9f90ffb +libqicns.dylib (0) <0AF4D919-D97B-3B83-99D0-B684E491CA8E> /Applications/OBS.app/Contents/Plugins/imageformats/libqicns.dylib
         0x9f95000 -          0x9f9affb +libqico.dylib (0) <7414AC74-5772-37EC-93D6-BF9CF2649B53> /Applications/OBS.app/Contents/Plugins/imageformats/libqico.dylib
         0x9f9f000 -          0x9feffff +libqjpeg.dylib (0) <5A690EEE-BB83-3BC5-889A-C18E59629679> /Applications/OBS.app/Contents/Plugins/imageformats/libqjpeg.dylib
         0x9ff5000 -          0x9ff9ff7 +libqmacjp2.dylib (0) <61CB4DD0-2F23-30E9-8B06-A7798D6606E6> /Applications/OBS.app/Contents/Plugins/imageformats/libqmacjp2.dylib
         0x9ffd000 -          0xa001fff +libqsvg.dylib (0) <E3301BB1-6F7E-31A2-9F67-D61EAC3D1A46> /Applications/OBS.app/Contents/Plugins/imageformats/libqsvg.dylib
         0xa005000 -          0xa009ff7 +libqtga.dylib (0) <A6B6EBBA-79C9-38BB-B969-F9B6111BD265> /Applications/OBS.app/Contents/Plugins/imageformats/libqtga.dylib
         0xa00d000 -          0xa06fffb +libqtiff.dylib (0) <13C36608-3757-3DCA-94EC-089C2A2D4637> /Applications/OBS.app/Contents/Plugins/imageformats/libqtiff.dylib
         0xa077000 -          0xa07bff7 +libqwbmp.dylib (0) <3E7C99A6-6FA9-3E5C-BB71-B26986D7B92B> /Applications/OBS.app/Contents/Plugins/imageformats/libqwbmp.dylib
         0xa07f000 -          0xa10cff7 +libqwebp.dylib (0) <D72A5496-4BCF-3991-AC38-BB0985E61E80> /Applications/OBS.app/Contents/Plugins/imageformats/libqwebp.dylib
         0xa1e7000 -          0xa1ea047  libobjc-trampolines.dylib (781) <6CF41A53-C75E-3AAA-9E47-E35C1EE56CE4> /usr/lib/libobjc-trampolines.dylib
         0xa281000 -          0xa293fff  com.apple.iokit.IOHIDLib (2.0.0 - 2.0.0) <0CBAD74B-19D4-3410-95CB-445D773F8A28> /System/Library/Extensions/IOHIDFamily.kext/Contents/PlugIns/IOHIDLib.plugin/Contents/MacOS/IOHIDLib
         0xa307000 -          0xa30effb +libqsvgicon.dylib (0) <6950EDE5-067C-3E8D-B9D6-102B8A685563> /Applications/OBS.app/Contents/Plugins/iconengines/libqsvgicon.dylib
         0xa313000 -          0xa327ffb +libobs-opengl.so (0) <34950D0F-A9AD-3AFC-A720-9EBE9E78C42A> /Applications/OBS.app/Contents/Frameworks/libobs-opengl.so
         0xa338000 -          0xa37bfff +libobsglad.0.dylib (0) <4378B528-9524-3D28-B67B-85AD315AFB6A> /Applications/OBS.app/Contents/MacOS/libobsglad.0.dylib
         0xa3d3000 -          0xa49bfff  com.apple.AMDRadeonX4000GLDriver (3.2.24 - 3.0.2) <52F3B7A4-3234-3EF8-81D0-50228066C8CA> /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
         0xa568000 -          0xa570ff7 +coreaudio-encoder.so (0) <EF06D1BF-B681-363D-9200-12FC9B891105> /Applications/OBS.app/Contents/Plugins/coreaudio-encoder.so
         0xa576000 -          0xa577fff +linux-jack.so (0) <1E2074D1-CE6E-3BDB-AA8F-89CD63C47413> /Applications/OBS.app/Contents/Plugins/linux-jack.so
         0xa5bc000 -          0xa5cafff +libavi_plugin.dylib (???) <D5DEECBD-D8E7-3A89-920E-0A415BB444DE> /Applications/VLC.app/Contents/MacOS/plugins/libavi_plugin.dylib
         0xb415000 -          0xb42dff7 +decklink-ouput-ui.so (0) <EE5F262C-0264-3672-AE12-54C5C85DF821> /Applications/OBS.app/Contents/Plugins/decklink-ouput-ui.so
         0xb451000 -          0xb48afff +frontend-tools.so (0) <994FBF0C-2412-37DB-8742-E51D3EADB6CA> /Applications/OBS.app/Contents/Plugins/frontend-tools.so
         0xb4cd000 -          0xb4e2fff +libobs-scripting.dylib (0) <9B61D7CB-7F78-3B3F-891D-1DE31F042E61> /Applications/OBS.app/Contents/Frameworks/libobs-scripting.dylib
         0xb4f9000 -          0xb56fff7 +libluajit-5.1.2.dylib (0) <A3EBD56C-67CF-3F8D-B5CE-D72C4840C14C> /Applications/OBS.app/Contents/Frameworks/libluajit-5.1.2.dylib
         0xb57c000 -          0xb57fffb +image-source.so (0) <67B45EBD-C0D8-3BB8-AF16-1ABA3B825755> /Applications/OBS.app/Contents/Plugins/image-source.so
         0xb585000 -          0xb591ff7 +libjack.0.dylib (0) <A1A1EA98-6D5E-3D93-A2DE-17971F2F88DF> /Applications/OBS.app/Contents/Frameworks/libjack.0.dylib
         0xb5a7000 -          0xb6f3ff3 +libdb-18.1.dylib (0) <DE2FF0B3-38A4-398F-9E0F-74879A40EB83> /Applications/OBS.app/Contents/Frameworks/libdb-18.1.dylib
         0xb728000 -          0xb776fff +libssl.1.1.dylib (0) <F1F30C49-D786-3C38-AEB7-0C172C443354> /Applications/OBS.app/Contents/Frameworks/libssl.1.1.dylib
         0xb7a5000 -          0xb9415ab +libcrypto.1.1.dylib (0) <E93BE894-9E2C-3175-8E04-9AE924C63760> /Applications/OBS.app/Contents/Frameworks/libcrypto.1.1.dylib
         0xb9dc000 -          0xb9ecff7 +mac-avcapture.so (0) <1E341EE7-32A1-3FCC-93F4-786C3916955F> /Applications/OBS.app/Contents/Plugins/mac-avcapture.so
         0xb9f6000 -          0xba1aff7  com.apple.cmio.DAL.iOSScreenCapture (1000.0 - 5125.3) <A68FF487-63F6-392F-A009-BCB05C3BF458> /System/Library/Frameworks/CoreMediaIO.framework/Resources/iOSScreenCapture.plugin/Contents/MacOS/iOSScreenCapture
         0xba2c000 -          0xba35ffb +mac-capture.so (0) <A3E86DB9-2BA7-3357-95EB-9FCB748AB764> /Applications/OBS.app/Contents/Plugins/mac-capture.so
         0xba3d000 -          0xba48fff +mac-decklink.so (0) <5F7A822D-3E50-3BE0-A7CF-E6891697CDFB> /Applications/OBS.app/Contents/Plugins/mac-decklink.so
         0xba5a000 -          0xba6fff7 +mac-syphon.so (0) <DF689134-8076-38CA-B2B0-422105FE9266> /Applications/OBS.app/Contents/Plugins/mac-syphon.so
         0xba8b000 -          0xba90fff +mac-vth264.so (0) <096F1D70-4D20-3AE9-A810-338BF65C5B2B> /Applications/OBS.app/Contents/Plugins/mac-vth264.so
         0xbb20000 -          0xbb89ff7 +obs-browser.so (0) <EBCEC6A7-CC70-3143-9AEA-754DA4D77B23> /Applications/OBS.app/Contents/Plugins/obs-browser.so
         0xbc13000 -         0x13304f7f +org.chromium.ContentShell.framework (75.1.16.0 - 16.0) <7599C8E5-3EE0-3B46-AC5F-3583974DCD43> /Applications/OBS.app/Contents/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework
        0x13d88000 -         0x13d97ff7 +obs-ffmpeg.so (0) <66B7022B-F053-3E64-A851-3651A58F1A38> /Applications/OBS.app/Contents/Plugins/obs-ffmpeg.so
        0x13da2000 -         0x13f92fef +libavfilter.7.dylib (0) <76B1D2D0-B1F1-3846-9A2B-18AF12B2F710> /Applications/OBS.app/Contents/Frameworks/libavfilter.7.dylib
        0x1408d000 -         0x14094fff +libavdevice.58.dylib (0) <B63150B4-22BA-3ADF-B23F-4E251C140D01> /Applications/OBS.app/Contents/Frameworks/libavdevice.58.dylib
        0x140a1000 -         0x140c1fff +libpostproc.55.dylib (0) <C7B00896-1F15-3C2F-9049-D28EB789026F> /Applications/OBS.app/Contents/Frameworks/libpostproc.55.dylib
        0x140ca000 -         0x140d7ff7 +obs-filters.so (0) <DF8E988A-9097-3B1B-8434-739087AEB26C> /Applications/OBS.app/Contents/Plugins/obs-filters.so
        0x140e4000 -         0x140f0fff +libspeexdsp.1.dylib (0) <33B5247E-583B-3820-813E-3D60DA56B08A> /Applications/OBS.app/Contents/Frameworks/libspeexdsp.1.dylib
        0x140f9000 -         0x140fcff3 +obs-libfdk.so (0) <52EB9145-DE67-3517-B000-520C400BC139> /Applications/OBS.app/Contents/Plugins/obs-libfdk.so
        0x14100000 -         0x14202ff7 +libfdk-aac.2.dylib (0) <5269FAFD-E2CC-3110-98FF-470AA2FC8E66> /Applications/OBS.app/Contents/Frameworks/libfdk-aac.2.dylib
        0x14232000 -         0x14261ffb +obs-outputs.so (0) <8BBE58B1-89BD-3537-A14A-F1DD4F8E83DF> /Applications/OBS.app/Contents/Plugins/obs-outputs.so
        0x14277000 -         0x14295ff7 +libmbedtls.12.dylib (0) <4547728C-5E79-3191-BF40-F44A80D0D836> /Applications/OBS.app/Contents/Frameworks/libmbedtls.12.dylib
        0x142a4000 -         0x142eaffb +libmbedcrypto.3.dylib (0) <4D022613-5EE5-3356-B52C-40B14513B24C> /Applications/OBS.app/Contents/Frameworks/libmbedcrypto.3.dylib
        0x14303000 -         0x14319ff7 +libmbedx509.0.dylib (0) <F383742C-027C-3858-AA32-60C6DF7F9830> /Applications/OBS.app/Contents/Frameworks/libmbedx509.0.dylib
        0x14325000 -         0x14329fff +obs-transitions.so (0) <B027DAFF-82FD-3E2F-97FE-783ADA41754C> /Applications/OBS.app/Contents/Plugins/obs-transitions.so
        0x14330000 -         0x14339fff +obs-vst.so (0) <672DFED6-577C-3442-9367-26B2EAFAA9BC> /Applications/OBS.app/Contents/Plugins/obs-vst.so
        0x14343000 -         0x14347ff3 +obs-x264.so (0) <4124C059-6F80-36E5-B10D-BF34E2E9C274> /Applications/OBS.app/Contents/Plugins/obs-x264.so
        0x1434b000 -         0x1454efc7 +libx264.155.dylib (0) <9655BF5C-5F45-3A06-9EEA-D7C87D3E5601> /Applications/OBS.app/Contents/Frameworks/libx264.155.dylib
        0x14688000 -         0x14692ff3 +rtmp-services.so (0) <38264A87-5DB9-393A-831E-262353986EB5> /Applications/OBS.app/Contents/Plugins/rtmp-services.so
        0x1469d000 -         0x146a4ffb +text-freetype2.so (0) <01036092-1C90-32DD-B4EC-6DE69219BAEC> /Applications/OBS.app/Contents/Plugins/text-freetype2.so
        0x146aa000 -         0x14726ffb +libfreetype.6.dylib (0) <36C84A2F-9F4B-3626-986D-55146AD52E48> /Applications/OBS.app/Contents/Frameworks/libfreetype.6.dylib
        0x14745000 -         0x14767fff +libpng16.16.dylib (0) <211A7B4C-219C-3929-A2CF-D796E3A5F40A> /Applications/OBS.app/Contents/Frameworks/libpng16.16.dylib
        0x14775000 -         0x14779ff7 +vlc-video.so (0) <DDDFC168-1C48-324C-940C-830F14CF3EBA> /Applications/OBS.app/Contents/Plugins/vlc-video.so
        0x1477f000 -         0x14854fff +libvlccore.9.dylib (10) <6E1BEB4D-89EC-3A05-88BE-3C16778B8FD7> /Applications/VLC.app/Contents/MacOS/lib/libvlccore.9.dylib
        0x14873000 -         0x1488bfff +libvlc.5.dylib (12) <D32DE850-8AF9-3BC0-A7A9-93B221B148E5> /Applications/VLC.app/Contents/MacOS/lib/libvlc.5.dylib
        0x1489a000 -         0x14e35fe7  com.apple.audio.codecs.Components (7.0 - 7.0) <265F7F29-2313-3CE0-B5F2-8D54E8C71664> /System/Library/Components/AudioCodecs.component/Contents/MacOS/AudioCodecs
        0x14f4d000 -         0x14f51fff  com.apple.audio.AppleHDAHALPlugIn (283.14 - 283.14) <D5B2752C-3598-3870-8BEB-F91597AE8D64> /System/Library/Extensions/AppleHDA.kext/Contents/PlugIns/AppleHDAHALPlugIn.bundle/Contents/MacOS/AppleHDAHALPlugIn
        0x14f5a000 -         0x14f5efff  com.apple.audio.AppleGFXHDAHALPlugIn (100.1.422 - 100.1.422) <68649BFE-8C33-3379-A9F0-B8EB36AFE44D> /System/Library/Extensions/AppleGFXHDA.kext/Contents/PlugIns/AppleGFXHDAHALPlugIn.bundle/Contents/MacOS/AppleGFXHDAHALPlugIn
        0x14f67000 -         0x150c3fff  com.apple.audio.units.Components (1.14 - 1.14) <A5AC33CF-21E6-38FB-9A8B-48CD77AA336C> /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
        0x151b6000 -         0x152f3ff7 +libmacosx_plugin.dylib (???) <744C56D3-0FB0-3AAD-AB97-D6E9D8DCA931> /Applications/VLC.app/Contents/MacOS/plugins/libmacosx_plugin.dylib
        0x15357000 -         0x15358ff7 +libsyslog_plugin.dylib (???) <2E445021-938B-3114-8230-E3A77653B943> /Applications/VLC.app/Contents/MacOS/plugins/libsyslog_plugin.dylib
        0x1535f000 -         0x15361ff7 +libfile_logger_plugin.dylib (???) <D7AB72A0-567E-39B5-BAB6-1294A13EC528> /Applications/VLC.app/Contents/MacOS/plugins/libfile_logger_plugin.dylib
        0x15369000 -         0x1536aff7 +libconsole_logger_plugin.dylib (???) <D488CA25-1CCE-3D84-9755-5BB7F26CA9B7> /Applications/VLC.app/Contents/MacOS/plugins/libconsole_logger_plugin.dylib
        0x15371000 -         0x15373fff +libmemory_keystore_plugin.dylib (???) <35F4F690-F4DE-33C1-BF7F-F179B2A2C7F6> /Applications/VLC.app/Contents/MacOS/plugins/libmemory_keystore_plugin.dylib
        0x1537b000 -         0x15385fff +libauhal_plugin.dylib (???) <E1BCAD5F-D7A3-331A-8002-9F9F3078E250> /Applications/VLC.app/Contents/MacOS/plugins/libauhal_plugin.dylib
        0x1538e000 -         0x15391fff +libvdr_plugin.dylib (???) <D92DE345-9A55-3BAC-A3F7-D89C4097D81B> /Applications/VLC.app/Contents/MacOS/plugins/libvdr_plugin.dylib
        0x15399000 -         0x1539bfff +libfilesystem_plugin.dylib (???) <117BD9CD-8F96-31D7-9439-5915EC0321B1> /Applications/VLC.app/Contents/MacOS/plugins/libfilesystem_plugin.dylib
        0x153a3000 -         0x153a5ff7 +libprefetch_plugin.dylib (???) <9BAE08DF-544D-3123-8F9A-A6EFF70BB791> /Applications/VLC.app/Contents/MacOS/plugins/libprefetch_plugin.dylib
        0x153ad000 -         0x153afff7 +libcache_read_plugin.dylib (???) <B81E23DA-1657-327F-8C58-4E27536A4C2D> /Applications/VLC.app/Contents/MacOS/plugins/libcache_read_plugin.dylib
        0x153b6000 -         0x153b7fff +libadf_plugin.dylib (???) <E329A98A-D467-3003-A96E-56501D957192> /Applications/VLC.app/Contents/MacOS/plugins/libadf_plugin.dylib
        0x153be000 -         0x155d7ff7 +liblibbluray_plugin.dylib (???) <FF0FD344-512A-3E53-8763-29E5E1510D01> /Applications/VLC.app/Contents/MacOS/plugins/liblibbluray_plugin.dylib
        0x155fb000 -         0x1562cfff +libdvdnav_plugin.dylib (???) <6AC9E155-D402-34FD-9C57-BC943C379713> /Applications/VLC.app/Contents/MacOS/plugins/libdvdnav_plugin.dylib
        0x16237000 -         0x16241ff7 +libinflate_plugin.dylib (???) <373E616B-C5BA-32BA-8A4D-F17C92341D1A> /Applications/VLC.app/Contents/MacOS/plugins/libinflate_plugin.dylib
        0x16249000 -         0x1624afff +libskiptags_plugin.dylib (???) <40E26A3C-04E1-366F-A9EC-D10559AA8804> /Applications/VLC.app/Contents/MacOS/plugins/libskiptags_plugin.dylib
        0x16251000 -         0x16256ff7 +libhds_plugin.dylib (???) <61625A8C-BAA3-3AC1-8FE6-BC3DB04A3D57> /Applications/VLC.app/Contents/MacOS/plugins/libhds_plugin.dylib
        0x1625e000 -         0x16260fff +libdecomp_plugin.dylib (???) <A83410AE-1A6D-3C3A-8F39-2777122EDC26> /Applications/VLC.app/Contents/MacOS/plugins/libdecomp_plugin.dylib
        0x16268000 -         0x1627aff7 +libplaylist_plugin.dylib (???) <A68BBBC4-E1E7-3A09-8C59-57BDDDECE7CF> /Applications/VLC.app/Contents/MacOS/plugins/libplaylist_plugin.dylib
        0x16283000 -         0x162ceff7 +liblua_plugin.dylib (???) <28E1D1D5-ADDC-3B55-9F80-C435D9BD5E01> /Applications/VLC.app/Contents/MacOS/plugins/liblua_plugin.dylib
        0x162dd000 -         0x16342fff +libarchive_plugin.dylib (???) <2CAD94F4-8B7F-30C9-9BAC-EC6237C9C6C0> /Applications/VLC.app/Contents/MacOS/plugins/libarchive_plugin.dylib
        0x1634d000 -         0x1634eff7 +librecord_plugin.dylib (???) <DE7C8927-2971-339F-BE51-E5824E3BC42C> /Applications/VLC.app/Contents/MacOS/plugins/librecord_plugin.dylib
        0x16356000 -         0x16384fff +libmp4_plugin.dylib (???) <64169CD5-BD1E-32DC-97D2-92E2E11EB08D> /Applications/VLC.app/Contents/MacOS/plugins/libmp4_plugin.dylib
        0x16774000 -         0x1677ffff +libasf_plugin.dylib (???) <FAE6BA2F-274C-34D7-818E-B180639E7BAA> /Applications/VLC.app/Contents/MacOS/plugins/libasf_plugin.dylib
        0x16787000 -         0x1678cff7 +libes_plugin.dylib (???) <7891BFDB-0DDE-3217-B00C-DF04D96ADBE0> /Applications/VLC.app/Contents/MacOS/plugins/libes_plugin.dylib
        0x16794000 -         0x1679aff7 +libflacsys_plugin.dylib (???) <A11202D9-A16F-323A-8D40-62BA14420059> /Applications/VLC.app/Contents/MacOS/plugins/libflacsys_plugin.dylib
        0x167a2000 -         0x167a5ff7 +libnuv_plugin.dylib (???) <DA19791C-3AEB-38FE-9CD9-991ED86B3A23> /Applications/VLC.app/Contents/MacOS/plugins/libnuv_plugin.dylib
        0x16da1000 -         0x16da3fff +libtta_plugin.dylib (???) <BD53F67A-AF7C-3504-9C76-0616F127A6DB> /Applications/VLC.app/Contents/MacOS/plugins/libtta_plugin.dylib
        0x16dab000 -         0x16dbbff7 +libmpc_plugin.dylib (???) <435EE7B8-04E8-3643-905B-7758E23366F9> /Applications/VLC.app/Contents/MacOS/plugins/libmpc_plugin.dylib
        0x16dc4000 -         0x16dc7fff +libwav_plugin.dylib (???) <6D4AD732-9EF8-32B7-82A1-C7A66977B8AA> /Applications/VLC.app/Contents/MacOS/plugins/libwav_plugin.dylib
        0x16dcf000 -         0x16dd0fff +libdirectory_demux_plugin.dylib (???) <96A0F96A-7DD7-3048-8A66-389F90C46A53> /Applications/VLC.app/Contents/MacOS/plugins/libdirectory_demux_plugin.dylib
        0x16e17000 -         0x16e1afff +libcaf_plugin.dylib (???) <8DC80AD9-0BB2-3EEA-A69D-DE55A228EFD8> /Applications/VLC.app/Contents/MacOS/plugins/libcaf_plugin.dylib
        0x16e22000 -         0x16e5bfff +libsid_plugin.dylib (???) <ECA0CFAF-1A2E-35A3-8184-DECCBB7B4AB0> /Applications/VLC.app/Contents/MacOS/plugins/libsid_plugin.dylib
        0x16e88000 -         0x16e96fff +libsap_plugin.dylib (???) <2E4F0D32-ADFF-3AD2-9C1D-11203740634A> /Applications/VLC.app/Contents/MacOS/plugins/libsap_plugin.dylib
        0x16e9e000 -         0x16e9fff7 +libdiracsys_plugin.dylib (???) <815D7D8A-1F47-3F63-8B87-8364E2026F42> /Applications/VLC.app/Contents/MacOS/plugins/libdiracsys_plugin.dylib
        0x16ea7000 -         0x16eaaff7 +libsmf_plugin.dylib (???) <567CA092-1142-3304-867E-BBDEFEE2E800> /Applications/VLC.app/Contents/MacOS/plugins/libsmf_plugin.dylib
        0x16ed6000 -         0x16ed7ff7 +libxa_plugin.dylib (???) <0E4B0F93-0BA6-3A2A-B7D4-789B0BC8B032> /Applications/VLC.app/Contents/MacOS/plugins/libxa_plugin.dylib
        0x16ee6000 -         0x16f22fff +libtheora_plugin.dylib (???) <334043A7-CCA5-383F-882C-EC76C19D15B3> /Applications/VLC.app/Contents/MacOS/plugins/libtheora_plugin.dylib
        0x16fa8000 -         0x16faafff +libvoc_plugin.dylib (???) <1A7E48BD-26EA-399D-81A6-18CE8B43A6A4> /Applications/VLC.app/Contents/MacOS/plugins/libvoc_plugin.dylib
        0x16fbf000 -         0x16fc1ff7 +libpva_plugin.dylib (???) <FD99BABD-EBBE-364E-ABD4-1DC236FEF4C0> /Applications/VLC.app/Contents/MacOS/plugins/libpva_plugin.dylib
        0x16fd6000 -         0x16fd8ff7 +librawvid_plugin.dylib (???) <592629F0-AF0E-364C-9849-BD95717E57A4> /Applications/VLC.app/Contents/MacOS/plugins/librawvid_plugin.dylib
        0x16fed000 -         0x16fefff7 +libnsv_plugin.dylib (???) <BB409021-31F1-382B-B4FD-872FB6297EEB> /Applications/VLC.app/Contents/MacOS/plugins/libnsv_plugin.dylib
        0x17004000 -         0x17006fff +libaiff_plugin.dylib (???) <91B574EE-CFB4-38E7-89B7-F1EF30C0818F> /Applications/VLC.app/Contents/MacOS/plugins/libaiff_plugin.dylib
        0x1700e000 -         0x1700ffff +libspdif_plugin.dylib (???) <94C42345-D7AF-340E-9E39-0575176C3322> /Applications/VLC.app/Contents/MacOS/plugins/libspdif_plugin.dylib
        0x17016000 -         0x17018ff7 +libaes3_plugin.dylib (???) <195E0C23-EBA5-3E32-95B6-1A5A5A2165E4> /Applications/VLC.app/Contents/MacOS/plugins/libaes3_plugin.dylib
        0x1701f000 -         0x17023ff7 +libg711_plugin.dylib (???) <CA31498E-35BD-301E-8879-186CAA2E9D28> /Applications/VLC.app/Contents/MacOS/plugins/libg711_plugin.dylib
        0x1702b000 -         0x1702efff +libimage_plugin.dylib (???) <B530BA2C-FA28-3A31-AD7E-1A4A481ED27F> /Applications/VLC.app/Contents/MacOS/plugins/libimage_plugin.dylib
        0x17039000 -         0x1703aff7 +libau_plugin.dylib (???) <A78E9450-9FCF-3113-8A16-A3C52F17814D> /Applications/VLC.app/Contents/MacOS/plugins/libau_plugin.dylib
        0x17043000 -         0x17066ff7 +libspeex_plugin.dylib (???) <8F74FF78-130E-3EE1-A235-82E30125EEA0> /Applications/VLC.app/Contents/MacOS/plugins/libspeex_plugin.dylib
        0x1706e000 -         0x17070fff +libamem_plugin.dylib (???) <D8533B5F-7D0A-3152-BB35-1B236B4C5F19> /Applications/VLC.app/Contents/MacOS/plugins/libamem_plugin.dylib
        0x17082000 -         0x17141fe7 +libdav1d_plugin.dylib (???) <72461C14-9C6E-3214-852E-D3C29AF4A709> /Applications/VLC.app/Contents/MacOS/plugins/libdav1d_plugin.dylib
        0x17196000 -         0x171d3fff +libjpeg_plugin.dylib (???) <7EB4FF09-9DFA-39F5-BC62-F9C940D70BE7> /Applications/VLC.app/Contents/MacOS/plugins/libjpeg_plugin.dylib
        0x171e1000 -         0x17223ff7 +libpng_plugin.dylib (???) <48E1AB01-1720-32EB-9D80-6C27050FCB5C> /Applications/VLC.app/Contents/MacOS/plugins/libpng_plugin.dylib
        0x1722c000 -         0x1722eff7 +libcdg_plugin.dylib (???) <823C0B98-C378-3736-825A-8AB480C3406C> /Applications/VLC.app/Contents/MacOS/plugins/libcdg_plugin.dylib
        0x17235000 -         0x17266fff +libvideotoolbox_plugin.dylib (0) <5AFC7669-67C5-3414-84F0-8462A68FBCC8> /Applications/VLC.app/Contents/MacOS/plugins/libvideotoolbox_plugin.dylib
        0x17270000 -         0x172fdff7  com.apple. AMDRadeonVADriver2 (3.2.24 - 3.0.2) <67D2818E-DDC5-3FE0-92CB-45F6D832F084> /System/Library/Extensions/AMDRadeonVADriver2.bundle/Contents/MacOS/AMDRadeonVADriver2
        0x17375000 -         0x173b8ff7 +libogg_plugin.dylib (???) <C9D1FB50-99B4-3B68-BAA7-9D67134D76E6> /Applications/VLC.app/Contents/MacOS/plugins/libogg_plugin.dylib
        0x173c1000 -         0x173d4fff +libwebvtt_plugin.dylib (???) <2714FB3E-CB34-3BC2-8E1A-7C12CD1D21C9> /Applications/VLC.app/Contents/MacOS/plugins/libwebvtt_plugin.dylib
        0x173dd000 -         0x173e4fff +libttml_plugin.dylib (???) <C8258363-3AAA-3A3C-8B22-978A1434B731> /Applications/VLC.app/Contents/MacOS/plugins/libttml_plugin.dylib
        0x173ec000 -         0x173f1fff +libps_plugin.dylib (???) <43FBEA30-6C62-33C2-A572-A302EBEE17C2> /Applications/VLC.app/Contents/MacOS/plugins/libps_plugin.dylib
        0x173f9000 -         0x17407fff +libh26x_plugin.dylib (???) <70682FE6-26BF-31EF-9CCF-B50A0EA95151> /Applications/VLC.app/Contents/MacOS/plugins/libh26x_plugin.dylib
        0x1740f000 -         0x17414fff +libty_plugin.dylib (???) <842D46A0-11A7-3779-9E93-64BEC8BE332E> /Applications/VLC.app/Contents/MacOS/plugins/libty_plugin.dylib
        0x17422000 -         0x17566fff +libschroedinger_plugin.dylib (???) <48F3144C-5679-3E30-8DDD-966530E83DD4> /Applications/VLC.app/Contents/MacOS/plugins/libschroedinger_plugin.dylib
        0x1757b000 -         0x1779bf47 +libaom_plugin.dylib (???) <4CB005A3-7991-337B-8C52-937822D6EB60> /Applications/VLC.app/Contents/MacOS/plugins/libaom_plugin.dylib
        0x177e0000 -         0x18816fe7 +libavcodec_plugin.dylib (???) <313D5AEF-F9BB-3C08-91FE-0A71276E8B01> /Applications/VLC.app/Contents/MacOS/plugins/libavcodec_plugin.dylib
        0x1a269000 -         0x1a2aefff +libfaad_plugin.dylib (???) <1217932A-4161-32AD-9626-08768E240EEA> /Applications/VLC.app/Contents/MacOS/plugins/libfaad_plugin.dylib
        0x1aebe000 -         0x1af8ffff +libtaglib_plugin.dylib (???) <09C0BA80-B720-30FD-B83F-1F3478EE76CC> /Applications/VLC.app/Contents/MacOS/plugins/libtaglib_plugin.dylib
        0x1afa0000 -         0x1afa1ff7 +libmpgv_plugin.dylib (???) <C4B6AD6D-518A-3C82-8F0C-02D2D38325A1> /Applications/VLC.app/Contents/MacOS/plugins/libmpgv_plugin.dylib
        0x1afa8000 -         0x1afabff7 +libmjpeg_plugin.dylib (???) <9EA54973-449D-3B4A-A58E-302ADC24337A> /Applications/VLC.app/Contents/MacOS/plugins/libmjpeg_plugin.dylib
        0x1afb3000 -         0x1afb5fff +libnsc_plugin.dylib (???) <7FBB0EED-5E7B-3125-8AA7-4C33A6AA1C89> /Applications/VLC.app/Contents/MacOS/plugins/libnsc_plugin.dylib
        0x1afbd000 -         0x1afbffff +librawdv_plugin.dylib (???) <812A551B-4CDD-378A-810B-9D5CD9D80C25> /Applications/VLC.app/Contents/MacOS/plugins/librawdv_plugin.dylib
        0x1afc7000 -         0x1afc8fff +libdemux_cdg_plugin.dylib (???) <3139A033-5409-3EB2-A50B-A6CB4F3C9661> /Applications/VLC.app/Contents/MacOS/plugins/libdemux_cdg_plugin.dylib
        0x1afdc000 -         0x1b117fff +libfreetype_plugin.dylib (???) <36031093-B7BD-3DCC-BCE9-756255E42B6B> /Applications/VLC.app/Contents/MacOS/plugins/libfreetype_plugin.dylib
        0x1b138000 -         0x1b139ff7 +libfloat_mixer_plugin.dylib (???) <FFC7E555-F392-3BC9-8E50-59A6755FD07C> /Applications/VLC.app/Contents/MacOS/plugins/libfloat_mixer_plugin.dylib
        0x1b140000 -         0x1b142fff +libinteger_mixer_plugin.dylib (???) <99A20689-DA7B-362B-9D68-E5E181C4A60E> /Applications/VLC.app/Contents/MacOS/plugins/libinteger_mixer_plugin.dylib
        0x1b149000 -         0x1b14bfff +libscaletempo_plugin.dylib (???) <9739242B-78E8-3F1C-9975-1AB45187C0CB> /Applications/VLC.app/Contents/MacOS/plugins/libscaletempo_plugin.dylib
        0x1b152000 -         0x1b2bdff7 +libsamplerate_plugin.dylib (???) <5444846A-DF27-3E2F-81B5-BF1EC9C6DC7E> /Applications/VLC.app/Contents/MacOS/plugins/libsamplerate_plugin.dylib
        0x1b2c9000 -         0x1b2cbff7 +libsimple_channel_mixer_plugin.dylib (???) <48A2E2C1-653A-3E6D-9A01-653EC6012E1D> /Applications/VLC.app/Contents/MacOS/plugins/libsimple_channel_mixer_plugin.dylib
        0x1b2d2000 -         0x1b2d5fff +libtospdif_plugin.dylib (???) <3613DF5F-B7E0-3235-9DDA-AA11A1AD979B> /Applications/VLC.app/Contents/MacOS/plugins/libtospdif_plugin.dylib
        0x1b2dc000 -         0x1b2ddfff +libdolby_surround_decoder_plugin.dylib (???) <D293CCFD-7611-3DD5-B920-1D66B0430B33> /Applications/VLC.app/Contents/MacOS/plugins/libdolby_surround_decoder_plugin.dylib
        0x1b2e4000 -         0x1b2e5fff +libugly_resampler_plugin.dylib (???) <8432F006-B3FA-3808-AC54-19E7C767E043> /Applications/VLC.app/Contents/MacOS/plugins/libugly_resampler_plugin.dylib
        0x1b2ec000 -         0x1b2effff +libaudio_format_plugin.dylib (???) <361F5682-DA5F-368E-8C71-6ECF89376B87> /Applications/VLC.app/Contents/MacOS/plugins/libaudio_format_plugin.dylib
        0x1b349000 -         0x1b3c4fff +liblive555_plugin.dylib (???) <C31A3372-5B3E-373A-9676-74DAED59B447> /Applications/VLC.app/Contents/MacOS/plugins/liblive555_plugin.dylib
        0x1b42e000 -         0x1b4ecff7 +libmkv_plugin.dylib (???) <B850B1F2-66E9-3DF1-9E8B-CBF9E4201592> /Applications/VLC.app/Contents/MacOS/plugins/libmkv_plugin.dylib
        0x1b561000 -         0x1b5affff +libgme_plugin.dylib (???) <30E9A6F6-3DD8-33AE-8109-E094D602E231> /Applications/VLC.app/Contents/MacOS/plugins/libgme_plugin.dylib
        0x1b5ba000 -         0x1b63bff7 +libts_plugin.dylib (???) <9E37DCEE-6FE1-38AB-9FDD-7D8180269F68> /Applications/VLC.app/Contents/MacOS/plugins/libts_plugin.dylib
        0x1b681000 -         0x1b7a6ff7 +libadaptive_plugin.dylib (???) <E2DC1573-2B69-336E-AC73-8401822620A8> /Applications/VLC.app/Contents/MacOS/plugins/libadaptive_plugin.dylib
        0x1b7c0000 -         0x1b80dfff +libmod_plugin.dylib (???) <0E955CDE-3A38-3280-B100-988E427F0CD2> /Applications/VLC.app/Contents/MacOS/plugins/libmod_plugin.dylib
        0x1b8d9000 -         0x1b8dcfff +libi420_yuy2_sse2_plugin.dylib (???) <FC9EC5B9-6560-3609-A81B-F0FF63678C42> /Applications/VLC.app/Contents/MacOS/plugins/libi420_yuy2_sse2_plugin.dylib
        0x1b8e3000 -         0x1b8e5fff +libi420_yuy2_mmx_plugin.dylib (???) <133CB2EA-B2AE-323D-A280-15D820275B2B> /Applications/VLC.app/Contents/MacOS/plugins/libi420_yuy2_mmx_plugin.dylib
        0x1b8ec000 -         0x1b8f1fff +libi420_nv12_plugin.dylib (???) <D98B01F5-06AD-3B05-BFBF-A4F65B445482> /Applications/VLC.app/Contents/MacOS/plugins/libi420_nv12_plugin.dylib
        0x1b8f9000 -         0x1b9dffff +libswscale_plugin.dylib (???) <226C6099-21FD-3990-9663-A0A642197BB9> /Applications/VLC.app/Contents/MacOS/plugins/libswscale_plugin.dylib
        0x1ba18000 -         0x1ba21ff7 +libi420_rgb_sse2_plugin.dylib (???) <CD2BEEAD-799A-3E44-92AF-B8B31ED66E4E> /Applications/VLC.app/Contents/MacOS/plugins/libi420_rgb_sse2_plugin.dylib
        0x1ba29000 -         0x1ba2bff7 +libi422_yuy2_sse2_plugin.dylib (???) <E328BA0E-541B-342F-83D8-FF3B45D49423> /Applications/VLC.app/Contents/MacOS/plugins/libi422_yuy2_sse2_plugin.dylib
        0x1ba32000 -         0x1ba33ff7 +libi422_yuy2_mmx_plugin.dylib (???) <5F62BE09-9EE8-3D0D-8304-A790831E860E> /Applications/VLC.app/Contents/MacOS/plugins/libi422_yuy2_mmx_plugin.dylib
        0x1ba3a000 -         0x1ba3fff7 +libi420_rgb_mmx_plugin.dylib (???) <298740C8-A98F-3636-8E1F-87CEFCDB30DD> /Applications/VLC.app/Contents/MacOS/plugins/libi420_rgb_mmx_plugin.dylib
        0x1ba47000 -         0x1ba48ff7 +libyuy2_i422_plugin.dylib (???) <E50C43BD-01E7-3D24-B706-EA1CFE4D465B> /Applications/VLC.app/Contents/MacOS/plugins/libyuy2_i422_plugin.dylib
        0x1ba4f000 -         0x1ba51fff +libi420_yuy2_plugin.dylib (???) <DB47BC57-1F73-3688-8BBE-9F0D29496230> /Applications/VLC.app/Contents/MacOS/plugins/libi420_yuy2_plugin.dylib
        0x1ba58000 -         0x1ba5aff7 +libi422_yuy2_plugin.dylib (???) <4FC567DE-DE6B-3DD9-B54B-71AA90F93C6F> /Applications/VLC.app/Contents/MacOS/plugins/libi422_yuy2_plugin.dylib
        0x1ba61000 -         0x1ba63fff +libyuy2_i420_plugin.dylib (???) <A8B48CD7-6A71-3FB9-BDBE-EC3D60EC34B2> /Applications/VLC.app/Contents/MacOS/plugins/libyuy2_i420_plugin.dylib
        0x1ba6a000 -         0x1ba6fff7 +libi420_rgb_plugin.dylib (???) <9D820E0F-3C5B-3560-98C3-B1D2DF5BC0E1> /Applications/VLC.app/Contents/MacOS/plugins/libi420_rgb_plugin.dylib
        0x1ba76000 -         0x1ba77fff +libgrey_yuv_plugin.dylib (???) <955CBA90-386F-3B3B-AE0E-99AC63679AE9> /Applications/VLC.app/Contents/MacOS/plugins/libgrey_yuv_plugin.dylib
        0x1ba7e000 -         0x1ba7fff7 +libi422_i420_plugin.dylib (???) <69DD8589-85F0-32E8-942E-B653E1D159C8> /Applications/VLC.app/Contents/MacOS/plugins/libi422_i420_plugin.dylib
        0x1bad9000 -         0x1bae1fff +libcvpx_plugin.dylib (0) <8B3BEF59-EBFC-3CD9-9008-0A3879FFDF10> /Applications/VLC.app/Contents/MacOS/plugins/libcvpx_plugin.dylib
        0x1bcf2000 -         0x1bcf3fff +libscale_plugin.dylib (???) <849991E6-5BF4-3B5C-AA10-39F8CC60BE16> /Applications/VLC.app/Contents/MacOS/plugins/libscale_plugin.dylib
        0x1bcfc000 -         0x1bcfdfff +libyuvp_plugin.dylib (???) <33FC7421-2CAE-3CF5-A03F-B9EBD3E23B52> /Applications/VLC.app/Contents/MacOS/plugins/libyuvp_plugin.dylib
        0x1bd08000 -         0x1bd0afff +libvmem_plugin.dylib (???) <BEC19F2B-EB4A-32D8-96D5-D49D114DA563> /Applications/VLC.app/Contents/MacOS/plugins/libvmem_plugin.dylib
        0x2070e000 -         0x2083eff7 +libxml_plugin.dylib (???) <F6CD217A-95B7-3AF7-AD36-183A9749EA4B> /Applications/VLC.app/Contents/MacOS/plugins/libxml_plugin.dylib
       0x105b7e000 -        0x105d41ff7 +com.obsproject.obs-studio (24.0.6 - 24.0.6) <DFAFD096-23A0-3A32-987F-124315A89F7E> /Applications/OBS.app/Contents/MacOS/obs
       0x105e20000 -        0x105e54ff7 +org.qt-project.QtSvg (5.10 - 5.10.1) <94493A0C-14EA-3F19-9FE0-469849546C03> /Applications/OBS.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
       0x105e7d000 -        0x105e80fff +libobs-frontend-api.dylib (0) <5C26E4A8-6A34-3BC9-BBB1-79D6B74AF7B0> /Applications/OBS.app/Contents/Frameworks/libobs-frontend-api.dylib
       0x105e8c000 -        0x10707bfa7 +libavcodec.58.dylib (0) <727CE897-84DD-3455-8F14-EB7E14BE6BA0> /Applications/OBS.app/Contents/Frameworks/libavcodec.58.dylib
       0x107a25000 -        0x107a6dff7 +libavutil.56.dylib (0) <44EC8515-1760-30AC-858C-21DC72F8F28C> /Applications/OBS.app/Contents/Frameworks/libavutil.56.dylib
       0x107a9b000 -        0x107c5aff7 +libavformat.58.dylib (0) <59CFFD9F-A443-374F-8B8E-9310845D9959> /Applications/OBS.app/Contents/Frameworks/libavformat.58.dylib
       0x107cab000 -        0x107d04ff7 +libcurl.4.dylib (0) <44416E14-0612-37BB-A429-62F4F3BE1DF0> /Applications/OBS.app/Contents/Frameworks/libcurl.4.dylib
       0x107d1b000 -        0x107d64ff7 +org.sparkle-project.Sparkle (1.20.0 - 1.20.0) <CE792D43-180A-3237-978D-966E2CF21125> /Applications/OBS.app/Contents/Frameworks/Sparkle.framework/Versions/A/Sparkle
       0x107db2000 -        0x107dbaffb +org.qt-project.QtMacExtras (5.10 - 5.10.1) <92C504C1-1B73-3C37-8C8D-B915A0D66E05> /Applications/OBS.app/Contents/Frameworks/QtMacExtras.framework/Versions/5/QtMacExtras
       0x107dc7000 -        0x1081f3ff7 +org.qt-project.QtWidgets (5.10 - 5.10.1) <AD15E490-1C7E-344F-9B40-A684A9160882> /Applications/OBS.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10836c000 -        0x108411fff +libobs.0.dylib (0) <ABE38A39-72B3-3FF3-BB37-2609F1B30E73> /Applications/OBS.app/Contents/Frameworks/libobs.0.dylib
       0x108474000 -        0x1088a1ff7 +org.qt-project.QtGui (5.10 - 5.10.1) <96CF196B-1BBB-317F-9F39-86DD41787FC9> /Applications/OBS.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x1089b5000 -        0x108e96fff +org.qt-project.QtCore (5.10 - 5.10.1) <0967D4C1-9487-3421-9861-304DEE848576> /Applications/OBS.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x108f67000 -        0x109025fff +libswscale.5.dylib (0) <3CAAD39B-E15E-3943-AEFE-31F0B5F9F16D> /Applications/OBS.app/Contents/Frameworks/libswscale.5.dylib
       0x10903e000 -        0x109059ff7 +libswresample.3.dylib (0) <0049AA29-C7EF-38E0-B707-9E88E9AB100E> /Applications/OBS.app/Contents/Frameworks/libswresample.3.dylib
       0x115cb0000 -        0x115d40b5f  dyld (733.6) <DAFEA246-2F9A-3DCB-A37C-4246D4F92770> /usr/lib/dyld
    0x7fff2e1e0000 -     0x7fff2e300ff5  com.apple.AMDMTLBronzeDriver (3.2.24 - 3.0.2) <63C45CEB-4AD1-396E-90C5-9A09B90C2584> /System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver
    0x7fff2e301000 -     0x7fff2e337ff7  ATIRadeonX4000SCLib.dylib (3.2.24) <3DC8C112-6831-3B42-ADFA-C42C37B9F7DB> /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib
    0x7fff2f925000 -     0x7fff3059dfff  libSC.dylib (3.2.24) <FE028806-66DD-33A6-9E5C-BB838360F440> /System/Library/Extensions/AMDShared.bundle/Contents/PlugIns/libSC.dylib
    0x7fff352d9000 -     0x7fff352ddffb  com.apple.agl (3.3.3 - AGL-3.3.3) <2DAAE917-6792-35B7-8BCE-C785ACDF8174> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff352de000 -     0x7fff354d7ffd  com.apple.avfoundation (2.0 - 1730.15) <EA7413E2-C050-380B-A396-F622BFA73071> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff354d8000 -     0x7fff355a4ff8  com.apple.audio.AVFAudio (1.0 - ???) <4978E752-5EF4-3066-963B-68B208871BD6> /System/Library/Frameworks/AVFoundation.framework/Versions/A/Frameworks/AVFAudio.framework/Versions/A/AVFAudio
    0x7fff356c4000 -     0x7fff356c4fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <956D070C-B522-3A08-891A-CAD6BA4082D1> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff356c5000 -     0x7fff356dbff7  libCGInterfaces.dylib (524.2) <23142415-0CD0-3020-B17E-F600C3889856> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff356dc000 -     0x7fff35d47fdf  com.apple.vImage (8.1 - 524.2) <DCF3349F-1159-3F46-81E0-C18E041DC940> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff35d48000 -     0x7fff35fb0fff  libBLAS.dylib (1303) <B950B953-116A-3C78-91A9-F983F61BC795> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff35fb1000 -     0x7fff362a0ff7  libBNNS.dylib (144.40.3) <BAE2A5E4-14A1-3C54-86DF-888FA26C745E> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff362a2000 -     0x7fff36647fff  libLAPACK.dylib (1303) <5C248B39-F233-3074-A3A5-AF8F436FBF87> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff36648000 -     0x7fff3665dff8  libLinearAlgebra.dylib (1303) <3AEC87AB-568C-3D88-959A-D6D8C2776FEC> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff3665e000 -     0x7fff36663ff3  libQuadrature.dylib (7) <7EE59014-8FC5-3369-868B-8A87E590BF78> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff36664000 -     0x7fff366d4fff  libSparse.dylib (103) <093F97A4-47DE-38DF-BB7A-FF5A3FB0BB3B> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff366d5000 -     0x7fff366e7fef  libSparseBLAS.dylib (1303) <4536B3F7-7017-36F5-B500-1A63F691CE03> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff366e8000 -     0x7fff368c1ffb  libvDSP.dylib (735) <E849AEB0-2995-38A4-B0C3-4ACEAF434D12> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff368c2000 -     0x7fff3697dfd3  libvMisc.dylib (735) <18B48679-444E-3680-A9B2-006A8D1DE3EB> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff3697e000 -     0x7fff3697efff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <79C1A1C7-E97A-3B7A-8737-444B402A7AA0> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff3697f000 -     0x7fff369deffc  com.apple.Accounts (113 - 113) <93F6714C-3028-3F7B-AA9B-82ED89D20D88> /System/Library/Frameworks/Accounts.framework/Versions/A/Accounts
    0x7fff369e0000 -     0x7fff36b22ff5  com.apple.AddressBook.framework (11.0 - 2421) <FB94811C-67C1-34BA-B64F-7041695D33E3> /System/Library/Frameworks/AddressBook.framework/Versions/A/AddressBook
    0x7fff36b23000 -     0x7fff378dbffe  com.apple.AppKit (6.9 - 1894.10.126) <76EB4086-CA3D-3448-8CE0-9812F9A94F3A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3792b000 -     0x7fff3792bfff  com.apple.ApplicationServices (48 - 50) <0748E453-524B-33BA-806B-22786DED2958> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3792c000 -     0x7fff37997fff  com.apple.ApplicationServices.ATS (377 - 493) <CF8434BF-B51D-3A68-B6FC-AFB0765530A2> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff37a30000 -     0x7fff37a6effa  libFontRegistry.dylib (274) <A512DEE5-A697-3EE6-AF9D-606C9D9156A0> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff37ac9000 -     0x7fff37af8ff7  com.apple.ATSUI (1.0 - 1) <50DC5F09-5336-3718-AEE9-490773BA3070> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATSUI.framework/Versions/A/ATSUI
    0x7fff37af9000 -     0x7fff37afdff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <D4F7C969-FE2C-3036-94E3-FD2882F89C6F> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff37b98000 -     0x7fff37beeffa  com.apple.HIServices (1.22 - 672) <0B1FD2E8-DEBD-3ED3-82F7-E0F80F21621A> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff37bef000 -     0x7fff37bfdfff  com.apple.LangAnalysis (1.7.0 - 1.7.0) <72ECDBB9-F607-3FB3-ABC3-882C9EFB3245> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff37bfe000 -     0x7fff37c43ff2  com.apple.print.framework.PrintCore (15 - 516) <78F4A9D5-82F5-3578-A78F-CDD438DB6A6C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff37c44000 -     0x7fff37c4efff  com.apple.QD (4.0 - 413) <63CCC6D7-659A-341A-A8A4-55B596EEFE9C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff37c4f000 -     0x7fff37c5cff0  com.apple.speech.synthesis.framework (9.0.22 - 9.0.22) <202F6033-A76D-3B2C-9BA9-9CCF4493AB4D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff37c5d000 -     0x7fff37d3dff2  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <CAE6B655-8D07-3040-811E-CE5DE42249AE> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff37d3f000 -     0x7fff37d3ffff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <FE7A9727-7F3F-3E0F-B827-DF421993ED12> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff380b5000 -     0x7fff3842cffb  com.apple.CFNetwork (1120 - 1120) <5EA797F3-2F7A-3E0C-8DBC-DBE145004EC5> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff384a6000 -     0x7fff384a6fff  com.apple.Carbon (160 - 162) <56A09CBE-D5EB-3918-B42B-B3ABFF52E1D1> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff384a7000 -     0x7fff384aaffb  com.apple.CommonPanels (1.2.6 - 101) <9286951D-8B2F-3A4B-86B2-767AFCC6A591> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff384ab000 -     0x7fff3879fff3  com.apple.HIToolbox (2.1.1 - 993.4) <AB2DC9D2-6A2A-3EB0-8ED9-8053CFEEC0A9> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff387a0000 -     0x7fff387a3ff3  com.apple.help (1.3.8 - 68) <64630D33-B292-3FD1-A3B7-AE98D4157EF1> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff387a4000 -     0x7fff387a9ff7  com.apple.ImageCapture (9.0 - 1600.18) <4B628CBB-65EC-3A36-8EBB-2F9D7D328744> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff387aa000 -     0x7fff387aafff  com.apple.ink.framework (10.15 - 227) <ED29C75F-6E14-352E-ACB9-AA899E2F5429> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff387ab000 -     0x7fff387c5ff2  com.apple.openscripting (1.7 - 185.1) <D300E418-CF0F-3127-BCBA-A7553F2F1E88> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff387e6000 -     0x7fff387e6fff  com.apple.print.framework.Print (15 - 271) <4DDF3DC5-A69B-3BB8-B5F3-42ECC341A0B4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff387e7000 -     0x7fff387e9ff7  com.apple.securityhi (9.0 - 55008) <8E09C68A-87BB-3D55-A52F-AB1B249D06F8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff387ea000 -     0x7fff387f0ff7  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <E2CECD92-568A-3C7A-AD98-D99CEF1BBCBF> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff387f1000 -     0x7fff3898affd  com.apple.cloudkit.CloudKit (854 - 854) <9A3AB320-1CB0-3C02-A492-5DD069964403> /System/Library/Frameworks/CloudKit.framework/Versions/A/CloudKit
    0x7fff3898b000 -     0x7fff3898bfff  com.apple.Cocoa (6.11 - 23) <EB4AD4EA-3212-385A-876E-9F8B30F8CA56> /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa
    0x7fff38999000 -     0x7fff38b84ff7  com.apple.ColorSync (4.13.0 - 3394.3) <DCAECEC5-F7D0-3A28-AE9D-3FA59CC9FB26> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff38c7d000 -     0x7fff38db2ff0  com.apple.contacts (1.0 - 3455.0.1) <4AFC923E-6985-3604-8645-D1F77E46E3BB> /System/Library/Frameworks/Contacts.framework/Versions/A/Contacts
    0x7fff38e6e000 -     0x7fff3937dffa  com.apple.audio.CoreAudio (5.0 - 5.0) <73C7F0DD-8919-3056-AB1F-67705F942A04> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff393d0000 -     0x7fff39407ff0  com.apple.CoreBluetooth (1.0 - 1) <E57B1D4A-DF7A-37F3-833A-CD440EB58685> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff39408000 -     0x7fff397e6ffc  com.apple.CoreData (120 - 973.1) <AC3856BC-894E-30C4-BA99-25C06A3D9FE8> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff397e7000 -     0x7fff398f3ff6  com.apple.CoreDisplay (1.0 - 186.2.4) <AD10EEEB-9A5F-3904-A487-50F13E4B2357> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff398f4000 -     0x7fff39d73fe7  com.apple.CoreFoundation (6.9 - 1673.126) <15D61616-B29B-3BDB-8624-4B84A4956485> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff39d75000 -     0x7fff3a3edff0  com.apple.CoreGraphics (2.0 - 1348.12.4.3) <B8D7910C-0C72-315F-8CE1-C257FD0ADD84> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff3a3fb000 -     0x7fff3a758ff5  com.apple.CoreImage (15.0.0 - 910.8) <CE3DB305-25FF-31FE-9334-C2370473BAAF> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff3a759000 -     0x7fff3a7c1ff5  com.apple.corelocation (2388.0.21 - 2388.0.21) <D9BE9D62-C4E4-32AF-9E98-770AE8778A90> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff3a7c2000 -     0x7fff3a813ffe  com.apple.audio.midi.CoreMIDI (1.10 - 88) <1C62E74B-4D5F-3C34-9284-6BF086A33B7C> /System/Library/Frameworks/CoreMIDI.framework/Versions/A/CoreMIDI
    0x7fff3a816000 -     0x7fff3ab1bff2  com.apple.CoreML (1.0 - 1) <0B25AECE-A5F7-3483-9296-24791531F0F3> /System/Library/Frameworks/CoreML.framework/Versions/A/CoreML
    0x7fff3ab1c000 -     0x7fff3abf6ffc  com.apple.CoreMedia (1.0 - 2510.17.4.6) <A455F944-F862-3668-AA2C-008106F9814F> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff3abf7000 -     0x7fff3ac58ff6  com.apple.CoreMediaIO (1000.0 - 5125.3) <61698CAC-C8A3-33F2-B09F-DDC1A7319644> /System/Library/Frameworks/CoreMediaIO.framework/Versions/A/CoreMediaIO
    0x7fff3ace1000 -     0x7fff3ace1fff  com.apple.CoreServices (1069.11 - 1069.11) <C8F86BE7-AAED-30A6-BBC2-550446137E7C> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3ace2000 -     0x7fff3ad67ff7  com.apple.AE (838 - 838) <3301AF1B-D178-306A-9641-B57AA03FB1BE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff3ad68000 -     0x7fff3b049fff  com.apple.CoreServices.CarbonCore (1217 - 1217) <FAA1467B-6D39-3EBE-9810-A4DF49478F10> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff3b04a000 -     0x7fff3b097ffd  com.apple.DictionaryServices (1.2 - 323) <C1798F09-36D3-3C8E-AF72-A3DE63962AF1> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff3b098000 -     0x7fff3b0a0fff  com.apple.CoreServices.FSEvents (1268.40.5 - 1268.40.5) <9BB76885-7CD7-3369-B759-33F7E5DA5392> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff3b0a1000 -     0x7fff3b2daff0  com.apple.LaunchServices (1069.11 - 1069.11) <88F59BD5-412A-35EE-AD45-E6BF80B24891> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff3b2db000 -     0x7fff3b373ff9  com.apple.Metadata (10.7.0 - 2074.4) <028AC15A-35B7-3E1F-BCDC-470C8EA0CA09> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff3b374000 -     0x7fff3b3a1ff7  com.apple.CoreServices.OSServices (1069.11 - 1069.11) <A667F007-A599-3869-99F7-1F8460011015> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff3b3a2000 -     0x7fff3b409fff  com.apple.SearchKit (1.4.1 - 1.4.1) <F0A931E4-0C31-36BA-8DD7-01FDF9813FB7> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff3b40a000 -     0x7fff3b42effd  com.apple.coreservices.SharedFileList (131 - 131) <62C3066A-3991-313F-AE2D-75B2B5934D52> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff3b42f000 -     0x7fff3b4a0ff7  com.apple.CoreSpotlight (1.0 - 2074.4) <702DAB35-ED5E-335C-86D9-C2512BD89C16> /System/Library/Frameworks/CoreSpotlight.framework/Versions/A/CoreSpotlight
    0x7fff3b690000 -     0x7fff3b755ff4  com.apple.CoreTelephony (113 - 7271.2) <E9E4C228-3B5C-3670-8604-A97AD2415078> /System/Library/Frameworks/CoreTelephony.framework/Versions/A/CoreTelephony
    0x7fff3b756000 -     0x7fff3b90aff6  com.apple.CoreText (643.1.1.5 - 643.1.1.5) <4525DC61-0B5B-33B2-A249-68C6A1267EE7> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff3b90b000 -     0x7fff3b94ffff  com.apple.CoreVideo (1.8 - 334.0) <52692CD0-764F-3D77-9087-2825ED39AD0F> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff3b950000 -     0x7fff3b9ddff1  com.apple.framework.CoreWLAN (13.0 - 1455.3) <3F7DCCA2-A5E2-3196-B2C7-31491192E75C> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff3bba3000 -     0x7fff3bbaeff7  com.apple.DirectoryService.Framework (10.15 - 220.40.1) <71100385-C865-3DEE-9B4E-B78E918E542B> /System/Library/Frameworks/DirectoryService.framework/Versions/A/DirectoryService
    0x7fff3bbaf000 -     0x7fff3bc5aff0  com.apple.DiscRecording (9.0.3 - 9030.4.5) <F200BFE6-5AF1-34BA-8A87-B06753141358> /System/Library/Frameworks/DiscRecording.framework/Versions/A/DiscRecording
    0x7fff3bc7f000 -     0x7fff3bc85ff7  com.apple.DiskArbitration (2.7 - 2.7) <A3D2B0A0-3C72-3893-87BF-D45FE398A905> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff3bca9000 -     0x7fff3be57ffc  com.apple.ical.EventKit (3.0 - 1370.2.5) <4646AC1D-AE43-3341-B7D7-0E6ECD724A2B> /System/Library/Frameworks/EventKit.framework/Versions/A/EventKit
    0x7fff3be78000 -     0x7fff3bf9fff7  com.apple.FileProvider (257 - 257) <E6755796-E58D-3C24-A0E9-0029521120C4> /System/Library/Frameworks/FileProvider.framework/Versions/A/FileProvider
    0x7fff3bfb4000 -     0x7fff3bfb6ff3  com.apple.ForceFeedback (1.0.6 - 1.0.6) <F32CE77A-2878-3D3B-BFC0-0C7A8526CC1C> /System/Library/Frameworks/ForceFeedback.framework/Versions/A/ForceFeedback
    0x7fff3bfb7000 -     0x7fff3c37eff4  com.apple.Foundation (6.9 - 1673.126) <470C2315-3047-39BB-BB6B-2C620087091C> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3c3eb000 -     0x7fff3c43bff3  com.apple.GSS (4.0 - 2.0) <A149061D-5893-35B5-AE7F-BA889DFEADB2> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff3c43c000 -     0x7fff3c468ffe  com.apple.GameController (1.0 - 1) <7DC9FF50-4CF9-3155-9974-59F2BA3C0523> /System/Library/Frameworks/GameController.framework/Versions/A/GameController
    0x7fff3c575000 -     0x7fff3c68dff8  com.apple.Bluetooth (7.0.1 - 7.0.1f1) <61A2BDF8-E3AC-3714-A967-92404AC52389> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff3c6f4000 -     0x7fff3c797ffb  com.apple.framework.IOKit (2.0.2 - 1726.41.1) <FBB4A97B-D7CF-3B8C-932D-672343D63260> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff3c799000 -     0x7fff3c7a9ff4  com.apple.IOSurface (269.6 - 269.6) <DB88C9C2-0F53-3C77-98F0-1D8A1DFA9CB1> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff3c7c7000 -     0x7fff3c81fff6  com.apple.ImageCaptureCore (1.0 - 1600.18) <E61ECB5C-38AC-3D4F-A770-A422260B3E77> /System/Library/Frameworks/ImageCaptureCore.framework/Versions/A/ImageCaptureCore
    0x7fff3c820000 -     0x7fff3c97cffe  com.apple.ImageIO.framework (3.3.0 - 1972.11.4.4) <2809F8D6-7B13-3703-B266-C5B7A6B62D97> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3c97d000 -     0x7fff3c980fff  libGIF.dylib (1972.11.4.4) <2BFC7FDD-4A4F-323C-B60A-3B4AE526F7CE> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff3c981000 -     0x7fff3ca3bfef  libJP2.dylib (1972.11.4.4) <214BCCF5-2A06-3B4A-B2B8-4ECCB4B32D1C> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff3ca3c000 -     0x7fff3ca60fef  libJPEG.dylib (1972.11.4.4) <DBE9F84B-D9A2-3044-BFE2-B3853025FD9F> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff3ccde000 -     0x7fff3ccf8fe7  libPng.dylib (1972.11.4.4) <BD63D82F-55E5-32DB-96F9-8D7A3CDDA272> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff3ccf9000 -     0x7fff3ccfafff  libRadiance.dylib (1972.11.4.4) <2454AEBE-BE87-3D0F-BE68-6ECA3FCA361C> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff3ccfb000 -     0x7fff3cd44fff  libTIFF.dylib (1972.11.4.4) <73A90FA4-9A51-3653-8F14-2EBBFEED3F78> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff3cd5d000 -     0x7fff3d1baffe  com.apple.Intents (1.0 - 1) <F4CE5FC2-AB7F-350D-8453-EA0F80BB6EE9> /System/Library/Frameworks/Intents.framework/Versions/A/Intents
    0x7fff3d1bd000 -     0x7fff3e151ff1  com.apple.JavaScriptCore (15608 - 15608.3.10.1.4) <84426449-FDEA-3B11-94AB-544A56CB07B3> /System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff3e169000 -     0x7fff3e17bff3  com.apple.Kerberos (3.0 - 1) <8018F664-0026-3CC3-8685-3E2FE0BF2C7F> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff3e17c000 -     0x7fff3e17cfff  libHeimdalProxy.dylib (77) <51DB9CFB-808F-32E8-BB34-39F6702DBDED> /System/Library/Frameworks/Kerberos.framework/Versions/A/Libraries/libHeimdalProxy.dylib
    0x7fff3e17d000 -     0x7fff3e1b3fff  com.apple.LDAPFramework (2.4.28 - 194.5) <33F235C9-B0D4-3005-B395-DACE6DD93855> /System/Library/Frameworks/LDAP.framework/Versions/A/LDAP
    0x7fff3e2c8000 -     0x7fff3e2e9ff1  com.apple.CoreAuthentication.SharedUtils (1.0 - 693.40.8) <74C59535-88EE-3008-BADD-5CAD05D6E02B> /System/Library/Frameworks/LocalAuthentication.framework/Support/SharedUtils.framework/Versions/A/SharedUtils
    0x7fff3e2ea000 -     0x7fff3e302ffc  com.apple.LocalAuthentication (1.0 - 693.40.8) <3311AD26-C9F5-3381-891D-CA035E7A3B8C> /System/Library/Frameworks/LocalAuthentication.framework/Versions/A/LocalAuthentication
    0x7fff3e50f000 -     0x7fff3e519fff  com.apple.MediaAccessibility (1.0 - 125) <DD6304A2-1692-3C69-9FEA-B51F92510D5B> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff3e52d000 -     0x7fff3e5e4ff9  com.apple.MediaPlayer (1.0 - 1.0) <41C84531-7B33-3169-8CC7-AA4D60B65A1D> /System/Library/Frameworks/MediaPlayer.framework/Versions/A/MediaPlayer
    0x7fff3e5e5000 -     0x7fff3ed28ff7  com.apple.MediaToolbox (1.0 - 2510.17.4.6) <3F852775-C302-3EE8-8631-31D96375BD73> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff3ed2a000 -     0x7fff3ededff9  com.apple.Metal (212.2.3 - 212.2.3) <AA7DE079-2DFD-3E9F-A041-464CFBE1ABAE> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff3edef000 -     0x7fff3ee09ffc  com.apple.MetalKit (141.1 - 141.1) <B210E250-B13F-3E6E-BD40-CAE44A1C131F> /System/Library/Frameworks/MetalKit.framework/Versions/A/MetalKit
    0x7fff3ee0a000 -     0x7fff3ee46ff3  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <FB95B500-E5A3-3FAD-882E-D12FD9CA0964> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff3ee47000 -     0x7fff3eecdfe6  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <C0E349E7-ADE3-3353-8CFF-3DAD653F810E> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff3eece000 -     0x7fff3eef2ff8  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <8665FDF1-210F-3A8C-9D5D-FA0C49FD8C8C> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff3eef3000 -     0x7fff3ef08fff  com.apple.MetalPerformanceShaders.MPSNDArray (1.0 - 1) <EE7CF802-BF7F-3EEC-9EC2-26A3B3432275> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNDArray.framework/Versions/A/MPSNDArray
    0x7fff3ef09000 -     0x7fff3f068ff4  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <46C9BDBB-1FB9-3E1A-A02C-818D16E472D9> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff3f069000 -     0x7fff3f0b7fff  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <7CFEE008-E1AD-30FE-B0B7-9A7459701234> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff3f0b8000 -     0x7fff3f0b9ff5  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <241617D0-E5E7-3E36-971E-E278D15990A9> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff3ffff000 -     0x7fff4000bffe  com.apple.NetFS (6.0 - 4.0) <5C3C3672-2549-316E-9AC6-A1CFDCD16E9C> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff4000c000 -     0x7fff4014fff6  com.apple.Network (1.0 - 1) <38F65393-1393-3888-9F02-C4087F19CA0D> /System/Library/Frameworks/Network.framework/Versions/A/Network
    0x7fff40150000 -     0x7fff403b7ffa  com.apple.NetworkExtension (1.0 - 1) <633ED770-D5B5-306D-9B8E-1F727AFA60F2> /System/Library/Frameworks/NetworkExtension.framework/Versions/A/NetworkExtension
    0x7fff42b6f000 -     0x7fff42b77fff  libcldcpuengine.dylib (2.12.7) <A868A807-EA7D-3F78-9AEB-74E0AC72F8EC> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fff42b78000 -     0x7fff42bd0ff7  com.apple.opencl (3.5 - 3.5) <D734AF0C-0EA3-3264-BBF9-D3099ACF47E3> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff42bd1000 -     0x7fff42bedfff  com.apple.CFOpenDirectory (10.15 - 220.40.1) <AA81FC34-A7F6-3DA2-A275-B34F75099C7B> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff42bee000 -     0x7fff42bf9fff  com.apple.OpenDirectory (10.15 - 220.40.1) <ECFA2FFB-D5B6-3916-96F7-9F3A1EB1E534> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff43554000 -     0x7fff43556fff  libCVMSPluginSupport.dylib (17.10.22) <48C3CA4F-69EF-31E7-9120-0BA8E9162ACA> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff43557000 -     0x7fff4355cfff  libCoreFSCache.dylib (176.9) <D5D62F22-9099-370B-B264-B5398554EF0B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff4355d000 -     0x7fff43561fff  libCoreVMClient.dylib (176.9) <31DA9263-05A0-35A5-9CB8-40F8311B964B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff43562000 -     0x7fff4356aff7  libGFXShared.dylib (17.10.22) <B153F11B-C10F-38FE-AB8D-9E6C5315F210> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff4356b000 -     0x7fff43575fff  libGL.dylib (17.10.22) <59E124FF-8F56-3028-9816-40699F152B3B> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff43576000 -     0x7fff435abfff  libGLImage.dylib (17.10.22) <7EC55D26-7FA5-3B7B-A552-C50FA0308101> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff435ac000 -     0x7fff4373eff7  libGLProgrammability.dylib (17.10.22) <832152E0-CE51-3BFD-B21E-DF2111D0C8F7> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fff4373f000 -     0x7fff4377bfff  libGLU.dylib (17.10.22) <A4C86485-7CDF-30B0-ACB5-B0D11CA88ED0> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff441ab000 -     0x7fff441baff7  com.apple.opengl (17.10.22 - 17.10.22) <0142B045-DCF8-3554-A7FB-48A173541E40> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff441bb000 -     0x7fff44334ff7  GLEngine (17.10.22) <3B0B4AB6-3D54-3475-A50B-73C565244063> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fff44335000 -     0x7fff4435dfff  GLRendererFloat (17.10.22) <F2C6CBD1-30C3-3A1F-9976-C888359930A4> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fff44369000 -     0x7fff4445dff2  com.apple.PDFKit (1.0 - 825.10) <871F915A-FC4C-3681-86BE-4CB3FEB43321> /System/Library/Frameworks/PDFKit.framework/Versions/A/PDFKit
    0x7fff4445e000 -     0x7fff44576ffd  com.apple.PencilKit (1.0 - 1) <373BB4D0-0574-3570-B241-252CCA0D21C6> /System/Library/Frameworks/PencilKit.framework/Versions/A/PencilKit
    0x7fff44811000 -     0x7fff44817ffa  com.apple.PushKit (1.0 - 1) <8946C7FD-4A69-3DA9-BBFB-1551B1337573> /System/Library/Frameworks/PushKit.framework/Versions/A/PushKit
    0x7fff44938000 -     0x7fff44b7fff6  com.apple.imageKit (3.0 - 1080) <ED29D27A-B76B-3507-A0E9-C32C265BA0C7> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/ImageKit.framework/Versions/A/ImageKit
    0x7fff44b80000 -     0x7fff45041ff7  com.apple.QuartzComposer (5.1 - 377) <2D676C09-9B93-3570-A973-51F88504C44F> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzComposer.framework/Versions/A/QuartzComposer
    0x7fff45042000 -     0x7fff45067ffc  com.apple.quartzfilters (1.10.0 - Tag) <0D03F25B-07A5-31F1-9A70-CE33E69CB4CF> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuartzFilters.framework/Versions/A/QuartzFilters
    0x7fff45068000 -     0x7fff45172ffe  com.apple.QuickLookUIFramework (5.0 - 905.1) <12339FDE-68C0-3C1C-B36A-0EAAD5A488F9> /System/Library/Frameworks/Quartz.framework/Versions/A/Frameworks/QuickLookUI.framework/Versions/A/QuickLookUI
    0x7fff45173000 -     0x7fff45173fff  com.apple.quartzframework (1.5 - 23) <7BAF742D-822E-3047-BE57-9DD6EFCF8924> /System/Library/Frameworks/Quartz.framework/Versions/A/Quartz
    0x7fff45174000 -     0x7fff453f2ff0  com.apple.QuartzCore (1.11 - 815.19.4.2) <5F492A40-BBBC-3A31-83A8-32462A7B1FB4> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff453f3000 -     0x7fff4544cff3  com.apple.QuickLookFramework (5.0 - 905.1) <53640506-3F38-3016-8E23-EC275B37CB22> /System/Library/Frameworks/QuickLook.framework/Versions/A/QuickLook
    0x7fff4544d000 -     0x7fff45481ff5  com.apple.QuickLookThumbnailing (1.0 - 1) <622F2373-E659-399F-A804-1D80BF1125B0> /System/Library/Frameworks/QuickLookThumbnailing.framework/Versions/A/QuickLookThumbnailing
    0x7fff4591d000 -     0x7fff45935fff  com.apple.SafariServices.framework (15608 - 15608.3.10.1.4) <7E93EF33-52B8-3212-992F-EFCBEA12F377> /System/Library/Frameworks/SafariServices.framework/Versions/A/SafariServices
    0x7fff45f26000 -     0x7fff45f3effd  com.apple.ScriptingBridge (1.4 - 79) <94588FFC-3A8C-34F9-B196-CCFF6B77F4AB> /System/Library/Frameworks/ScriptingBridge.framework/Versions/A/ScriptingBridge
    0x7fff45f3f000 -     0x7fff46285ff6  com.apple.security (7.0 - 59306.41.2) <FB3774D5-C940-35FB-960A-86253A01BDAE> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff46286000 -     0x7fff4630eff7  com.apple.securityfoundation (6.0 - 55236) <6482C994-4DB4-320D-8FD4-50C998EA8856> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff4630f000 -     0x7fff4633cfff  com.apple.securityinterface (10.0 - 55139.0.1) <CC270134-36F2-3FBF-A087-F4FFC6B65D05> /System/Library/Frameworks/SecurityInterface.framework/Versions/A/SecurityInterface
    0x7fff46368000 -     0x7fff4636cff8  com.apple.xpc.ServiceManagement (1.0 - 1) <2B80E13A-AFFC-355A-AA82-CCDEF4718E66> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff470f9000 -     0x7fff47163ff7  com.apple.SystemConfiguration (1.19 - 1.19) <A52A533D-DA25-3607-A18E-CA7C539E1C52> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff473df000 -     0x7fff47739ff4  com.apple.VideoToolbox (1.0 - 2510.17.4.6) <D8DDFD1A-003E-399A-9469-E6E55551726D> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff479dc000 -     0x7fff480e4ff6  libwebrtc.dylib (7608.3.10.1.4) <34C65BA0-76E5-3B29-97BA-C44E84CC45D7> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libwebrtc.dylib
    0x7fff480e5000 -     0x7fff4a288ff8  com.apple.WebCore (15608 - 15608.3.10.1.4) <76C41F28-1862-34DA-804B-1A9DDCF557BA> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/WebCore
    0x7fff4a289000 -     0x7fff4a482ff3  com.apple.WebKitLegacy (15608 - 15608.3.10.1.4) <23E4FF3A-B3F6-3367-BCAF-56B467C9FF32> /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebKitLegacy.framework/Versions/A/WebKitLegacy
    0x7fff4a483000 -     0x7fff4ab1eff2  com.apple.WebKit (15608 - 15608.3.10.1.4) <37C34BB7-F23E-3D1B-B36B-F5A28925E777> /System/Library/Frameworks/WebKit.framework/Versions/A/WebKit
    0x7fff4aebf000 -     0x7fff4af83fef  com.apple.APFS (1412.41.1 - 1412.41.1) <0319F563-43AE-3F80-9107-7F0056E726DB> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff4b5b3000 -     0x7fff4b5beff9  com.apple.accessibility.AXCoreUtilities (1.0 - 1) <F9138D1F-8953-3F86-B59C-2583705ABEFC> /System/Library/PrivateFrameworks/AXCoreUtilities.framework/Versions/A/AXCoreUtilities
    0x7fff4b8a5000 -     0x7fff4b951ff5  com.apple.accounts.AccountsDaemon (113 - 113) <1A714C39-7BED-3071-8602-0088127ACA0F> /System/Library/PrivateFrameworks/AccountsDaemon.framework/Versions/A/AccountsDaemon
    0x7fff4beec000 -     0x7fff4c043ff2  com.apple.AddressBook.core (1.0 - 1) <5EAF64DA-595B-3A42-B5A8-9F2C2D3D6597> /System/Library/PrivateFrameworks/AddressBookCore.framework/Versions/A/AddressBookCore
    0x7fff4c05f000 -     0x7fff4c060ff1  com.apple.AggregateDictionary (1.0 - 1) <93D38CEB-C8F2-3011-8810-64D1E33B0D62> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff4c422000 -     0x7fff4c56fff5  com.apple.AnnotationKit (1.0 - 325) <652D2F61-D477-345A-BA7A-AEEC8C5A53C3> /System/Library/PrivateFrameworks/AnnotationKit.framework/Versions/A/AnnotationKit
    0x7fff4c570000 -     0x7fff4c58dffc  com.apple.AppContainer (4.0 - 448.40.2) <1A1D23EF-A9CA-3D46-ABAC-E87628E3DF26> /System/Library/PrivateFrameworks/AppContainer.framework/Versions/A/AppContainer
    0x7fff4c5af000 -     0x7fff4c5c5ff6  com.apple.AppSSOCore (1.0 - 1) <0EC1D344-A2EB-33A7-86F6-A562B19E3D98> /System/Library/PrivateFrameworks/AppSSOCore.framework/Versions/A/AppSSOCore
    0x7fff4c5e2000 -     0x7fff4c5f0ff7  com.apple.AppSandbox (4.0 - 448.40.2) <19B46F6D-3F13-3679-81E0-C626E7E9749D> /System/Library/PrivateFrameworks/AppSandbox.framework/Versions/A/AppSandbox
    0x7fff4c9e5000 -     0x7fff4ca4bff7  com.apple.AppSupport (1.0.0 - 29) <275D79F2-561E-368E-BD77-C1D5CB2DA6B4> /System/Library/PrivateFrameworks/AppSupport.framework/Versions/A/AppSupport
    0x7fff4ca77000 -     0x7fff4ca9bff3  com.apple.framework.Apple80211 (13.0 - 1460.1) <5290ABDC-D781-31CF-AD23-C39D3BA3FBD6> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff4ca9c000 -     0x7fff4cbcfff6  com.apple.AppleAccount (1.0 - 1.0) <C7877817-D10B-303F-823A-16628EAD69A3> /System/Library/PrivateFrameworks/AppleAccount.framework/Versions/A/AppleAccount
    0x7fff4cbd1000 -     0x7fff4cbe0fdf  com.apple.AppleFSCompression (119 - 1.0) <7EEDBF8A-8812-33D6-A5B0-F7D36825EE73> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff4cbe1000 -     0x7fff4ccc9ff1  com.apple.AppleGVAFramework (73 - 73) <7F7C6B3E-E401-38A1-9E3E-C51B61B5E3A6> /System/Library/PrivateFrameworks/AppleGVA.framework/Versions/A/AppleGVA
    0x7fff4ccdf000 -     0x7fff4cceaff7  com.apple.AppleIDAuthSupport (1.0 - 1) <B84D3BAB-BCF7-3DD8-A656-498D5444DC9D> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff4cceb000 -     0x7fff4cd2bff6  com.apple.AppleIDSSOAuthentication (1.0 - 1) <914DE180-C948-37AD-AFBB-F6A0B5D37B0D> /System/Library/PrivateFrameworks/AppleIDSSOAuthentication.framework/Versions/A/AppleIDSSOAuthentication
    0x7fff4cd2c000 -     0x7fff4cd74fff  com.apple.AppleJPEG (1.0 - 1) <CFE57DD6-F663-3DBF-8D37-BEFABF557D1F> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff4cd75000 -     0x7fff4cd85ff7  com.apple.AppleLDAP (10.15 - 52) <0515DEF9-5365-3C7E-970B-068EC4894EA5> /System/Library/PrivateFrameworks/AppleLDAP.framework/Versions/A/AppleLDAP
    0x7fff4d127000 -     0x7fff4d14cff3  com.apple.aps.framework (4.0 - 4.0) <A6FDA31A-83D5-3215-A2C5-09F51841E122> /System/Library/PrivateFrameworks/ApplePushService.framework/Versions/A/ApplePushService
    0x7fff4d14d000 -     0x7fff4d151ff7  com.apple.AppleSRP (5.0 - 1) <77EB08CE-419B-38D5-9160-C1D4D3EE5131> /System/Library/PrivateFrameworks/AppleSRP.framework/Versions/A/AppleSRP
    0x7fff4d152000 -     0x7fff4d174ffb  com.apple.applesauce (1.0 - 16.22) <EFF69698-9566-3957-B3F5-CEC2B206EE7C> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff4d234000 -     0x7fff4d237ffb  com.apple.AppleSystemInfo (3.1.5 - 3.1.5) <F4F1A097-C691-38BC-B91B-FFD828C3EA4E> /System/Library/PrivateFrameworks/AppleSystemInfo.framework/Versions/A/AppleSystemInfo
    0x7fff4d238000 -     0x7fff4d288ff7  com.apple.AppleVAFramework (6.1.2 - 6.1.2) <C380FF1E-965E-3F05-BDCF-BB9EAC7F7B74> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff4d2d1000 -     0x7fff4d2e0ff1  com.apple.AssertionServices (1.0 - 223.40.19) <73B5C0D9-AB04-3961-A01D-FFBC94D1348E> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff4d81c000 -     0x7fff4dc1aff4  com.apple.audio.AudioResourceArbitration (1.0 - 1) <D51DC94A-FFDE-3B61-8E71-A05298853297> /System/Library/PrivateFrameworks/AudioResourceArbitration.framework/Versions/A/AudioResourceArbitration
    0x7fff4dd59000 -     0x7fff4ddaaffd  com.apple.audio.AudioSession (1.0 - 17) <95ED0F4C-FE5E-3401-82CC-3ADC19120CE8> /System/Library/PrivateFrameworks/AudioSession.framework/Versions/A/AudioSession
    0x7fff4ddab000 -     0x7fff4ddd8ff7  libSessionUtility.dylib (17) <B39432B4-506A-3FBE-A512-8E4780CD9A03> /System/Library/PrivateFrameworks/AudioSession.framework/libSessionUtility.dylib
    0x7fff4de71000 -     0x7fff4e0aefff  com.apple.audio.AudioToolboxCore (1.0 - 1104.26) <9D7C2174-0854-3C13-AF80-E814A9EC013C> /System/Library/PrivateFrameworks/AudioToolboxCore.framework/Versions/A/AudioToolboxCore
    0x7fff4e0af000 -     0x7fff4e1c8ff0  com.apple.AuthKit (1.0 - 1) <F190E8C4-1D9B-34F2-9255-902509534E6A> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff4e383000 -     0x7fff4e38cff3  com.apple.coreservices.BackgroundTaskManagement (1.0 - 104) <5E2B9000-49D6-3BFA-97F1-3B47A8A7418D> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff4e38d000 -     0x7fff4e42eff8  com.apple.backup.framework (1.11.1 - 1298.1.2) <3C069796-5360-32F6-8841-BC263B94B2A3> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff4e42f000 -     0x7fff4e4b0ffd  com.apple.BaseBoard (464.1 - 464.1) <1A44B522-904F-3541-BC8C-5EDF0C6EE49C> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff4e5b2000 -     0x7fff4e5eeff7  com.apple.bom (14.0 - 219.1) <4D4C4ACA-A1DD-3D0B-B362-8D202EBE8D9B> /System/Library/PrivateFrameworks/Bom.framework/Versions/A/Bom
    0x7fff4e70c000 -     0x7fff4e743ff1  com.apple.C2 (1.3 - 487) <F96E736F-7E88-3895-9517-AD2DC998F0A3> /System/Library/PrivateFrameworks/C2.framework/Versions/A/C2
    0x7fff4e862000 -     0x7fff4e8bcff6  com.apple.CalDAV (8.0 - 790.2.2) <B48583C0-DF79-3EC0-A7F3-43C90FF87986> /System/Library/PrivateFrameworks/CalDAV.framework/Versions/A/CalDAV
    0x7fff4ea6c000 -     0x7fff4ea97fff  com.apple.CalendarAgentLink (8.0 - 250) <A4899625-38D1-3355-9281-C48F2FB21490> /System/Library/PrivateFrameworks/CalendarAgentLink.framework/Versions/A/CalendarAgentLink
    0x7fff4eab0000 -     0x7fff4eb28ff0  com.apple.CalendarFoundation (8.0 - 1140.2.3) <A9BC0999-4320-3169-A467-2ABCAB4EC8F9> /System/Library/PrivateFrameworks/CalendarFoundation.framework/Versions/A/CalendarFoundation
    0x7fff4eb5f000 -     0x7fff4ee59ff9  com.apple.CalendarPersistence (8.0 - 1040.2.2) <1C2CDF6E-43B9-3E5D-8D5F-D50400C56FCD> /System/Library/PrivateFrameworks/CalendarPersistence.framework/Versions/A/CalendarPersistence
    0x7fff4f163000 -     0x7fff4f1b2fff  com.apple.ChunkingLibrary (302 - 302) <593921FE-7EFE-36F6-8B05-4E89B00EABD6> /System/Library/PrivateFrameworks/ChunkingLibrary.framework/Versions/A/ChunkingLibrary
    0x7fff4f1b3000 -     0x7fff4f209ff3  com.apple.ClassKit (1.2 - 145.1.22) <AC780D8D-B00D-3F30-A8BF-415042F471BC> /System/Library/PrivateFrameworks/ClassKit.framework/Versions/A/ClassKit
    0x7fff4f2e1000 -     0x7fff4f36bff3  com.apple.CloudDocs (1.0 - 681) <BC8D1A81-55F1-3236-BD13-5A01AC27CD68> /System/Library/PrivateFrameworks/CloudDocs.framework/Versions/A/CloudDocs
    0x7fff5003b000 -     0x7fff5004cfff  com.apple.CommonAuth (4.0 - 2.0) <1D04F654-22B1-37EF-90AD-3ADB5238806A> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff50060000 -     0x7fff50077fff  com.apple.commonutilities (8.0 - 900) <0B13423D-84E7-394A-8E2A-62D815B5BC4B> /System/Library/PrivateFrameworks/CommonUtilities.framework/Versions/A/CommonUtilities
    0x7fff5030f000 -     0x7fff5034affe  com.apple.contacts.ContactsAutocomplete (1.0 - 1136) <3D21AF9B-81C7-3BDC-AFD9-004F4780C4A0> /System/Library/PrivateFrameworks/ContactsAutocomplete.framework/Versions/A/ContactsAutocomplete
    0x7fff5037b000 -     0x7fff503feff0  com.apple.AddressBook.ContactsFoundation (8.0 - ???) <AD51E6E6-0601-3F72-84FF-6FD73F606E54> /System/Library/PrivateFrameworks/ContactsFoundation.framework/Versions/A/ContactsFoundation
    0x7fff503ff000 -     0x7fff5042cffe  com.apple.contacts.ContactsPersistence (1.0 - ???) <70E2EC97-3A38-3E59-B732-C6F961BDAF8B> /System/Library/PrivateFrameworks/ContactsPersistence.framework/Versions/A/ContactsPersistence
    0x7fff50770000 -     0x7fff50b45fc8  com.apple.CoreAUC (283.0.0 - 283.0.0) <505292C7-A6F0-392F-A94D-03D74F61F717> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff50b46000 -     0x7fff50b74ffb  com.apple.CoreAVCHD (6.1.0 - 6100.4.1) <BB2011D9-77DB-3C50-9228-C0A7B3880821> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff50b97000 -     0x7fff50bb6ff4  com.apple.analyticsd (1.0 - 1) <CFAD97DE-F4F0-3A1B-B6FE-855164CC68CC> /System/Library/PrivateFrameworks/CoreAnalytics.framework/Versions/A/CoreAnalytics
    0x7fff50cb5000 -     0x7fff50d26ff6  com.apple.corebrightness (1.0 - 1) <C1725CD4-5C4F-313E-B9DD-43DB05113416> /System/Library/PrivateFrameworks/CoreBrightness.framework/Versions/A/CoreBrightness
    0x7fff50def000 -     0x7fff50e80ff0  com.apple.coredav (1.0.1 - 870.2.2) <946994C1-96F1-328D-A5E5-90FC99274BDE> /System/Library/PrivateFrameworks/CoreDAV.framework/Versions/A/CoreDAV
    0x7fff50e81000 -     0x7fff50e8cff7  com.apple.frameworks.CoreDaemon (1.3 - 1.3) <E382C414-45C5-370B-A011-ED8FFCE8737D> /System/Library/PrivateFrameworks/CoreDaemon.framework/Versions/B/CoreDaemon
    0x7fff50e8d000 -     0x7fff5108fff2  com.apple.CoreDuet (1.0 - 1) <88D7D8FA-8936-392E-AD40-07E758C04256> /System/Library/PrivateFrameworks/CoreDuet.framework/Versions/A/CoreDuet
    0x7fff51090000 -     0x7fff510ddff4  com.apple.coreduetcontext (1.0 - 1) <A04DE547-1419-3A28-A6FD-4ACFA1FE426F> /System/Library/PrivateFrameworks/CoreDuetContext.framework/Versions/A/CoreDuetContext
    0x7fff510de000 -     0x7fff510eeffe  com.apple.CoreDuetDaemonProtocol (1.0 - 1) <A3BF0B6E-77E6-3126-A659-8B07A03808F4> /System/Library/PrivateFrameworks/CoreDuetDaemonProtocol.framework/Versions/A/CoreDuetDaemonProtocol
    0x7fff510f1000 -     0x7fff510f3fff  com.apple.CoreDuetDebugLogging (1.0 - 1) <FFFFA1F7-88AA-3F4B-B32A-FE971ADAB841> /System/Library/PrivateFrameworks/CoreDuetDebugLogging.framework/Versions/A/CoreDuetDebugLogging
    0x7fff51104000 -     0x7fff51114ff3  com.apple.CoreEmoji (1.0 - 107) <8D1CA277-C4F7-3F3B-919E-73B68D39535E> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff512c2000 -     0x7fff5140efff  com.apple.CoreHandwriting (161 - 1.2) <0EB567E1-C4F4-3976-9DB9-BEF7F92D3C89> /System/Library/PrivateFrameworks/CoreHandwriting.framework/Versions/A/CoreHandwriting
    0x7fff51765000 -     0x7fff517cfff8  com.apple.CoreNLP (1.0 - 213) <329A9840-CBD8-33A2-A584-2805042284A9> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff51acf000 -     0x7fff51ad3fff  com.apple.CoreOptimization (1.0 - 1) <80C75A46-E0FC-3E28-85E1-FC43404214B5> /System/Library/PrivateFrameworks/CoreOptimization.framework/Versions/A/CoreOptimization
    0x7fff51ad4000 -     0x7fff51b5dffa  com.apple.CorePDF (4.0 - 518.4.1) <D3831A20-C85E-3D51-80C5-DFC1157C4DD0> /System/Library/PrivateFrameworks/CorePDF.framework/Versions/A/CorePDF
    0x7fff51c3e000 -     0x7fff51c46ff8  com.apple.CorePhoneNumbers (1.0 - 1) <D4405704-6DD4-3486-9DE4-80FC91F1F80B> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff51c47000 -     0x7fff51c9994b  com.apple.CorePrediction (1.0 - 1) <4E6EB3F2-C3D2-32EC-8713-6CF6C7235BA8> /System/Library/PrivateFrameworks/CorePrediction.framework/Versions/A/CorePrediction
    0x7fff522b8000 -     0x7fff522c3ff4  com.apple.corerecents (1.0 - 1) <22BD94FB-BB37-34C6-B1A7-1227B8CCC4B7> /System/Library/PrivateFrameworks/CoreRecents.framework/Versions/A/CoreRecents
    0x7fff52392000 -     0x7fff523b5fff  com.apple.CoreSVG (1.0 - 129) <00FDBCD4-A7CC-3E32-AC10-878B6A74596F> /System/Library/PrivateFrameworks/CoreSVG.framework/Versions/A/CoreSVG
    0x7fff523b6000 -     0x7fff523e9fff  com.apple.CoreServicesInternal (446.4 - 446.4) <E9CE4776-4375-384B-B4A8-D0BF1D5BBFA4> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff523ea000 -     0x7fff52418ff7  com.apple.CSStore (1069.11 - 1069.11) <792520D2-5D81-3867-8DC7-75F8205D5A5B> /System/Library/PrivateFrameworks/CoreServicesStore.framework/Versions/A/CoreServicesStore
    0x7fff52585000 -     0x7fff52629ff6  com.apple.CoreSuggestions (1.0 - 1052.14) <F5239315-3396-3DA0-8C62-4EC14F8ADA99> /System/Library/PrivateFrameworks/CoreSuggestions.framework/Versions/A/CoreSuggestions
    0x7fff52919000 -     0x7fff529a0fff  com.apple.CoreSymbolication (11.0 - 64509.98.1) <F0A1415B-068A-3CE6-9AB3-B11EF978B58A> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff52a38000 -     0x7fff52b64ffc  com.apple.coreui (2.1 - 607) <5FB17928-EB0D-3C46-B078-7B9621261385> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff52b65000 -     0x7fff52d00ffe  com.apple.CoreUtils (6.1 - 610.14) <62284EE1-1F77-3487-8DD0-43BDCFFD27D2> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff52e35000 -     0x7fff52e48ff1  com.apple.CrashReporterSupport (10.13 - 15011) <E4E96CDA-DFC4-3096-BCFC-994DB61D3E4D> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff530b4000 -     0x7fff530c6ff0  com.apple.framework.DFRFoundation (1.0 - 252) <A7A09B8B-CEAD-3480-906E-9C3B685E6611> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff530c7000 -     0x7fff530ccfff  com.apple.DSExternalDisplay (3.1 - 380) <F34E4A29-FD30-3DD0-946E-0AEDAE04EB18> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff53135000 -     0x7fff531b0ff8  com.apple.datadetectorscore (8.0 - 659) <0E160ECD-98B5-3D9E-B155-0942A4B009A5> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff531b2000 -     0x7fff531fbff2  com.apple.DataDetectorsNaturalLanguage (1.0 - 154) <26B072AC-8F8D-356D-A743-233A841AE7C4> /System/Library/PrivateFrameworks/DataDetectorsNaturalLanguage.framework/Versions/A/DataDetectorsNaturalLanguage
    0x7fff531fc000 -     0x7fff5323aff0  com.apple.DebugSymbols (194 - 194) <FF16F79C-0D6B-32BF-B2DC-25BAF1E914C2> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff5323b000 -     0x7fff53396ff7  com.apple.desktopservices (1.14.1 - 1281.1.1) <44D9F114-0D09-331E-8CD2-3A191E5AE8E1> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff534d8000 -     0x7fff535a0ff6  com.apple.DiskImagesFramework (559.40.3 - 559.40.3) <E2E4EDD4-00DA-3002-81A4-258281876871> /System/Library/PrivateFrameworks/DiskImages.framework/Versions/A/DiskImages
    0x7fff535a1000 -     0x7fff53671ff6  com.apple.DiskManagement (13.0 - 1648.0.5) <ADE3EAEE-5EAF-359E-BD5F-B2C348C3EEB0> /System/Library/PrivateFrameworks/DiskManagement.framework/Versions/A/DiskManagement
    0x7fff53672000 -     0x7fff53676ff1  com.apple.DisplayServicesFW (3.1 - 380) <751C717D-BDD2-358B-9453-CACEBA38B421> /System/Library/PrivateFrameworks/DisplayServices.framework/Versions/A/DisplayServices
    0x7fff536cc000 -     0x7fff536f0ff1  com.apple.DuetActivityScheduler (1.0 - 1) <0D97B344-9B01-3D36-9AEC-395AE11413AE> /System/Library/PrivateFrameworks/DuetActivityScheduler.framework/Versions/A/DuetActivityScheduler
    0x7fff5371a000 -     0x7fff5374fff7  com.apple.SystemConfiguration.EAP8021X (14.0.0 - 14.0) <3810F65F-FA5C-3710-8F2D-5282DDC71636> /System/Library/PrivateFrameworks/EAP8021X.framework/Versions/A/EAP8021X
    0x7fff53750000 -     0x7fff53754ff9  com.apple.EFILogin (2.0 - 2) <A50E6356-A248-31DE-931C-F89ED4B22F38> /System/Library/PrivateFrameworks/EFILogin.framework/Versions/A/EFILogin
    0x7fff54264000 -     0x7fff5427aff8  com.apple.Engram (1.0 - 1) <935F3463-12D4-342D-B962-9DE4F7B3AB37> /System/Library/PrivateFrameworks/Engram.framework/Versions/A/Engram
    0x7fff5427b000 -     0x7fff548e6ff9  com.apple.vision.EspressoFramework (1.0 - 188.1.6) <532E3F4F-371A-3A96-B3B7-115156E39213> /System/Library/PrivateFrameworks/Espresso.framework/Versions/A/Espresso
    0x7fff54930000 -     0x7fff54989ff0  com.apple.ExchangeWebServices (8.0 - 802) <4E29C1A6-71BE-30C0-BB57-0EC519A6CAD9> /System/Library/PrivateFrameworks/ExchangeWebServices.framework/Versions/A/ExchangeWebServices
    0x7fff54bca000 -     0x7fff54fe5ff9  com.apple.vision.FaceCore (4.3.0 - 4.3.0) <9F0FB4FD-C77F-3494-9898-9709BA2F1315> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff5564b000 -     0x7fff55782ffc  libFontParser.dylib (277.2.1.2) <92F025B1-AEE5-3BF8-8515-24FAF66AD7C2> /System/Library/PrivateFrameworks/FontServices.framework/libFontParser.dylib
    0x7fff55783000 -     0x7fff557b7fff  libTrueTypeScaler.dylib (277.2.1.2) <AD3D80AD-FF50-3652-B42B-A26030249CDF> /System/Library/PrivateFrameworks/FontServices.framework/libTrueTypeScaler.dylib
    0x7fff5581c000 -     0x7fff5582cff6  libhvf.dylib (1.0 - $[CURRENT_PROJECT_VERSION]) <E7C8B563-8C55-30CC-AA12-EC9A6B1DAB1A> /System/Library/PrivateFrameworks/FontServices.framework/libhvf.dylib
    0x7fff58cf0000 -     0x7fff58cf1fff  libmetal_timestamp.dylib (902.11.1) <FA6BD306-D8F5-3F48-A98E-5BA327F3B679> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3902/Libraries/libmetal_timestamp.dylib
    0x7fff5a38c000 -     0x7fff5a397ff7  libGPUSupportMercury.dylib (17.10.22) <4FBD47A2-1E5F-3FAB-81E0-BCAF8E31A46A> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fff5a398000 -     0x7fff5a39efff  com.apple.GPUWrangler (4.5.9 - 4.5.9) <382B7462-5644-3C3E-968A-A5A9EBAFEECA> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff5a6b9000 -     0x7fff5a6dfffb  com.apple.GenerationalStorage (2.0 - 312) <C0B51C28-86E3-350E-BE7D-009032478C18> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff5a6f8000 -     0x7fff5b6cfffc  com.apple.GeoServices (1.0 - 1624.21.8.28.18) <2634B6F8-4114-3DA8-BB91-EB0860EB87BD> /System/Library/PrivateFrameworks/GeoServices.framework/Versions/A/GeoServices
    0x7fff5b7fd000 -     0x7fff5b80bffb  com.apple.GraphVisualizer (1.0 - 100.1) <415AAD69-0A45-3B21-9698-D8798A48E5A2> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff5b80c000 -     0x7fff5b819ff3  com.apple.GraphicsServices (1.0 - 1.0) <CF29B1DA-52DD-3FBC-8C1B-64993478B264> /System/Library/PrivateFrameworks/GraphicsServices.framework/Versions/A/GraphicsServices
    0x7fff5b870000 -     0x7fff5b87dff9  com.apple.HID (1.0 - 1) <C5B9ED5F-E349-3572-AA0A-D9AC236DE7D4> /System/Library/PrivateFrameworks/HID.framework/Versions/A/HID
    0x7fff5b99e000 -     0x7fff5ba5cff4  com.apple.Heimdal (4.0 - 2.0) <735D30D6-8713-382B-97EA-12EFCC053486> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff5d1b7000 -     0x7fff5d2b5ff1  com.apple.ids (10.0 - 1000) <C4FE4844-6A01-3993-A68D-14FA82AD65DC> /System/Library/PrivateFrameworks/IDS.framework/Versions/A/IDS
    0x7fff5d2b6000 -     0x7fff5d3f3ff8  com.apple.idsfoundation (10.0 - 1000) <010D2AAB-3265-3ED4-B79E-E83571CF0647> /System/Library/PrivateFrameworks/IDSFoundation.framework/Versions/A/IDSFoundation
    0x7fff5da08000 -     0x7fff5da67ffa  com.apple.imfoundation (10.0 - 1000) <0ED54BF3-FD8C-32E9-A8E8-5087AB372230> /System/Library/PrivateFrameworks/IMFoundation.framework/Versions/A/IMFoundation
    0x7fff5db89000 -     0x7fff5db92ffe  com.apple.IOAccelMemoryInfo (1.0 - 1) <8FCBD2DE-0094-3F8B-BB86-646646BA5D9C> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff5db93000 -     0x7fff5db9bff5  com.apple.IOAccelerator (438.2.7 - 438.2.7) <98C1C6DE-68A7-3396-B3D6-336CF11964AD> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff5db9e000 -     0x7fff5dbb4ff7  com.apple.IOPresentment (1.0 - 37) <E3AACF97-C85A-3720-90F0-61CAEF721F3D> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff5df3e000 -     0x7fff5df89ffc  com.apple.IconServices (438.2 - 438.2) <49E47D81-CBE8-3CB3-82F6-927B0AE64086> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff5e127000 -     0x7fff5e133ffa  com.apple.IntentsFoundation (1.0 - 1) <144BCC01-9AB2-308F-A40E-E5BA8394E794> /System/Library/PrivateFrameworks/IntentsFoundation.framework/Versions/A/IntentsFoundation
    0x7fff5e146000 -     0x7fff5e14cffc  com.apple.InternationalSupport (1.0 - 44) <E881A3F9-7D1E-3943-B8DB-7BF31057CBB6> /System/Library/PrivateFrameworks/InternationalSupport.framework/Versions/A/InternationalSupport
    0x7fff5e14d000 -     0x7fff5e14fffb  com.apple.InternationalTextSearch (1.0 - 1) <64947BC3-DE21-3220-AE94-436A86A5D083> /System/Library/PrivateFrameworks/InternationalTextSearch.framework/Versions/A/InternationalTextSearch
    0x7fff5e1b4000 -     0x7fff5e1e3fff  com.apple.IntlPreferences (2.0 - 301.4) <C0941FD7-1690-37CD-998E-03AA2B795650> /System/Library/PrivateFrameworks/IntlPreferences.framework/Versions/A/IntlPreferences
    0x7fff5e380000 -     0x7fff5e38cff7  com.apple.KerberosHelper (4.0 - 1.0) <0E1F7502-6AEB-33B9-B8AB-3B7F1C4A38C2> /System/Library/PrivateFrameworks/KerberosHelper.framework/Versions/A/KerberosHelper
    0x7fff5e38d000 -     0x7fff5e3adfff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <A6E97F92-DF9D-35F3-9DD8-2951FF162578> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff5e504000 -     0x7fff5e5d2ff5  com.apple.LanguageModeling (1.0 - 215) <D3478ED9-A757-355F-A4A0-464E133182D6> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff5e5d3000 -     0x7fff5e61bff7  com.apple.Lexicon-framework (1.0 - 72) <94910CCB-C386-3912-84A2-1A730BB6EF62> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff5e622000 -     0x7fff5e626ff6  com.apple.LinguisticData (1.0 - 353) <23AF4473-4FDB-39D9-8862-7D23276606A9> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff5e64d000 -     0x7fff5e671ffe  com.apple.locationsupport (2388.0.21 - 2388.0.21) <088A87C4-E61C-37C0-A030-D104940F043B> /System/Library/PrivateFrameworks/LocationSupport.framework/Versions/A/LocationSupport
    0x7fff5e6ca000 -     0x7fff5e6cfff7  com.apple.LoginUICore (4.0 - 4.0) <7E1FC261-596B-3EBF-8BA2-0E2D616C9103> /System/Library/PrivateFrameworks/LoginUIKit.framework/Versions/A/Frameworks/LoginUICore.framework/Versions/A/LoginUICore
    0x7fff5ee7c000 -     0x7fff5ee87ff7  com.apple.MallocStackLogging (1.0 - 1) <BD81C567-0D8C-36E6-9CD8-3DCDAB437CE9> /System/Library/PrivateFrameworks/MallocStackLogging.framework/Versions/A/MallocStackLogging
    0x7fff5eebe000 -     0x7fff5eec1fff  com.apple.Mangrove (1.0 - 25) <445D1183-447D-3F73-9532-11DAFF69F2A8> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff5f077000 -     0x7fff5f077ff5  com.apple.marco (10.0 - 1000) <0EA43E00-4C88-3A5C-A895-934DF9C5DDF9> /System/Library/PrivateFrameworks/Marco.framework/Versions/A/Marco
    0x7fff5f078000 -     0x7fff5f09effe  com.apple.MarkupUI (1.0 - 325) <A86C51C7-07CC-39A0-B341-3538F2C51BF6> /System/Library/PrivateFrameworks/MarkupUI.framework/Versions/A/MarkupUI
    0x7fff5f123000 -     0x7fff5f1adff0  com.apple.MediaExperience (1.0 - 1) <40A6CE90-66FA-341B-ABF9-5EE0FB506645> /System/Library/PrivateFrameworks/MediaExperience.framework/Versions/A/MediaExperience
    0x7fff5f1ae000 -     0x7fff5f1e1fff  com.apple.MediaKit (16 - 923) <F4E063D9-5302-3A54-A80E-721D2555E367> /System/Library/PrivateFrameworks/MediaKit.framework/Versions/A/MediaKit
    0x7fff5f2a6000 -     0x7fff5f62cff1  com.apple.MediaRemote (1.0 - 1) <E3A53F0F-2E66-3361-B750-C7ECECCC3E96> /System/Library/PrivateFrameworks/MediaRemote.framework/Versions/A/MediaRemote
    0x7fff5f62d000 -     0x7fff5f668ffc  com.apple.MediaServices (1.0 - 1) <4FF2CAE0-985D-3708-8ABA-915A4B4A3CF1> /System/Library/PrivateFrameworks/MediaServices.framework/Versions/A/MediaServices
    0x7fff5f977000 -     0x7fff5f9c3ff7  com.apple.spotlight.metadata.utilities (1.0 - 2074.4) <8957F147-9371-3728-896E-FC517AC7E86E> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff5f9c4000 -     0x7fff5fa92ffd  com.apple.gpusw.MetalTools (1.0 - 1) <494BAEE0-8742-31F9-BC6D-C947A2756C5F> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff5faec000 -     0x7fff5fb05ff8  com.apple.MobileAssets (1.0 - 619.40.6) <2DBD115A-ACC8-37D9-9F5E-DE2F8C9F5D09> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff5fcc2000 -     0x7fff5fce0fff  com.apple.MobileKeyBag (2.0 - 1.0) <C137BEF9-6103-3AA5-B4BB-25BFE550B473> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff5fdad000 -     0x7fff5ff46ff3  com.apple.Montreal (1.0 - 120.1) <36EB7D45-4E72-31B9-BEF7-E446A5C803BB> /System/Library/PrivateFrameworks/Montreal.framework/Versions/A/Montreal
    0x7fff5ff47000 -     0x7fff5ff75ff7  com.apple.MultitouchSupport.framework (3410.2 - 3410.2) <67076218-F639-3C44-9670-20B54714E339> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff6016b000 -     0x7fff60256ff6  com.apple.NLP (1.0 - 202) <DBA950DD-819B-39A8-9F95-15EB631CEA1E> /System/Library/PrivateFrameworks/NLP.framework/Versions/A/NLP
    0x7fff603ea000 -     0x7fff603f4fff  com.apple.NetAuth (6.2 - 6.2) <BA114B8C-BE33-3DBB-BDC8-25423DBBD3A3> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff60b65000 -     0x7fff60b67ffe  com.apple.OAuth (25 - 25) <0D3A2C8D-41BC-3813-AF59-B33F4A4B0F7D> /System/Library/PrivateFrameworks/OAuth.framework/Versions/A/OAuth
    0x7fff60de2000 -     0x7fff60e2eff7  com.apple.OTSVG (1.0 - 643.1.1.5) <239EB765-2776-30F4-A300-4DF12C987D0F> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff61fbd000 -     0x7fff61fc8ffe  com.apple.PerformanceAnalysis (1.243 - 243) <FCF592E9-A0C8-3E31-BC87-91AEE71C2869> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff61fc9000 -     0x7fff61ff1ffb  com.apple.persistentconnection (1.0 - 1.0) <E6842FE3-D767-3540-95D3-39A213B45BD7> /System/Library/PrivateFrameworks/PersistentConnection.framework/Versions/A/PersistentConnection
    0x7fff61ff2000 -     0x7fff62000ff2  com.apple.PersonaKit (1.0 - 1) <1FCFFFE1-13FB-3144-ABFE-2D0B6A18CA9C> /System/Library/PrivateFrameworks/PersonaKit.framework/Versions/A/PersonaKit
    0x7fff621aa000 -     0x7fff621aaffe  com.apple.PhoneNumbers (1.0 - 1) <DD1ADA26-B650-36C2-B85F-31414EE4AC0B> /System/Library/PrivateFrameworks/PhoneNumbers.framework/Versions/A/PhoneNumbers
    0x7fff639df000 -     0x7fff63a0fff9  com.apple.pluginkit.framework (1.0 - 1) <65278C57-5335-31D5-9F82-6F3DB478A5A2> /System/Library/PrivateFrameworks/PlugInKit.framework/Versions/A/PlugInKit
    0x7fff63a38000 -     0x7fff63a4bff0  com.apple.PowerLog (1.0 - 1) <C7526E78-CCEB-3178-B560-32E6315AC4D1> /System/Library/PrivateFrameworks/PowerLog.framework/Versions/A/PowerLog
    0x7fff646c5000 -     0x7fff646e5ff9  com.apple.proactive.support.ProactiveEventTracker (1.0 - 258.3) <A1C60CB5-1975-3EB0-9C7D-70EA65B20400> /System/Library/PrivateFrameworks/ProactiveEventTracker.framework/Versions/A/ProactiveEventTracker
    0x7fff64766000 -     0x7fff647cfffe  com.apple.proactive.support.ProactiveSupport (1.0 - 258.3) <A7F6CA89-0B93-389A-9C1B-187BC22A3E18> /System/Library/PrivateFrameworks/ProactiveSupport.framework/Versions/A/ProactiveSupport
    0x7fff648b6000 -     0x7fff64910fff  com.apple.ProtectedCloudStorage (1.0 - 1) <9B166C3E-ACED-3528-A68F-22491EE811BA> /System/Library/PrivateFrameworks/ProtectedCloudStorage.framework/Versions/A/ProtectedCloudStorage
    0x7fff64911000 -     0x7fff6492afff  com.apple.ProtocolBuffer (1 - 274.20.7.15.1) <89CB1292-0A41-3848-9AE1-CC5CEA756A25> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff64a36000 -     0x7fff64a39ff4  com.apple.QuickLookNonBaseSystem (1.0 - 1) <467F0F62-DEA3-30CB-98C2-78502069E81B> /System/Library/PrivateFrameworks/QuickLookNonBaseSystem.framework/Versions/A/QuickLookNonBaseSystem
    0x7fff64a3a000 -     0x7fff64a5dff3  com.apple.quicklook.QuickLookSupport (1.0 - 1) <0D811D46-9909-342A-B936-E837936DA069> /System/Library/PrivateFrameworks/QuickLookSupport.framework/Versions/A/QuickLookSupport
    0x7fff64aa4000 -     0x7fff64b1cff8  com.apple.Rapport (1.9 - 190.11) <D54D57D1-6CDC-3A24-A02D-77E87FFE92D0> /System/Library/PrivateFrameworks/Rapport.framework/Versions/A/Rapport
    0x7fff64d2f000 -     0x7fff64d58ff9  com.apple.RemoteViewServices (2.0 - 148) <D8DCE656-7CBF-381A-827A-B8AA2A34CC08> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff64ddb000 -     0x7fff64e26ff2  com.apple.ResponseKit (1.0 - 148) <90DECB43-ABEE-3F81-AA3A-F495FF904FD7> /System/Library/PrivateFrameworks/ResponseKit.framework/Versions/A/ResponseKit
    0x7fff64ebd000 -     0x7fff64ef8ff0  com.apple.RunningBoardServices (1.0 - 223.40.19) <30C89668-9DEE-3948-B4EA-6DC9099497C2> /System/Library/PrivateFrameworks/RunningBoardServices.framework/Versions/A/RunningBoardServices
    0x7fff65c72000 -     0x7fff65cbcfff  com.apple.Safari.SafeBrowsing (15608 - 15608.3.10.1.4) <0EAC823B-0A4F-3FFC-89B0-EF5B19B1E339> /System/Library/PrivateFrameworks/SafariSafeBrowsing.framework/Versions/A/SafariSafeBrowsing
    0x7fff6680c000 -     0x7fff6680fff1  com.apple.SecCodeWrapper (4.0 - 448.40.2) <C2138BC2-5F03-3E79-AC0C-F95F0BC9C0B3> /System/Library/PrivateFrameworks/SecCodeWrapper.framework/Versions/A/SecCodeWrapper
    0x7fff66957000 -     0x7fff66a7bff4  com.apple.Sharing (1496.4 - 1496.4) <509EE7C8-C096-372E-B1CC-1CBB7B59DFEF> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff66a9c000 -     0x7fff66abcff1  com.apple.sidecar-core (1.0 - 208) <3F9A3D2A-F7A6-3D85-845F-D6DDD8180514> /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
    0x7fff66abd000 -     0x7fff66acfff0  com.apple.sidecar-ui (1.0 - 208) <4F36ACD6-38D8-3F45-BCCA-932DBF2B2C48> /System/Library/PrivateFrameworks/SidecarUI.framework/Versions/A/SidecarUI
    0x7fff67aaf000 -     0x7fff67da7ffa  com.apple.SkyLight (1.600.0 - 440.14) <87B4BC36-78DA-3320-B455-FACB48DC63AA> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff685ef000 -     0x7fff685fdfff  com.apple.SpeechRecognitionCore (6.0.91 - 6.0.91) <6D164E0A-5C8D-3125-933F-F4842C731E01> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff686c0000 -     0x7fff6894affe  com.apple.spotlight.index (10.7.0 - 2074.4) <D5D50BCE-287B-3C95-8F7E-B85182D64A97> /System/Library/PrivateFrameworks/SpotlightIndex.framework/Versions/A/SpotlightIndex
    0x7fff68cce000 -     0x7fff68d0fff9  com.apple.StreamingZip (1.0 - 1) <A2156ED8-DD0F-3F42-851D-1EF9ECA6AE2B> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff68e20000 -     0x7fff68e29ff3  com.apple.SymptomDiagnosticReporter (1.0 - 1238.40.4) <FB255398-53B0-3462-8227-EBD173B5F93E> /System/Library/PrivateFrameworks/SymptomDiagnosticReporter.framework/Versions/A/SymptomDiagnosticReporter
    0x7fff68e9b000 -     0x7fff68ec5ff0  com.apple.framework.SystemAdministration (1.0 - 1.0) <37D8FA9B-7C69-30D4-A8E9-8973924733B0> /System/Library/PrivateFrameworks/SystemAdministration.framework/Versions/A/SystemAdministration
    0x7fff690de000 -     0x7fff690eeff3  com.apple.TCC (1.0 - 1) <87BE8D5C-5D35-3434-8BDF-1615349C7A21> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff695e0000 -     0x7fff696a7ff4  com.apple.TextureIO (3.10.9 - 3.10.9) <499A5034-C527-30AC-9580-912423C3C2D8> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff6972a000 -     0x7fff69745ff4  com.apple.ToneKit (1.0 - 1) <DC014CD1-D36C-3C61-B571-B64FFF0D32E2> /System/Library/PrivateFrameworks/ToneKit.framework/Versions/A/ToneKit
    0x7fff69746000 -     0x7fff69770ffc  com.apple.ToneLibrary (1.0 - 1) <1071517F-71C5-3F14-A1B8-6895800ECE7B> /System/Library/PrivateFrameworks/ToneLibrary.framework/Versions/A/ToneLibrary
    0x7fff69824000 -     0x7fff69825fff  com.apple.TrustEvaluationAgent (2.0 - 33) <4327B52D-2681-3195-B1F8-270D9137F932> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff6a4fe000 -     0x7fff6a757ffa  com.apple.UIFoundation (1.0 - 659.5) <99072103-6A73-3538-944A-5FD2AF709A78> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff6a7ea000 -     0x7fff6a7f0ff6  com.apple.URLFormatting (119 - 119.13) <7257AB76-1449-3649-86BA-4B7F56B59480> /System/Library/PrivateFrameworks/URLFormatting.framework/Versions/A/URLFormatting
    0x7fff6b348000 -     0x7fff6b368fff  com.apple.UserManagement (1.0 - 1) <CAD75201-57C8-338E-BE1B-5C5E2EEB9DAB> /System/Library/PrivateFrameworks/UserManagement.framework/Versions/A/UserManagement
    0x7fff6c11a000 -     0x7fff6c204ffe  com.apple.ViewBridge (462 - 462) <627E4CA4-2E4E-3CF7-8DBB-F09990DDF0FF> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff6c3a9000 -     0x7fff6c3aafff  com.apple.WatchdogClient.framework (1.0 - 67.40.1) <B1228D4E-50B5-3630-A7F4-5598651CE963> /System/Library/PrivateFrameworks/WatchdogClient.framework/Versions/A/WatchdogClient
    0x7fff6c573000 -     0x7fff6c573fff  com.apple.WebInspectorUI (15608 - 15608.3.10.1.4) <FAD34ABD-04C5-30F5-8784-1BD603755CD6> /System/Library/PrivateFrameworks/WebInspectorUI.framework/Versions/A/WebInspectorUI
    0x7fff6c71e000 -     0x7fff6c75aff3  libAWDSupport.dylib (949) <03EE06EA-AD89-3377-A027-F268F8E46B23> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupport.dylib
    0x7fff6c75b000 -     0x7fff6ca00ff2  libAWDSupportFramework.dylib (3210) <9D077F42-DA50-3358-96D8-0DBB80E14615> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libAWDSupportFramework.dylib
    0x7fff6ca01000 -     0x7fff6ca12ff7  libprotobuf-lite.dylib (3210) <DE3E8323-4F86-3293-A793-D3AA0ACA8804> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf-lite.dylib
    0x7fff6ca13000 -     0x7fff6ca6dff3  libprotobuf.dylib (3210) <E5FD19B6-6919-30D7-8C70-60D91FF87E10> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
    0x7fff6ca6e000 -     0x7fff6cab2ffe  com.apple.awd (1.0 - 949) <14BA32F0-A038-3720-83A6-176986C9B962> /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/WirelessDiagnostics
    0x7fff6cf81000 -     0x7fff6cf84ffe  com.apple.dt.XCTTargetBootstrap (1.0 - 15508) <BA4C9007-2C3E-33DE-B81C-608918D2FDF1> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff6cf8c000 -     0x7fff6cfe9ff8  com.apple.xquery (1.3.1 - 30) <A31D61D1-3A5D-3202-8508-4092F3A34689> /System/Library/PrivateFrameworks/XQuery.framework/Versions/A/XQuery
    0x7fff6cffd000 -     0x7fff6d00bffd  com.apple.audio.caulk (1.0 - 32.3) <089441BF-D7F6-388F-8D89-0262AB2EEA3F> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
    0x7fff6d1d0000 -     0x7fff6d205ff4  com.apple.iCalendar (7.0 - 810.2.2) <D1BC6DFA-3AF3-3E4E-AA8E-3957FC255A08> /System/Library/PrivateFrameworks/iCalendar.framework/Versions/A/iCalendar
    0x7fff6d34b000 -     0x7fff6d34dff3  com.apple.loginsupport (1.0 - 1) <FFE90A0A-BEBC-3032-9368-94C016BE0795> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff6d34e000 -     0x7fff6d361ffd  com.apple.login (3.0 - 3.0) <51B9680F-41CE-394E-A600-1B5B0EC8D52B> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff6d393000 -     0x7fff6d39fffd  com.apple.perfdata (1.0 - 51.40.3) <00815E30-3964-3DAA-8CD4-C94E4ECBC5F8> /System/Library/PrivateFrameworks/perfdata.framework/Versions/A/perfdata
    0x7fff6d3a0000 -     0x7fff6d3d1ff9  com.apple.contacts.vCard (1.0 - ???) <0E0A41EA-F99A-3E96-BF4B-4DDFAE4209AC> /System/Library/PrivateFrameworks/vCard.framework/Versions/A/vCard
    0x7fff6d419000 -     0x7fff6d427ff7  com.apple.zudp (1.0 - 1) <07DAF24A-EF62-3CD3-A8A3-88DF2588A8B4> /System/Library/PrivateFrameworks/zudp.framework/Versions/A/zudp
    0x7fff6d5ad000 -     0x7fff6d5c2ff6  libAccessibility.dylib (2771.18.2.4) <26E69EEB-BEBD-3411-956A-FF6F0C238937> /usr/lib/libAccessibility.dylib
    0x7fff6d673000 -     0x7fff6d67ffff  libAudioStatistics.dylib (1104.26) <26761E48-3286-3F62-BDCA-C093980DB412> /usr/lib/libAudioStatistics.dylib
    0x7fff6d680000 -     0x7fff6d6b5ff2  libAudioToolboxUtility.dylib (1104.26) <261CDFD3-BEFF-3BE8-9322-8A0F5282D4B9> /usr/lib/libAudioToolboxUtility.dylib
    0x7fff6d6bc000 -     0x7fff6d6f1ff7  libCRFSuite.dylib (48) <CDEA70A4-318B-3990-9AAE-1D7B18132760> /usr/lib/libCRFSuite.dylib
    0x7fff6d6f4000 -     0x7fff6d6feff3  libChineseTokenizer.dylib (34) <4D68248B-BD40-32E3-ABCA-CE23BCA0A6A4> /usr/lib/libChineseTokenizer.dylib
    0x7fff6d6ff000 -     0x7fff6d788fff  libCoreStorage.dylib (551) <440FD2FE-94FD-3456-898A-6420EAC5A71F> /usr/lib/libCoreStorage.dylib
    0x7fff6d78b000 -     0x7fff6d78dfff  libDiagnosticMessagesClient.dylib (112) <83F42398-DB41-3BB2-B8A1-10D78C4B5778> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff6d7d2000 -     0x7fff6d989ff3  libFosl_dynamic.dylib (100.4) <F5583DFD-E3A1-3D6A-8698-613F7FA119A0> /usr/lib/libFosl_dynamic.dylib
    0x7fff6d9b0000 -     0x7fff6d9b6ff3  libIOReport.dylib (54) <EC75DB3B-CFC4-3235-8C2F-CE3C29CA8CFE> /usr/lib/libIOReport.dylib
    0x7fff6da96000 -     0x7fff6da9dfff  libMatch.1.dylib (36) <D059FA22-1620-3A26-BF81-70EA469C97EB> /usr/lib/libMatch.1.dylib
    0x7fff6dacd000 -     0x7fff6daecfff  libMobileGestalt.dylib (826.40.7) <C9875B8D-F7C6-32F6-A94D-1F2CA20D00CE> /usr/lib/libMobileGestalt.dylib
    0x7fff6db61000 -     0x7fff6dc3eff7  libSMC.dylib (20) <EB67A1E2-9471-3406-846E-F5E68C9D9FCD> /usr/lib/libSMC.dylib
    0x7fff6dc53000 -     0x7fff6dc54ff3  libSystem.B.dylib (1281) <1DD1BCD2-2C85-3B81-8CAF-224FB042F441> /usr/lib/libSystem.B.dylib
    0x7fff6dc55000 -     0x7fff6dce3ffb  libTelephonyUtilDynamic.dylib (3851) <6ED64F20-2FEE-340B-9E7F-5E3A3AF93E93> /usr/lib/libTelephonyUtilDynamic.dylib
    0x7fff6dce4000 -     0x7fff6dce5fff  libThaiTokenizer.dylib (3) <22582C9C-3D32-3832-8925-813E4F2BA8DA> /usr/lib/libThaiTokenizer.dylib
    0x7fff6dcfd000 -     0x7fff6dd13fff  libapple_nghttp2.dylib (1.39.2) <9B990E6A-D9EB-3F2C-B7CA-085A47D4BC62> /usr/lib/libapple_nghttp2.dylib
    0x7fff6dd48000 -     0x7fff6ddbaff7  libarchive.2.dylib (72.40.2) <25C00824-621A-3FF1-9B6C-52999B6DDF4E> /usr/lib/libarchive.2.dylib
    0x7fff6ddbb000 -     0x7fff6de51fc5  libate.dylib (2.0.9) <53750831-1A8E-3AF3-A22D-53C08F9D7002> /usr/lib/libate.dylib
    0x7fff6de55000 -     0x7fff6de55ff3  libauto.dylib (187) <F4B3519A-A4FC-30E0-805C-70C99BA3FDDA> /usr/lib/libauto.dylib
    0x7fff6de56000 -     0x7fff6df12ff5  libboringssl.dylib (283.40.1) <12B83BB5-43F8-347C-93A9-13E624388DB5> /usr/lib/libboringssl.dylib
    0x7fff6df13000 -     0x7fff6df23fff  libbsm.0.dylib (60) <E57A0CC6-226D-3529-A23A-D5DD6674DB3E> /usr/lib/libbsm.0.dylib
    0x7fff6df24000 -     0x7fff6df30fff  libbz2.1.0.dylib (44) <F3D26C17-BC6E-3A83-A3BB-137343C87303> /usr/lib/libbz2.1.0.dylib
    0x7fff6df31000 -     0x7fff6df84fff  libc++.1.dylib (800.7) <1D42387D-206A-3F06-9B5F-705B83EAC295> /usr/lib/libc++.1.dylib
    0x7fff6df85000 -     0x7fff6df99fff  libc++abi.dylib (800.7) <D89ABFBF-3754-35AB-BAEE-FBF14857F79B> /usr/lib/libc++abi.dylib
    0x7fff6df9a000 -     0x7fff6df9affb  libcharset.1.dylib (59) <EC5B95D9-388B-3351-9192-CD6CDB8C3E0F> /usr/lib/libcharset.1.dylib
    0x7fff6df9b000 -     0x7fff6dfacffb  libcmph.dylib (8) <49C8E101-945E-369B-91D3-2129000DFF35> /usr/lib/libcmph.dylib
    0x7fff6dfad000 -     0x7fff6dfc4fe7  libcompression.dylib (87) <77B35FFD-CE66-3CCA-BEDD-9771D698CEE3> /usr/lib/libcompression.dylib
    0x7fff6e291000 -     0x7fff6e2a7fff  libcoretls.dylib (167) <4F054E37-783A-3FCD-B90B-23A0A83621D9> /usr/lib/libcoretls.dylib
    0x7fff6e2a8000 -     0x7fff6e2a9ffb  libcoretls_cfhelpers.dylib (167) <62E31BC8-A823-3816-B130-2BB550433203> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff6e44c000 -     0x7fff6e546fff  libcrypto.35.dylib (47.11.1) <BE850B43-B562-38AD-9A0B-EBDAD26B9875> /usr/lib/libcrypto.35.dylib
    0x7fff6e74d000 -     0x7fff6e851fe7  libcrypto.44.dylib (47.11.1) <7607262D-CEFA-3B52-A07E-7DC7904F9BD8> /usr/lib/libcrypto.44.dylib
    0x7fff6e854000 -     0x7fff6e85fff7  libcsfde.dylib (551) <0A7CE4E1-45F7-3C3E-A092-EAB17818F4A8> /usr/lib/libcsfde.dylib
    0x7fff6e867000 -     0x7fff6e8c6fff  libcups.2.dylib (483) <38F989F6-5143-3D01-9F41-3B34553B68F0> /usr/lib/libcups.2.dylib
    0x7fff6e8c8000 -     0x7fff6e92ffff  libcurl.4.dylib (118) <F75E40BA-8DA6-39E7-BDFE-C9F4823BF5E0> /usr/lib/libcurl.4.dylib
    0x7fff6e9d2000 -     0x7fff6e9d2ff3  libenergytrace.dylib (21) <1CE2BD78-F68E-36A3-BCE9-E9EAB78D9FF3> /usr/lib/libenergytrace.dylib
    0x7fff6e9d3000 -     0x7fff6e9ecff7  libexpat.1.dylib (19) <E209623A-A410-3749-AD6D-2850241CB873> /usr/lib/libexpat.1.dylib
    0x7fff6e9fa000 -     0x7fff6e9fcff7  libfakelink.dylib (149) <528A0ABE-B583-3DA1-8E5B-9CA7E89303DE> /usr/lib/libfakelink.dylib
    0x7fff6ea0b000 -     0x7fff6ea10fff  libgermantok.dylib (24) <5E297121-22A7-3A2F-92B9-DD3E5C829CC7> /usr/lib/libgermantok.dylib
    0x7fff6ea11000 -     0x7fff6ea1aff7  libheimdal-asn1.dylib (564.40.3) <6C5102F7-85BE-34E0-BFC7-0569FCAE2755> /usr/lib/libheimdal-asn1.dylib
    0x7fff6ea1b000 -     0x7fff6eb0bff7  libiconv.2.dylib (59) <EB71AC8F-EA44-3BEE-A210-2D92251CA51D> /usr/lib/libiconv.2.dylib
    0x7fff6eb0c000 -     0x7fff6ed64ff7  libicucore.A.dylib (64243.0.1) <4CBF52D7-7235-34C8-9FF1-8657076B604F> /usr/lib/libicucore.A.dylib
    0x7fff6ed7e000 -     0x7fff6ed7ffff  liblangid.dylib (133) <DCC4FA36-0563-3BD2-AE35-9BAF52F5BD98> /usr/lib/liblangid.dylib
    0x7fff6ed80000 -     0x7fff6ed98ffb  liblzma.5.dylib (16) <7D2522C8-8CBE-32C9-8743-A8F598602F4C> /usr/lib/liblzma.5.dylib
    0x7fff6edb0000 -     0x7fff6ee57fff  libmecab.dylib (883) <FDA0E623-F6F2-3402-B72C-0C60A32C2CC1> /usr/lib/libmecab.dylib
    0x7fff6ee58000 -     0x7fff6f0b8ff9  libmecabra.dylib (883) <2E84458F-5748-3A9B-94F3-CAF3C79E6383> /usr/lib/libmecabra.dylib
    0x7fff6f424000 -     0x7fff6f453ff7  libncurses.5.4.dylib (57) <7115BD9E-9A53-3538-BA7C-6D71E8C0F9F1> /usr/lib/libncurses.5.4.dylib
    0x7fff6f582000 -     0x7fff6f9f4ff4  libnetwork.dylib (1880.40.26) <D8C5B7F0-04D5-3470-A9C4-EF8B2FF96986> /usr/lib/libnetwork.dylib
    0x7fff6f9f5000 -     0x7fff6fa0bfff  libnetworkextension.dylib (1095.40.22) <3C100538-5C43-3857-A126-1878D5B8C89B> /usr/lib/libnetworkextension.dylib
    0x7fff6fa93000 -     0x7fff6fac4ff6  libobjc.A.dylib (781) <D866A31E-5CB1-3327-8D22-C4F83C9225D0> /usr/lib/libobjc.A.dylib
    0x7fff6fac5000 -     0x7fff6fac6ff7  libodfde.dylib (26) <104DFC2F-ACCF-321A-974D-734E19056B21> /usr/lib/libodfde.dylib
    0x7fff6fad7000 -     0x7fff6fadbfff  libpam.2.dylib (25) <02ABA04D-5843-3850-82A3-EBECA6FC2CDF> /usr/lib/libpam.2.dylib
    0x7fff6fade000 -     0x7fff6fb11ff7  libpcap.A.dylib (89.40.2) <C4F9F5BD-BA21-3038-9665-4D298FB7511C> /usr/lib/libpcap.A.dylib
    0x7fff6fb12000 -     0x7fff6fb4dfff  libpcre.0.dylib (11) <76FD8942-CF3A-3E1B-94AB-98452B748F69> /usr/lib/libpcre.0.dylib
    0x7fff6fb4f000 -     0x7fff6fb5dff9  libperfcheck.dylib (37) <975FBE7C-C399-3B64-AFF1-24B3B161F477> /usr/lib/libperfcheck.dylib
    0x7fff6fb93000 -     0x7fff6fbabfff  libresolv.9.dylib (67.40.1) <34848168-B77D-3749-A7ED-B1F3F92E5162> /usr/lib/libresolv.9.dylib
    0x7fff6fbad000 -     0x7fff6fbf1ff7  libsandbox.1.dylib (1217.41.1) <EAC4CA6F-6527-373C-8AD8-F8F1B590B54B> /usr/lib/libsandbox.1.dylib
    0x7fff6fbf2000 -     0x7fff6fc04fff  libsasl2.2.dylib (213) <FA0CF2A0-1989-3CCF-8118-45017132788B> /usr/lib/libsasl2.2.dylib
    0x7fff6fc05000 -     0x7fff6fc06ff7  libspindump.dylib (281.1) <D330C232-51A7-3943-87EB-FAEA3C9352DC> /usr/lib/libspindump.dylib
    0x7fff6fc07000 -     0x7fff6fdf4ff7  libsqlite3.dylib (308.4) <2D0B1BE5-9B8A-394F-82F7-F612B1A6C73F> /usr/lib/libsqlite3.dylib
    0x7fff6fee8000 -     0x7fff6ff15ffb  libssl.46.dylib (47.11.1) <37B2EA03-9748-3324-ADDD-75F67D1E9D15> /usr/lib/libssl.46.dylib
    0x7fff6ff18000 -     0x7fff6ff62ff7  libstdc++.6.dylib (104.1) <8D404CA3-0176-3BC6-88D4-C77A552FEC56> /usr/lib/libstdc++.6.dylib
    0x7fff6ff96000 -     0x7fff6ffc7fff  libtidy.A.dylib (17.1) <7B56511C-4F77-32D0-96CF-32833366EAF1> /usr/lib/libtidy.A.dylib
    0x7fff6ffe9000 -     0x7fff70044ff0  libusrtcp.dylib (1880.40.26) <9FE938A6-BC56-3245-87D6-88C3C7A1F81D> /usr/lib/libusrtcp.dylib
    0x7fff70045000 -     0x7fff70048ffb  libutil.dylib (57) <B88D4C21-DAEF-3566-8EAE-5973C51A16FD> /usr/lib/libutil.dylib
    0x7fff70049000 -     0x7fff70056fff  libxar.1.dylib (420) <46AAA43E-6FC6-38A8-B696-62143706D33B> /usr/lib/libxar.1.dylib
    0x7fff7005c000 -     0x7fff7013eff7  libxml2.2.dylib (32.12) <0DB777D9-F9A1-3921-BFCE-05A000293915> /usr/lib/libxml2.2.dylib
    0x7fff70142000 -     0x7fff7016afff  libxslt.1.dylib (16.7) <C30A840F-E7E7-39D5-A633-9C256650B552> /usr/lib/libxslt.1.dylib
    0x7fff7016b000 -     0x7fff7017dfff  libz.1.dylib (76) <3EC7A143-AF2D-35EE-9C08-542B2907E3D2> /usr/lib/libz.1.dylib
    0x7fff701a8000 -     0x7fff701aaff9  liblog_network.dylib (1880.40.26) <DA6411F8-CD4B-3D5F-B685-C796FAC87AA7> /usr/lib/log/liblog_network.dylib
    0x7fff70be3000 -     0x7fff70be8ff7  libcache.dylib (83) <74F6459D-3606-3ADB-9808-F6B0FE70062D> /usr/lib/system/libcache.dylib
    0x7fff70be9000 -     0x7fff70bf4ff7  libcommonCrypto.dylib (60165) <1333752F-5117-3E86-803A-06E166D80C8C> /usr/lib/system/libcommonCrypto.dylib
    0x7fff70bf5000 -     0x7fff70bfcfff  libcompiler_rt.dylib (101.2) <0437EBEF-8191-3912-A365-D6BB75C7A810> /usr/lib/system/libcompiler_rt.dylib
    0x7fff70bfd000 -     0x7fff70c06fff  libcopyfile.dylib (166.40.1) <7FAF372E-BAD5-30E6-A8F2-A3D06B91DC80> /usr/lib/system/libcopyfile.dylib
    0x7fff70c07000 -     0x7fff70c9efef  libcorecrypto.dylib (866.40.8) <AE25C9EE-5D63-3E49-B3AA-D482D35C085A> /usr/lib/system/libcorecrypto.dylib
    0x7fff70db5000 -     0x7fff70df6ff0  libdispatch.dylib (1173.40.5) <1FF421B6-4BF0-3B5F-8F56-5ED3B3EFE06F> /usr/lib/system/libdispatch.dylib
    0x7fff70df7000 -     0x7fff70e2cfff  libdyld.dylib (733.6) <2FA4B359-624B-337C-9207-CDCF841C2E52> /usr/lib/system/libdyld.dylib
    0x7fff70e2d000 -     0x7fff70e2dffb  libkeymgr.dylib (30) <7EEF9246-30B4-34DD-8AD6-79679D1A7784> /usr/lib/system/libkeymgr.dylib
    0x7fff70e2e000 -     0x7fff70e3aff7  libkxld.dylib (6153.41.3) <F9FF90CE-DCB0-3918-882F-6E475A6E244A> /usr/lib/system/libkxld.dylib
    0x7fff70e3b000 -     0x7fff70e3bff7  liblaunch.dylib (1738.40.10) <CC02D5B3-A95D-3B16-8EE5-D62521CFE899> /usr/lib/system/liblaunch.dylib
    0x7fff70e3c000 -     0x7fff70e41ff7  libmacho.dylib (949.0.1) <6C3E49B2-594D-3B9D-82DB-C4ABEB9788AB> /usr/lib/system/libmacho.dylib
    0x7fff70e42000 -     0x7fff70e44ff3  libquarantine.dylib (110.40.3) <A1BCAA32-A194-3DBE-9930-8F49A4AEF284> /usr/lib/system/libquarantine.dylib
    0x7fff70e45000 -     0x7fff70e46ff7  libremovefile.dylib (48) <DD7AE862-F179-3C07-A4FC-5775DDD4D3E6> /usr/lib/system/libremovefile.dylib
    0x7fff70e47000 -     0x7fff70e5efff  libsystem_asl.dylib (377.40.1) <ECE44856-D279-3B5D-A0AA-8BE421D200C4> /usr/lib/system/libsystem_asl.dylib
    0x7fff70e5f000 -     0x7fff70e5ffff  libsystem_blocks.dylib (74) <DC521115-905A-3A0D-9337-C55FACCEA85F> /usr/lib/system/libsystem_blocks.dylib
    0x7fff70e60000 -     0x7fff70ee7ff7  libsystem_c.dylib (1353.41.1) <5AD50779-955E-3F56-BCB9-1E14833B3455> /usr/lib/system/libsystem_c.dylib
    0x7fff70ee8000 -     0x7fff70eebfff  libsystem_configuration.dylib (1061.40.2) <7A2329E0-3C84-3DB7-BC32-E7796C50D621> /usr/lib/system/libsystem_configuration.dylib
    0x7fff70eec000 -     0x7fff70eefff7  libsystem_coreservices.dylib (114) <DF341577-A307-3722-BB24-D4AACEAB19B3> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff70ef0000 -     0x7fff70ef7fff  libsystem_darwin.dylib (1353.41.1) <E862B5B1-A367-39CA-8319-B2F9DFADF606> /usr/lib/system/libsystem_darwin.dylib
    0x7fff70ef8000 -     0x7fff70effffb  libsystem_dnssd.dylib (1096.40.7) <2A9C6F3E-427B-332E-BDD3-D4651306F3DE> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff70f00000 -     0x7fff70f01ffb  libsystem_featureflags.dylib (17) <B94C0052-B75A-3169-80AA-5F480588AF6E> /usr/lib/system/libsystem_featureflags.dylib
    0x7fff70f02000 -     0x7fff70f4fff7  libsystem_info.dylib (538) <18CC56C5-5325-3375-BF99-FAE7F4F19DDD> /usr/lib/system/libsystem_info.dylib
    0x7fff70f50000 -     0x7fff70f7cff7  libsystem_kernel.dylib (6153.41.3) <18918E9C-45BC-3D5A-A6B6-3DBC60EEE2E1> /usr/lib/system/libsystem_kernel.dylib
    0x7fff70f7d000 -     0x7fff70fc4ff7  libsystem_m.dylib (3178) <636A1A1C-7AFC-3E82-B86B-0173912A3437> /usr/lib/system/libsystem_m.dylib
    0x7fff70fc5000 -     0x7fff70fecff7  libsystem_malloc.dylib (283.40.1) <F82A587B-44A2-3699-A218-9D3ECEE23D5A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff70fed000 -     0x7fff70ffaff3  libsystem_networkextension.dylib (1095.40.22) <7F206A43-A941-3BAB-AE3A-16169F2FE6AB> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff70ffb000 -     0x7fff71004fff  libsystem_notify.dylib (241) <C95CC58E-35E7-3828-AA2A-6EED73C12DE5> /usr/lib/system/libsystem_notify.dylib
    0x7fff71005000 -     0x7fff7100efe7  libsystem_platform.dylib (220) <0CCDD81F-0891-3400-8A97-6CAC3BBBE2F9> /usr/lib/system/libsystem_platform.dylib
    0x7fff7100f000 -     0x7fff71019ff7  libsystem_pthread.dylib (416.40.3) <53C65598-9E9E-36FF-BDC2-74F228E58C5C> /usr/lib/system/libsystem_pthread.dylib
    0x7fff7101a000 -     0x7fff7101effb  libsystem_sandbox.dylib (1217.41.1) <2183D15E-2CFD-3160-80CE-A948F0529005> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7101f000 -     0x7fff71021fff  libsystem_secinit.dylib (62.40.2) <D2782294-ACDC-30FF-A794-B4C1B324526B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff71022000 -     0x7fff71029ffb  libsystem_symptoms.dylib (1238.40.4) <A44E4405-E22E-32E9-83DE-8C7A82401DA0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff7102a000 -     0x7fff71040ff2  libsystem_trace.dylib (1147.40.13) <376CC435-E656-37D9-A5FF-C49B6E4525E2> /usr/lib/system/libsystem_trace.dylib
    0x7fff71042000 -     0x7fff71047ffb  libunwind.dylib (35.4) <44448F1F-08E5-3425-ADBA-C38A9E8F90C7> /usr/lib/system/libunwind.dylib
    0x7fff71048000 -     0x7fff7107cff6  libxpc.dylib (1738.40.10) <99CC9436-D653-3762-ADBB-9054EBD1BA2B> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 466
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1663280
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=953.9M resident=0K(0%) swapped_out_or_unallocated=953.9M(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
CG backing stores                 13.7M        4 
CG image                           288K        4 
CoreAnimation                      136K        7 
CoreGraphics                         8K        1 
CoreImage                           24K        2 
CoreUI image data                  256K        3 
Foundation                          28K        2 
Kernel Alloc Once                    8K        1 
MALLOC                             1.0G      473 
MALLOC guard page                   48K       11 
MALLOC_LARGE (reserved)           6776K       10         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
Memory Tag 242                      12K        1 
OpenGL GLSL                        256K        3 
PROTECTED_MEMORY                     4K        1 
SQLite page cache                   64K        1 
STACK GUARD                       56.2M       46 
Stack                             33.4M       54 
VM_ALLOCATE                       5328K       54 
__DATA                            96.8M      680 
__DATA_CONST                       321K       11 
__FONT_DATA                          4K        1 
__GLSLBUILTINS                    5176K        1 
__LINKEDIT                       369.6M      190 
__OBJC_RO                         32.0M        1 
__OBJC_RW                         1780K        2 
__TEXT                           584.3M      639 
__UNICODE                          564K        1 
libnetwork                         128K        8 
mapped file                       72.4M       40 
shared memory                      648K       17 
===========                     =======  ======= 
TOTAL                              2.6G     2271 
TOTAL, minus reserved VM space     2.2G     2271 
```

### PR DESCRIPTION
**Pull request by jpark37**
### Description
Use autoreleasepool for graphics thread.

### Motivation and Context
Apparently necessary to clean up macOS leaks.

Fixes #2293

### How Has This Been Tested?
OBS still works on Mac and Windows. Used _CFAutoreleasePoolPrintPools() in debugger to verify leaky behavior before change, and good behavior after change. Not quite guaranteed to fix original issue, but hopefully it does.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: libobs/obs-cocoa.m [hunk 1]
```diff
@@ -1804,3 +1804,17 @@ bool obs_hotkeys_platform_is_pressed(obs_hotkeys_platform_t *plat,
...
+		return obs_graphics_thread(param);
+	}
+}
+
+bool obs_graphics_thread_loop_mac(struct obs_graphics_context *context)
+{
+	@autoreleasepool {
+		return obs_graphics_thread_loop(context);
+	}
+}
```
Comment (torarnv) [inline libobs/obs-cocoa.m:1820]: I don't know how OBS calls these, but the pool needs to be part of the the loop, eg:

```c++
while (true) {
    @autoreleasepool {
        do_stuff_per_iteration();
    }
}
```
Otherwise the pool will only be drained once the thread exits.

Comment (torarnv) [reply libobs/obs-cocoa.m:1820]: Never mind, I see you're calling `obs_graphics_thread_loop_mac` in a loop below.

**Comment by eric** [comment]
This looks like a great find!
