### PR TITLE
UI: Force UpdateEditMenu on UI Thread

### LINKED ISSUE #11116: OBS crashing on Mac M2 Air when switching scenes
### Operating System Info

macOS 14

### Other OS

_No response_

### OBS Studio Version

30.2.2

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/Ro85YoO1FwcEnwcd

### OBS Studio Crash Log URL

https://drive.google.com/file/d/1fYH5g8GrLBeXpl5BMZ2-EYLIO8Jpvi8e/view?usp=sharing

### Expected Behavior

Switch scenes indefinitely

### Current Behavior

After switching scenes for a while, OBS will crash with no message. It crashes as soon as I do a cut to another scene. Doesnt seem to consistantly be the same scene. Mac reports OBS quit unexpectedly. Last line of the log always states:

`QObject::startTimer: Timers cannot be started from another thread`

Doesn't seem to have anything to do with any scripts/plugins, as it happens even in safe mode. I've tried changing output formats and codecs but this doesn't seem to be related.

### Steps to Reproduce

1. Install any OBS version after 30.1.2 (30.2.0 onwards) for Mac OS (might be specific to Apple Silicon or M2)
2. Create a bunch of scenes (might need content like simple colour layers, might not need anything)
3. ~~Start streaming to YouTube while also recording the stream encoder. Output can be anything (mov, mp4, ts). I did not test without recording as I always need to (sorry).~~
4. Switch scenes a bunch of times in Studio Mode. Sometimes it will crash immediately, sometimes after switching a dozen times. I can't seem to get it to crash without being in Studio Mode.
...

### Anything else we should know?

I have NDI plugin updated and NDI SDK updated. But this crash occurs even in safe mode on any version after 30.1.2. Log provided was from a safe mode crash. 

30.1.2 doesn't seem to have this issue.

### PR DESCRIPTION
**Pull request by exeldro**
### Description
Force UpdateEditMenu on UI Thread

### Motivation and Context
UpdateEditMenu should always be called on the UI Thread
broken since #10725

Fixes #11116

### How Has This Been Tested?
On windows by removing and adding filters via not UI

### Types of changes
- Bug fix (non-breaking change which fixes an issue) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: UI/window-basic-main.cpp [hunk 1]
```diff
@@ -2014,13 +2014,25 @@ void OBSBasic::InitOBSCallbacks()
...
 		obs_get_signal_handler(), "source_filter_add",
 		[](void *data, calldata_t *) {
-			static_cast<OBSBasic *>(data)->UpdateEditMenu();
+			obs_queue_task(
+				OBS_TASK_UI,
+				[](void *param) {
+					static_cast<OBSBasic *>(param)
+						->UpdateEditMenu();
+				},
+				data, false);
```
Comment (derrod) [inline UI/window-basic-main.cpp:2023]: Can you not use `QMetaObject::invokeMethod` with `Qt::QueuedConnection` here like we do in other parts of the UI?

Comment (exeldro) [reply UI/window-basic-main.cpp:2023]: that is an option, in that case we need to make `UpdateEditMenu` a slot or `Q_INVOKABLE`

**Review by derrod — APPROVED** [review]
lgtm

**Comment by PatTheMav** [comment]
Potentially fixes #11116.

**Comment by RytoEX** [comment]
cc @gxalpha author of #10725

**Review by RytoEX — APPROVED** [review]
LGTM

**Comment by RytoEX** [comment]
> Potentially fixes #11116.

Potentially enough to explicitly link this PR and that Issue?

**Review by gxalpha — APPROVED** [review]
Seems correct. I don't think this occurs in stock OBS but should definitely be fixed.

**Comment by RytoEX** [comment]
Marking this as "Fixes #11116". If we find that it doesn't fix it, we can reopen it.
