### PR TITLE
frontend: Switch off deleted scenes immediately

### LINKED ISSUE #12880: Audio sources are not destroyed in Audio Mixer when deleting scene (Version 32.0.3)
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

Other

### OBS Studio Version (Other)

32.0.3

### OBS Studio Log URL

https://obsproject.com/logs/BMpfGBoiIdS3rC0B

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When deleting a scene, any audio sources contained in the scene should be removed from the Audio Mixer.

### Current Behavior

When deleting a scene, audio sources contained in the scene remain in the Audio Mixer.
This issue did not occur in OBS 32.0.2.

### Steps to Reproduce

1. Open OBS 32.0.3.
2. Create a scene and add an audio source.
3. Delete the scene.
4. The audio source is not destroyed and remains in the Audio Mixer.

Version 32.0.3

https://github.com/user-attachments/assets/cfaa460e-a849-4df5-b112-e85c81e846b7

Version 32.0.2

https://github.com/user-attachments/assets/3e2dbd0f-b1ba-4377-84c3-017b84228197

### Anything else we should know?

This issue seems specific to version 32.0.3.

### PR DESCRIPTION
**Pull request by Warchamp7**
### Description
Companion PR to #12882. When a scene has been removed and it was the previously active scene, switch immediately off of it.

### Motivation and Context
Fixes #12880 on the frontend side whereas #12882 fixes it on the libobs side. Both solutions are good: `libobs` should immediately cease using any source marked as removed and the frontend should avoid putting `libobs` in a state where it needs to.

### How Has This Been Tested?
Deleted multiple scenes that contained Audio Input/Output captures. Performed transitions after deleting the scene and confirmed no "ghost" transitions happened caused by the scene still being held by the current transition.

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: frontend/widgets/OBSBasic_Scenes.cpp [hunk 1]
```diff
@@ -492,16 +492,20 @@ void OBSBasic::on_scenes_currentItemChanged(QListWidgetItem *current, QListWidge
 {
 	OBSSource source;
 
+	bool oldSceneIsRemoved = false;
+
 	if (current) {
 		OBSScene scene = GetOBSRef<OBSScene>(current);
 		source = obs_scene_get_source(scene);
 
+		oldSceneIsRemoved = obs_source_removed(obs_scene_get_source(currentScene));
```
Comment (exeldro) [inline frontend/widgets/OBSBasic_Scenes.cpp]: instead of calling obs_scene_get_source twice source can be used

Comment (Warchamp7) [reply frontend/widgets/OBSBasic_Scenes.cpp]: `source` is the source for the currently selected scene in the QListWidget. It is the new scene, not the old one.

`currentScene` is the OBSBasic member variable that has not been updated yet at this stage.

Comment (exeldro) [reply frontend/widgets/OBSBasic_Scenes.cpp]: ah, my bad
I can't seem to resolve the comment I get error `Failed to resolve thread`

File: frontend/widgets/OBSBasic_Scenes.cpp [hunk 2]
```diff
@@ -492,16 +492,20 @@ void OBSBasic::on_scenes_currentItemChanged(QListWidgetItem *current, QListWidge
 {
 	OBSSource source;
 
+	bool oldSceneIsRemoved = false;
```
Comment (PatTheMav) [inline frontend/widgets/OBSBasic_Scenes.cpp]:
```suggestion
	bool forceSceneChange = false;
```

File: frontend/widgets/OBSBasic_Scenes.cpp (hunk 1 above)
Comment (PatTheMav) [inline frontend/widgets/OBSBasic_Scenes.cpp]:
```suggestion
		forceSceneChange = obs_source_removed(obs_scene_get_source(currentScene));
```

File: frontend/widgets/OBSBasic_Scenes.cpp [hunk 3]
```diff
@@ -492,16 +492,20 @@ void OBSBasic::on_scenes_currentItemChanged(QListWidgetItem *current, QListWidge
...
 
+		oldSceneIsRemoved = obs_source_removed(obs_scene_get_source(currentScene));
+
 		currentScene = scene;
 	} else {
 		currentScene = NULL;
 	}
 
-	SetCurrentScene(source);
+	SetCurrentScene(source, /*force=*/oldSceneIsRemoved);
```
Comment (PatTheMav) [inline frontend/widgets/OBSBasic_Scenes.cpp]:
```suggestion
	SetCurrentScene(source, forceSceneChange);
```

If C++-style comments were used here (as they should be in C++ code), this would not be possible. That one has to "reach down" to old C-style comments to make this compile should be a gentle hint that this is not a good pattern.

Instead the used variable should simply use a name that communicates what it _means_ logically in your current context. And because this variable is used for nothing else but to implicitly decide whether or not to force a scene change, it should simply carry information explicitly in its name.

Read it as "Whether I need to force-change the scene depends on whether the current scene's underlying source has the 'removed' state".

---

Indeed one could make the argument (and John Carmack recently made it) that it would be even better to do:

```C++
OBSSource *currentSceneSource = obs_scene_get_source(currentScene);
bool isCurrentSceneRemoved = obs_source_removed(currentSceneSource);
bool forceSceneChange = isCurrentSceneRemoved;
```

This would have multiple benefits (as Carmack pointed out):

* The return value of each `libobs` API function can be observed and debugged(!) separately (no information is "hidden" by temporaries)
* The values are immutable, they retain their original values throughout the function (so one can look at their original values even after a few other instructions)
* The logical flow is made explicit in the program:
    * First you get the source associated with the scene
    * Second you check whether it has the 'removed' state
    * Third, you interpret that state explicitly as the necessary requirement to force a scene change

That way the code is truly optimised for maintenance, debugging, and "the reader", as the logical step you took ("scene is marked 'resumed' and I directly use that as the requirement to force a scene change") is made explicit.

Modern compilers will optimise this with simple optimisation anyway (the generated assembly will be identical even with the function calls split out), so there is no penalty for the end user, just benefits for maintainers and debugging.

Comment (Warchamp7) [reply frontend/widgets/OBSBasic_Scenes.cpp]: > Indeed one could make the argument (and John Carmack recently made it) that it would be even better to do:

Honestly this has always been own preference but it has seemed to be uncommon. Compilers are smart and we don't have a budget on characters.

**Comment by exeldro** [comment]
The changes look good to me. There is a review requested from me, but I don't have the rights to approve.
