### PR TITLE
frontend-tools: Fix multiple signal-slot connections on output timer

### LINKED ISSUE #6558: Output timer stops video prematurely
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

27.2.4

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/forum/threads/output-timer-stops-video-prematurely.118949/

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

When using output timer, the video should be always stopped as expected

### Current Behavior

When using the output timer functionality, the recording will sometimes stop immediately, producing a 1kb file. The UI however shows that it is still recording. Normally when it is recording the file size is 0kb and will show the real size when the recording is complete. If I don't notice the 1kb file immediately, it will just keep running without throwing any errors. I for sure have the correct timer settings.

### Steps to Reproduce

When using the output timer functionality, the recording will sometimes stop immediately, producing a 1kb file. The UI however shows that it is still recording. Normally when it is recording the file size is 0kb and will show the real size when the recording is complete. If I don't notice the 1kb file immediately, it will just keep running without throwing any errors. I for sure have the correct timer settings.

### Anything else we should know?

The bug has been reproing since 25.0.4, see here: https://obsproject.com/forum/threads/output-timer-stops-video-prematurely.118949/

### PR DESCRIPTION
**Pull request by matt818**
### Description
This will fix the output timer bug from issue #6558. If you use the output timer too many times in a run of the program, issues start happening where on every other run of the output timer, the video will stop prematurely and generate a tiny video recording file. 

Every time the start button is pressed it makes a new connection to the QTimers, increasing the amount of connections and signals being sent to the QTimers by 1 each time the start button is clicked.

This fix moves the connections to the QTimers to the function that creates them, so that the connection is only established once.

### Motivation and Context
Fixes #6558.

### How Has This Been Tested?
I used the output timer to record multiple 5 seconds videos consecutively with the issue not happening.

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [ ] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: UI/frontend-plugins/frontend-tools/output-timer.cpp [hunk 1]
```diff
@@ -32,6 +32,18 @@ OutputTimer::OutputTimer(QWidget *parent)
 
 	recordingTimer = new QTimer(this);
 	recordingTimerDisplay = new QTimer(this);
+
+	QObject::connect(streamingTimer, &QTimer::timeout, this,
+			 &OutputTimer::EventStopStreaming);
+
```
Comment (gxalpha) [inline UI/frontend-plugins/frontend-tools/output-timer.cpp:38]: Please remove the newline here (and the ones below) to stay consistent with the connections further up.

**Review by gxalpha — APPROVED** [review]
This change does make sense and is definitely needed, but I don't quite understand how it fixes the issue. As is it should "only" call `obs_frontend_recording_stop` multiple times which in theory shouldn't cause any issues.

File: UI/frontend-plugins/frontend-tools/output-timer.cpp (hunk 1 above)
Comment (matt818) [reply UI/frontend-plugins/frontend-tools/output-timer.cpp]: Done.

**Review by PatTheMav — APPROVED** [review]

**Comment by PatTheMav** [comment]
The change in general seems desirable to me, because event handlers should be connected at the time of object creation and not dynamically every time a prior event handler is invoked.

**Comment by gxalpha** [comment]
@matt818 please make sure to squash your commits together into one and force-push this PR. There are currently two commits on the branch

**Review by gxalpha — APPROVED** [review]

**Comment by matt818** [comment]
Sorry, I'm new to all of this. Do I need to do anything else?

**Comment by gxalpha** [comment]
@matt818 Not currently, no.
If there are no other issues with this Pull Request, someone will merge it at some point. If any other issues come up, someone will comment on here again.

**Comment by norihiro** [comment]
The code looks pretty good but can the title be more specific?
Probably, this will be better. `frontend-tools: Fix multiple signal-slot connections on output timer`

**Review by RytoEX — APPROVED** [review]
Fixed up the commit message. Will merge shortly.
