### PR TITLE
obs-ffmpeg: Add auto reconnect to remote media sources

### LINKED ISSUE #2878: [BUG] RTSP streams fail to reconnect after faults
## Platform
Operating system and version: MacOS 10.14.6
OBS Studio version: 25.0.7

## Expected Behavior
RTSP stream should be temporarily lost and then re-connected in the event of an RTSP fault. If an RTSP source vanishes, it should be aggressively attempted for reconnection. If the user has not turned off the source, OBS should at a minimum keep trying to reconnect after a reset of the stream.

## Current Behavior
RTSP source streams currently stop for reasons that are unclear. This may be frame loss on the RTSP stream, overload on the CPU of the OBS host, or other failures. It is not clear from debugging what causes the RTSP stream to fail. Error messages are vague: "MP: av_read_frame failed: Operation timed out (-60)" but the error that causes the problem is not really the problem I'm identifying in this report. The problem is that the streams are not re-connected after a fault.

The behavior is that the RTSP stream does not restart after experiencing interruption. OBS does not reconnect to the sources, or if there are reconnect attempts they are not successful.  

Clicking on the "eye" in the source name and re-clicking (turning off/on the source) or restarting OBS  is the only way to get the RTSP streams back online. Reconnection is immediate after restart.

Logfile here: https://drive.google.com/file/d/1Cm6-UibJsAmjU_UMglp8pBVmlzcr7T16/view?usp=sharing

## Steps to Reproduce
Connect to one or two 15fps, 1080p RTSP stream, preferably Amcrest. Start stream to YouTube. Wait. One or both streams will eventually fail, possibly not at the same time, and the RTSP stream will not be automatically restarted. (Faults have been seen with single RTSP stream sources, or dual RTSP stream sources where one fails and the other does not, or where both fail eventually.)

## Additional information
I can provide more debugging or remote console if required, and am happy to test various settings or patched versions.

### PR DESCRIPTION
**Pull request by Yohox**
### Description
- deps\media-playback\media-playback\media.c
add av_dict_set(&opts, "stimeout", "30000000", 0);
when connect ffmpeg source fail it will be closed

- deps\media-playback\media-playback\media.c.h
add kill_cb in mp_media_info, when ffmpeg thread is killed it will be called

- plugins\obs-ffmpeg\obs-ffmpeg-source.c
add ffpmeg_source_reconnect, when ffmpeg_source_tick found media thread has been destory it will start reconnect thread after 10000 ms

### Motivation and Context
ffmepg source does not reconnect when source disconnect

### How Has This Been Tested?
obs add a rtmp source or rtsp source test close the network and after a moment reconnect。
After 10000  ms it will be reconnect。

### Types of changes
New feature (non-breaking change which adds functionality) 

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

Fixes #2878

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please stop opening new PRs. You can just run a force push to your existing branch and the PR will automatically update.

**Comment by dodgepong** [comment]
Thanks for this PR, I'll have to give it a try sometime. Stream disconnects when ingesting external streams are something that people have asked us about quite a bit. Is this something that could be applied to the VLC source as well?

And yes, you should be able to just squash and force push rather than opening a new PR for each attempt.

**Comment by Yohox** [comment]
sorry, this is my second pr, i'm not very familiar with this process.
i don't test in vlc case

**Comment by cg2121** [comment]
Doesn't the VLC source already handle disconnects?

**Comment by dodgepong** [comment]
Does it? I feel like I've heard reports of it not handling disconnects, maybe I'm wrong.

**Comment by Yohox** [comment]
> Doesn't the VLC source already handle disconnects?

I test in vlc case, I found the screen will stop when vlc source disconnect and don't toggle my code, may be this is another error.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 1]
```diff
@@ -315,6 +301,44 @@ static void ffmpeg_source_start(struct ffmpeg_source *s)
...
+	struct ffmpeg_source *s = data;
+	if (s->destroy_media) {
+		if (s->media_valid) {
+			mp_media_free(&s->media);
+			s->media_valid = false;
+		}
+		s->destroy_media = false;
+		FF_BLOG(LOG_ERROR, "MP: thread has been destory");
+		pthread_t reconnect_thread;
+		if (pthread_create(&reconnect_thread, NULL,
```
Comment (notr1ch) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:334]: This creates a dangling thread. If the source is destroyed, the thread is not correctly signaled to exit and waited on, which will result in a crash.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 2]
```diff
@@ -315,6 +301,44 @@ static void ffmpeg_source_start(struct ffmpeg_source *s)
 	}
 }
 
+static void *ffpmeg_source_reconnect(void *data)
+{
+	os_sleep_ms(10000);
```
Comment (notr1ch) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:306]: This should be a configurable delay or ideally, reconnect ASAP with exponential backoff.

**Comment by Yohox** [comment]
@notr1ch  i fix it.

**Comment by Fenrirthviti** [comment]
These commits must be squashed.

Follow this guide if you are unsure how: https://www.internalpointers.com/post/squash-commits-into-one-git

**Comment by Yohox** [comment]
> These commits must be squashed.
> 
> Follow this guide if you are unsure how: https://www.internalpointers.com/post/squash-commits-into-one-git

@Fenrirthviti 
done.

**Comment by eric** [comment]
Is this change waiting on something more?

**Comment by RytoEX** [comment]
> Is this change waiting on something more?

Yes.  This still doesn't conform to our [contributing guidelines](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).  The commits need to be squashed into one commit, with the correct prefix, and an appropriate note that it also modifies deps/media-playback.  It also needs to not modify locale files other than en-US, as [all of our translation work is done via Crowdin](https://obsproject.com/forum/threads/how-to-contribute-translations-for-obs.16327/).

Even after that is done, this still needs to be tested, and it will still have to pass review, probably from Jim or @notr1ch, or both.

**Comment by Yohox** [comment]
@RytoEX done. @notr1ch  please review.

**Comment by eric** [comment]
I’ve tested this and it works great. I wish the minimum for the retry setting was 2 seconds instead of 5.

**Comment by Yohox** [comment]
@eric done.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 3]
```diff
@@ -298,21 +347,19 @@ static void ffmpeg_source_tick(void *data, float seconds)
...
-		mp_media_play(&s->media, s->is_looping);
-		if (s->is_local_file)
-			obs_source_show_preloaded_video(s->source);
-		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
-		obs_source_media_started(s->source);
+		if (!s->is_local_file) {
+			FF_BLOG(LOG_ERROR, "MP: thread has been destroy");
+			if (pthread_create(&s->reconnect_thread, NULL,
+					   ffpmeg_source_reconnect, s) != 0) {
+				blog(LOG_WARNING,
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:357]: Use `FF_BLOG` instead of `blog`.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 4]
```diff
@@ -539,6 +599,12 @@ static void ffmpeg_source_destroy(void *data)
 
 	if (s->hotkey)
 		obs_hotkey_unregister(s->hotkey);
+	if (!s->is_local_file) {
+		s->stop_reconect = true;
+		if (s->reconnect_thread_valid) {
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:604]: Style:  Remove braces around single line `if` statements.

File: deps/media-playback/media-playback/media.c [hunk 5]
```diff
@@ -811,8 +812,6 @@ void mp_media_free(mp_media_t *media)
 	os_sem_destroy(media->sem);
 	sws_freeContext(media->swscale);
 	av_freep(&media->scale_pic[0]);
-	bfree(media->path);
-	bfree(media->format_name);
```
Comment (RytoEX) [inline deps/media-playback/media-playback/media.c:815]: Moving these `bfree` calls to the obs-ffmpeg source code doesn't seem right.  Why do you need to do this?

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 6]
```diff
@@ -288,6 +298,45 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+	if (s->media_valid) {
+		mp_media_play(&s->media, s->is_looping);
+		if (s->is_local_file)
+			obs_source_show_preloaded_video(s->source);
+		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
+		obs_source_media_started(s->source);
+	}
+}
+
+static void *ffpmeg_source_reconnect(void *data)
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:315]: Use `ffmpeg_source_reconnect` instead of `ffpmeg_source_reconnect` here and throughout the PR.

File: deps/media-playback/media-playback/media.c (hunk 5 above)
Comment (RytoEX) [reply deps/media-playback/media-playback/media.c:815]: I confirmed in my own testing that this change introduces memory leaks.  Reverting this change, and the associated changes in `obs-ffmpeg` removed the memory leaks and still allowed media sources to reconnect.

Comment (Yohox) [reply deps/media-playback/media-playback/media.c:815]: Because when mp_media_thread thread close, it will call mp_media_free to free media context, So that reconnect thread dons't get media context, So i want when the thread close dons't free context Unless the media source update.
can you give any suggest?

Comment (Yohox) [reply deps/media-playback/media-playback/media.c:815]: > Moving these `bfree` calls to the obs-ffmpeg source code doesn't seem right. Why do you need to do this?

Because when mp_media_thread thread close, it will call mp_media_free to free media context, So that reconnect thread dons't get media context, So i want when the thread close dons't free context Unless the media source update.
can you give any suggest?

**Comment by eric** [comment]
I noticed the configuration setting is visible for local files too, which doesn’t make sense.

**Comment by Yohox** [comment]
> I noticed the configuration setting is visible for local files too, which doesn’t make sense.

Can you explain it in detail?

**Comment by eric** [comment]
CleanShot 2020-06-20 at 13 23 26@2x

If "Local File" is selected, it doesn't make sense to show the reconnection setting.

**Comment by RytoEX** [comment]
@eric 
Out of curiosity, what happens if you have a media source on a network resource and the network connection is interrupted (e.g., media on another computer on your local network and that computer restarted)?  Does the source come back by itself without this PR?  Does it come back with this PR?

**Comment by eric** [comment]
@RytoEX I didn't (and don't have a good way to) test how this operates with local files, though I would expect you would see some strange hangs from OBS stalling on IO if such a situation happened.

File: plugins/obs-ffmpeg/data/locale/en-US.ini [hunk 7]
```diff
@@ -66,3 +66,5 @@ NVENC.OutdatedDriver="Your current video card driver does not support this NVENC
 NVENC.UnsupportedDevice="NVENC Error: Unsupported device. Check your video card supports NVENC and that the drivers are up to date."
 NVENC.TooManySessions="NVENC Error: Too many concurrent sessions. Try closing other recording software which might be using NVENC such as NVIDIA Shadowplay or Windows 10 Game DVR."
 NVENC.CheckDrivers="Please check your video drivers are up to date."
+
+ReconnectDelayTime="ReconnectDelayTime"
```
[the remark this answers is not in the document]
Comment (eric) [reply plugins/obs-ffmpeg/data/locale/en-US.ini:70]:
```suggestion
ReconnectDelayTime="Reconnect Delay"
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 8]
```diff
@@ -58,6 +58,11 @@ struct ffmpeg_source {
 	bool close_when_inactive;
 	bool seekable;
 
+	pthread_t reconnect_thread;
+	bool stop_reconect;
```
[the remark this answers is not in the document]
Comment (eric) [reply plugins/obs-ffmpeg/obs-ffmpeg-source.c:62]: Fix typo:

```suggestion
	bool stop_reconnect;
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 9]
```diff
@@ -288,6 +298,45 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+
+static void *ffpmeg_source_reconnect(void *data)
+{
+	struct ffmpeg_source *s = data;
+	os_sleep_ms(s->reconnect_delay_time * 1000);
+	FF_BLOG(LOG_INFO, "MP: start reconnect thread");
+	do {
+		if (s->stop_reconect) {
+			break;
+		}
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:323]: Fix typo and @RytoEX style suggestion:

```suggestion
		if (s->stop_reconnect)
			break;
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 10]
```diff
@@ -288,6 +298,45 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+
+		if (s->media_valid) {
+			break;
+		}
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:327]: Suggestion from @RytoEX:

```suggestion
		if (s->media_valid)
			break;
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 11]
```diff
@@ -338,8 +385,19 @@ static void ffmpeg_source_update(void *data, obs_data_t *settings)
...
+		s->reconnect_delay_time = s->reconnect_delay_time == 0
+						  ? 10
+						  : s->reconnect_delay_time;
 		s->is_looping = false;
 		s->close_when_inactive = true;
+
+		if (s->reconnect_thread_valid) {
+			s->stop_reconect = true;
+			pthread_join(s->reconnect_thread, NULL);
+			s->stop_reconect = false;
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:399]: Fix typo:

```suggestion
			s->stop_reconnect = true;
			pthread_join(s->reconnect_thread, NULL);
			s->stop_reconnect = false;
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 12]
```diff
@@ -539,6 +599,12 @@ static void ffmpeg_source_destroy(void *data)
 
 	if (s->hotkey)
 		obs_hotkey_unregister(s->hotkey);
+	if (!s->is_local_file) {
+		s->stop_reconect = true;
+		if (s->reconnect_thread_valid) {
+			pthread_join(s->reconnect_thread, NULL);
+		}
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:606]:
```suggestion
		if (s->reconnect_thread_valid)
			pthread_join(s->reconnect_thread, NULL);
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 13]
```diff
@@ -539,6 +599,12 @@ static void ffmpeg_source_destroy(void *data)
 
 	if (s->hotkey)
 		obs_hotkey_unregister(s->hotkey);
+	if (!s->is_local_file) {
+		s->stop_reconect = true;
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:603]:
```suggestion
		s->stop_reconnect = true;
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 14]
```diff
@@ -298,21 +347,19 @@ static void ffmpeg_source_tick(void *data, float seconds)
...
+		s->destroy_media = false;
 
-	if (s->media_valid) {
-		mp_media_play(&s->media, s->is_looping);
-		if (s->is_local_file)
-			obs_source_show_preloaded_video(s->source);
-		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
-		obs_source_media_started(s->source);
+		if (!s->is_local_file) {
+			FF_BLOG(LOG_ERROR, "MP: thread has been destroy");
```
[the remark this answers is not in the document]
Comment (eric) [reply plugins/obs-ffmpeg/obs-ffmpeg-source.c:354]:
```suggestion
			FF_BLOG(LOG_ERROR, "thread has been destroyed");
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 15]
```diff
@@ -288,6 +298,45 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
+		obs_source_media_started(s->source);
+	}
+}
+
+static void *ffpmeg_source_reconnect(void *data)
+{
+	struct ffmpeg_source *s = data;
+	os_sleep_ms(s->reconnect_delay_time * 1000);
+	FF_BLOG(LOG_INFO, "MP: start reconnect thread");
```
[the remark this answers is not in the document]
Comment (eric) [reply plugins/obs-ffmpeg/obs-ffmpeg-source.c:319]:
```suggestion
	FF_BLOG(LOG_INFO, "start reconnect thread");
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c (hunk 6 above)
Comment (eric) [reply plugins/obs-ffmpeg/obs-ffmpeg-source.c:315]: Fix typo:

```suggestion
static void * ffmpeg_source_reconnect(void *data)
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 16]
```diff
@@ -288,6 +298,45 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
 
+static void ffmpeg_source_start(struct ffmpeg_source *s)
+{
+	if (!s->media_valid)
+		ffmpeg_source_open(s);
+
+	if (s->media_valid) {
+		mp_media_play(&s->media, s->is_looping);
+		if (s->is_local_file)
+			obs_source_show_preloaded_video(s->source);
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:309]: Suggestion from @RytoEX:

```suggestion
			obs_source_show_preloaded_video(s->source);
			
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 17]
```diff
@@ -298,21 +347,19 @@ static void ffmpeg_source_tick(void *data, float seconds)
...
-	if (s->media_valid) {
-		mp_media_play(&s->media, s->is_looping);
-		if (s->is_local_file)
-			obs_source_show_preloaded_video(s->source);
-		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
-		obs_source_media_started(s->source);
+		if (!s->is_local_file) {
+			FF_BLOG(LOG_ERROR, "MP: thread has been destroy");
+			if (pthread_create(&s->reconnect_thread, NULL,
+					   ffpmeg_source_reconnect, s) != 0) {
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:356]:
```suggestion
					   ffmpeg_source_reconnect, s) != 0) {
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 18]
```diff
@@ -298,21 +347,19 @@ static void ffmpeg_source_tick(void *data, float seconds)
...
+				blog(LOG_WARNING,
+				     "MP: Could not create reconnect thread");
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:358]:
```suggestion
				FF_BLOG(LOG_WARNING,
				     "Could not create reconnect thread");
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 19]
```diff
@@ -174,6 +179,11 @@ static obs_properties_t *ffmpeg_source_getproperties(void *data)
 				obs_module_text("InputFormat"),
 				OBS_TEXT_DEFAULT);
 
+	prop = obs_properties_add_int_slider(
+		props, "reconnect_delay_time",
+		obs_module_text("ReconnectDelayTime"), 2, 60, 1);
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:184]:
```suggestion
		obs_module_text("ReconnectDelayTime"), 1, 60, 1);
```

I realized there's no reason not to make it 1s as the smallest amount.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 20]
```diff
@@ -288,6 +298,45 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+	if (!s->media_valid)
+		ffmpeg_source_open(s);
+
+	if (s->media_valid) {
+		mp_media_play(&s->media, s->is_looping);
+		if (s->is_local_file)
+			obs_source_show_preloaded_video(s->source);
+		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
+		obs_source_media_started(s->source);
+	}
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:312]: Suggestion from @RytoEX:

```suggestion
	if (!s->media_valid)
		return;
		
	mp_media_play(&s->media, s->is_looping);
	if (s->is_local_file)
		obs_source_show_preloaded_video(s->source);
	set_media_state(s, OBS_MEDIA_STATE_PLAYING);
	obs_source_media_started(s->source);
```

**Comment by Yohox** [comment]
@RytoEX 
Can you provide the memory leak reproduce case?

**Comment by RytoEX** [comment]
> Can you provide the memory leak reproduce case?

@Yohox 
1. Open OBS.
2. Add a Media Source
3. Set the Media Source to a remote source (e.g., an RTMP stream)
4. Cause the remote source to disconnect
5. Cause the remote source to reconnect
6. Exit OBS

The resulting OBS log will show memory leaks at the end of the log file.

File: deps/media-playback/media-playback/media.c (hunk 5 above)
Comment (eric) [reply deps/media-playback/media-playback/media.c:815]: @Yohox I don't really understand what you're seeing here and I can't see why this is needed at all. What goes wrong if you keep this where it is?

**Comment by eric** [comment]
@Yohox I'm pretty sure if you back out the changes to `bfree()` and put it where it was before that everything will Just Work.

**Comment by Yohox** [comment]
@eric 
Because In plugins/obs-ffmpeg/obs-ffmpeg-source.c
ffmpeg_source_reconnect function should read struct ffmpeg_source *s = data;
`
static void * ffmpeg_source_reconnect(void *data)
{
	struct ffmpeg_source *s = data;
        ....
}
`
But Before When source destory It will free the ffmpeg_source In deps/media-playback/media-playback/media.c line: 814
`
bfree(media->path);	
bfree(media->format_name);
`

So I move the bfree code from `deps/media-playback/media-playback/media.c` to `plugins/obs-ffmpeg/obs-ffmpeg-source.c` ffmpeg_source_update function

**Comment by eric** [comment]
@Yohox I still don't understand what you're saying. There's nothing in `plugins/obs-ffmpeg/obs-ffmpeg-source.c` that references `media->path` or `media->format_name` directly.

What goes wrong when you put the `bfree()` back where it originally was? Does it still compile? Does the app crash?

What does `ffmpeg_source_reconnect()` have to do with where the `media->path` is freed?

**Comment by eric** [comment]
I also wanted to remind you that you need to add the following to `is_local_file_modified()` to make it not show the setting when local file is select:

```
	obs_property_t *reconnect_delay_time = obs_properties_get(props, "reconnect_delay_time");
        // ...
	obs_property_set_visible(reconnect_delay_time, !enabled);
```

**Comment by Yohox** [comment]
@eric 
image
In `deps/media-playback/media-playback/media.c` when ffmpeg source destory 

If we don't delete the bfree code 

when source reconnect thread restart the ffmpeg source thread
In `deps/media-playback/media-playback/media.c` line 592
`
int ret = avformat_open_input(&m->fmt, m->path, format,
				      opts ? &opts : NULL);
`
it will read m->path but the m->path is free it will crash.

**Comment by Yohox** [comment]
> I also wanted to remind you that you need to add the following to `is_local_file_modified()` to make it not show the setting when local file is select:
> 
> ```
> 	obs_property_t *reconnect_delay_time = obs_properties_get(props, "reconnect_delay_time");
>         // ...
> 	obs_property_set_visible(reconnect_delay_time, !enabled);
> ```

Ok i will change.

**Comment by eric** [comment]
In what situation would `mp_media_free()` be called in `obs-ffmpeg-source.c` while the thread is running?

**Comment by Yohox** [comment]
if the ffmpeg source thread dosen't connect the source it will break and mark the media->valid false 
and ffmpeg_source_tick will call mp_media_free to free.

image

**Comment by Yohox** [comment]
@eric 
You are right. I will change this code.

**Comment by eric** [comment]
Great!

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 21]
```diff
@@ -93,7 +100,7 @@ static bool is_local_file_modified(obs_properties_t *props,
 	obs_property_set_visible(looping, enabled);
 	obs_property_set_visible(speed, enabled);
 	obs_property_set_visible(seekable, !enabled);
-
+	obs_property_set_visible(reconnect_delay_time, !enabled);
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:103]: Please re-add the blank line here between the last `obs_property_set_visible` and `return true;`.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 22]
```diff
@@ -288,6 +300,44 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+{
+	if (!s->media_valid)
+		ffmpeg_source_open(s);
+
+	if (!s->media_valid)
+		return;
+
+	mp_media_play(&s->media, s->is_looping);
+	if (s->is_local_file)
+		obs_source_show_preloaded_video(s->source);
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:313]: Add a blank line between this line and the next line to separate `if` contents from the code that comes after it.

**Comment by eric** [comment]
@RytoEX This should be ready for another review.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 23]
```diff
@@ -298,21 +348,19 @@ static void ffmpeg_source_tick(void *data, float seconds)
...
+		s->destroy_media = false;
 
-	if (s->media_valid) {
-		mp_media_play(&s->media, s->is_looping);
-		if (s->is_local_file)
-			obs_source_show_preloaded_video(s->source);
-		set_media_state(s, OBS_MEDIA_STATE_PLAYING);
-		obs_source_media_started(s->source);
+		if (!s->is_local_file) {
+			FF_BLOG(LOG_ERROR, "thread has been destroyed");
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:355]: Please use "reconnect thread has been destroyed" here.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c (hunk 21 above)
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:103]:
```suggestion
	obs_property_set_visible(reconnect_delay_time, !enabled);
	
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 24]
```diff
@@ -288,6 +300,44 @@ static void ffmpeg_source_open(struct ffmpeg_source *s)
...
+static void ffmpeg_source_start(struct ffmpeg_source *s)
+{
+	if (!s->media_valid)
+		ffmpeg_source_open(s);
+
+	if (!s->media_valid)
+		return;
+
+	mp_media_play(&s->media, s->is_looping);
+	if (s->is_local_file)
```
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:312]: Request from @RytoEX:

```suggestion

	if (s->is_local_file)
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c (hunk 23 above)
Comment (eric) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:355]:
```suggestion
			FF_BLOG(LOG_ERROR, "reconnect thread has been destroyed");
```

**Comment by RytoEX** [comment]
@eric No need to tag me.  I already get email notifications for all changes to PRs.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c (hunk 24 above)
Comment (RytoEX) [reply plugins/obs-ffmpeg/obs-ffmpeg-source.c:312]: I actually didn't request this.  I requested a blank line _below_.

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c (hunk 22 above)
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:313]:
```suggestion
		obs_source_show_preloaded_video(s->source);
		
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c (hunk 23 above)
Comment (RytoEX) [reply plugins/obs-ffmpeg/obs-ffmpeg-source.c:355]: This line will likely trigger clang-format to fail for being too long.

Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:355]:
```suggestion
			FF_BLOG(LOG_ERROR,
				"reconnect thread has been destroyed");
```

File: plugins/obs-ffmpeg/obs-ffmpeg-source.c [hunk 25]
```diff
@@ -93,7 +100,8 @@ static bool is_local_file_modified(obs_properties_t *props,
 	obs_property_set_visible(looping, enabled);
 	obs_property_set_visible(speed, enabled);
 	obs_property_set_visible(seekable, !enabled);
-
+	obs_property_set_visible(reconnect_delay_time, !enabled);
+
```
Comment (RytoEX) [inline plugins/obs-ffmpeg/obs-ffmpeg-source.c:104]:
```suggestion

```

**Comment by RytoEX** [comment]
I have force pushed the requested changes to the fork for this PR.

**Comment by Yohox** [comment]
Great!

**Comment by Barabba11** [comment]
HI mates, may someone help me understand, I've installed the latest OBS but I suffer from the same problem, if the source RTSP may be temporary not avilable, OBS doesn't retry for a reconnection. Is this plugin already implemented in the latest version? Or how can I implement it? Kindly describe me stemps, thank you a lot!

**Comment by Yohox** [comment]
> HI mates, may someone help me understand, I've installed the latest OBS but I suffer from the same problem, if the source RTSP may be temporary not avilable, OBS doesn't retry for a reconnection. Is this plugin already implemented in the latest version? Or how can I implement it? Kindly describe me stemps, thank you a lot!

can you provide your obs version?

**Comment by Barabba11** [comment]
I've just downloaded it yesterday from your site :) should be the latest!

**Comment by Yohox** [comment]
> I've just downloaded it yesterday from your site :) should be the latest!

ok, can you provide the obs log?

**Comment by Barabba11** [comment]
With pleasure, I
[log.zip](https://github.com/obsproject/obs-studio/files/6141842/log.zip)

this is the log folder, I don't know how many interesting info you may find there, cause I don't see logs about streaming. The OBS was running from yesterday, probably the problem appeared during night

**Comment by Yohox** [comment]
> With pleasure, I
> [log.zip](https://github.com/obsproject/obs-studio/files/6141842/log.zip)
> 
> this is the log folder, I don't know how many interesting info you may find there, cause I don't see logs about streaming. The OBS was running from yesterday, probably the problem appeared during night

emm, no found any effective information. we should more information. can you reproduce that? like shutdown network.

**Comment by Barabba11** [comment]
I'll do it this night, let's see. So as I can understand you already implemented the auto reconnect. If this happens, that the stream not updates (but available from VLC for example), will it log the failure in the logs? Or should I enable a verbose log?
Teach me please how to debug it correctly

**Comment by Fenrirthviti** [comment]
If you need support, please use the support channels in our Discord or appropriate forum section.

**Comment by Yohox** [comment]
> I'll do it this night, let's see. So as I can understand you already implemented the auto reconnect. If this happens, that the stream not updates (but available from VLC for example), will it log the failure in the logs? Or should I enable a verbose log?
> Teach me please how to debug it correctly

create a issue, we go there discuss

**Comment by Fenrirthviti** [comment]
Again, please use the forums or Discord for support and troubleshooting, we reserve issues on this project for verified bugs with replication steps. Any issues opened asking for support will be closed.

**Comment by Barabba11** [comment]
thanks for support, I've opened a thread https://obsproject.com/forum/threads/autoreconnect-rtsp-stream.141004/

**Comment by Barabba11** [comment]
Hi mates, in the forum I had no replies, I'm posting here, maybe someone has an idea how to proceed, thank  you a lot!

It happened again, and I don't know how to help you understand where the problem is.. I've checked the log, they contain only log of the start of OBS and its shutting down, events which appeared during functioning (that's what I'm looking for) aren't present. How can I activate a log each time RTSP stop? How can I tell OBS to force reconnect forever?
Thanks

**Comment by dodgepong** [comment]
A lack of replies on the forum is not permission to continue misusing Github as a support center.

**Comment by Barabba11** [comment]
I wish somebody can help me, thank you for your support

**Comment by notr1ch** [comment]
@Barabba11 It has been explained many times to you that this is not the place for support. Each time you comment here, you send a notification to every developer who has worked on this issue. It is expected that such notifications are only for regressions or other development related tasks and it is rude to keep interrupting developers this way.
