### PR TITLE
linux-v4l2: Fix virtual camera start failure

### LINKED ISSUE #11891: Failed to start virtual camera
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

31.0.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/Q8JBY1aQ0Z9qQviP

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Virtual camera would start and applications would detect it

### Current Behavior

Virtual camera does not start with the following in OBS logs
```
info: GPU conversion not available for format: 7
info: NV12 texture support not available
warning: Failed to start virtual camera
info: Starting Virtual Camera output to Source : Screen
info: [pipewire] Stream 0x56d23a748780 state: "paused" (error: none)
```

### Steps to Reproduce

1. Install from system package manager
2. Launch OBS
3. Attempt to start virtual camera, any mode

### Anything else we should know?

Occurs on the official OBS Flatpak and on system packages, same error across both

### PR DESCRIPTION
**Pull request by stephematician**
Skip the 'non-compliant' usage of STREAMON ioctl for V4L2 compliant _v4l2loopback_ module

### Description

When starting the virtual camera:

-   Check the OUTPUT capability is reported for the device.
    -   If has OUTPUT: use compliant calls only (do not use STREAMON/OFF workaround).
    -   If no OUTPUT capability: _attempt_ to reset using the STREAMON/OFF workaround for _loopback_ 0.12.5-0.12.7, then continue to use workaround each time opened.

### Motivation and Context

Fixes #11891

_v4l2loopback_ was recently updated to have stronger compliance with V4L2 UAPI; thus, the invocation of STREAMON by _OBS_ when no streaming I/O buffers have been negotiated (e.g. via REQBUFS) results in an error.

This is also a revision of the fix for #4808 - where it was identified that the STREAMON call would trigger the reset of the OUTPUT capability when the loopback node was closed (thus allowing the camera to be restarted).

### How Has This Been Tested?

Built on Ubuntu 24.04, x64 machine, with _v4l2loopback_:

1.  @ 0.12.5-0.12.7 - confirm no regression for #4808;
2.  @ 0.13.0-0.13.2 - confirm no longer use workaround as _loopback_ was already patched, and;
3.  @ 0.14.0 - confirm fix #11891

Starting, stopping, and re-starting the virtual camera succeeded in all versions tested.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
For clarification, is there a reason to hold on to the old behavior for older versions? If the issue is stricter requirements on the v4l2loopback side, wouldn't this just be a backwards compatible change?

What breaks in the old versions with this change, or is that untested and just an attempt to not change what has been working?

**Comment by stephematician** [comment]
The existing behaviour should be kept when using loopback <= 0.13.2, otherwise there'll be regression to #4808

An alternative solution: Simply ignore any errors from STREAMON or STREAMOFF. In a way; this would be cleaner - but there is a relatively harmless issue where, say, a user has an older loopback module and STREAMON fails for a legitimate reason. In that case - presumably the next call to `write()` will fail and if the user tries to view the virtual camera, they'll see nothing (but also have no feedback as to why it isn't working).

**Comment by stephematician** [comment]
I just remembered I forgot to close the file pointer. Such a noob mistake!

**Comment by Fenrirthviti** [comment]
I'm mostly just confused by the presentation of what this is actually fixing.

It sounds like this is actually resulting from what was a *bug* in v4l2loopback, and we had previously put a workaround in place for, and now that bug is fixed (in the name of better compliance, presumably) and the workaround is now causing issues.

**Comment by stephematician** [comment]
> I'm mostly just confused by the presentation of what this is actually fixing.
> 
> It sounds like this is actually resulting from what was a _bug_ in v4l2loopback, and we had previously put a workaround in place for, and now that bug is fixed (in the name of better compliance, presumably) and the workaround is now causing issues.

Yes. Sorry, I should have answered your quetion.

That is exactly the issue.

1.  loopback <= 0.13.2 had a problem with internal state, meaning that cameras did not restart.
2.  OBS introduced a call to STREAMON call as a workaround.
3.  loopback > 0.13.2 (once released) no longer has a problem with internal state, but it _will_ complain about STREAMON (because this use of STREAMON is not V4L2 UAPI compliant - pretty sure it will fail on every compliant device).
4.  as long as OBS doesn't call STREAMON (or ignores errors); then the camera starts/stops/restarts cleanly with loopback > 0.13.2

Happy to change approach with this PR if needed.

**Comment by Fenrirthviti** [comment]
I'll leave the technical specifics to others to comment on, we were just a bit confused on the context around this.

Makes perfect sense now, thanks!

**Comment by stephematician** [comment]
> just a bit confused

I can relate. It took me a ridiculously long time to get my head about the loopback module as I was updating it. Thanks for your questions!

**Comment by stephematician** [comment]
FWIW: the "simpler" fix would be to treat the failed STREAMON (or STREAMOFF) as an info/warning message and not an error; e.g. in `v4l2-output.c`:

```diff
	if (ioctl(vcam->device, VIDIOC_STREAMON, &parm) < 0) {
-		blog(LOG_ERROR, "Failed to start streaming on '%s' (%s)", device, strerror(errno));
-		goto fail_close_device;
+		if (errno == -EINVAL) {
+			blog(LOG_INFO, "EINVAL returned from loopback STREAMON, likely an error in loopback version <= 0.13.2");
+		} else {
+			blog(LOG_ERROR, "Failed to start streaming on '%s' (%s)", device, strerror(errno));
+			goto fail_close_device;
+		}
	}

	blog(LOG_INFO, "Virtual camera started");
```

**Comment by stephematician** [comment]
Somewhat tidied up; also noticed that the dimensions (and pixel format) returned by S_FMT were being ignored; which can lead to unexpected behaviour if the (virtual) device chooses a different size (or pixel format) to the request. So that's fixed now, too.

**Review by kkartaltepe — COMMENTED** [review]
First commit is fine. The 2nd commit changes a bit too much can we split it out into another PR so we can merge this one right now?

**Comment by stephematician** [comment]
Sure, no problem; I didn't carefully plan the second commit - it just sort of "happened" when I had a closer look at the sequence.

**Review by kkartaltepe — APPROVED** [review]

File: plugins/linux-v4l2/v4l2-output.c [hunk 1]
```diff
@@ -241,9 +273,8 @@ static void virtualcam_stop(void *data, uint64_t ts)
 	struct v4l2_streamparm parm = {0};
 	parm.type = V4L2_BUF_TYPE_VIDEO_OUTPUT;
 
-	if (ioctl(vcam->device, VIDIOC_STREAMOFF, &parm) < 0) {
+	if (use_vcam_restart_workaround() && ioctl(vcam->device, VIDIOC_STREAMOFF, &parm) < 0)
 		blog(LOG_WARNING, "Failed to stop streaming on video device %d (%s)", vcam->device, strerror(errno));
-	}
```
Comment (RytoEX) [inline plugins/linux-v4l2/v4l2-output.c:246]: No need to remove these braces.

File: plugins/linux-v4l2/v4l2-output.c [hunk 2]
```diff
@@ -95,6 +96,36 @@ bool loopback_module_available()
 	return false;
 }
 
+bool use_vcam_restart_workaround()
+{
+	static int version = -1;
+	FILE *fp;
+	size_t result = 0;
+	int v_major, v_minor, v_bugfix;
```
Comment (RytoEX) [inline plugins/linux-v4l2/v4l2-output.c:104]:
```suggestion
	int v_major;
	int v_minor;
	int v_bugfix;
```

**Review by RytoEX — CHANGES_REQUESTED** [review]

File: plugins/linux-v4l2/v4l2-output.c (hunk 2 above)
Comment (stephematician) [reply plugins/linux-v4l2/v4l2-output.c]: Corrected in e340a44

File: plugins/linux-v4l2/v4l2-output.c (hunk 1 above)
Comment (stephematician) [reply plugins/linux-v4l2/v4l2-output.c]: Corrected in e340a44

**Review by RytoEX — APPROVED** [review]

**Comment by mutax** [comment]
Just compiled the branch in an arch linux and can confirm virtual camera works again. Thanks a lot! 
fwiw:
v4l2loopback-dkms 0.14.0-1
kernel 6.13.6-arch1-1

File: plugins/linux-v4l2/v4l2-output.c [hunk 3]
```diff
@@ -95,6 +96,38 @@ bool loopback_module_available()
...
+	FILE *fp;
+	size_t result = 0;
+	int v_major;
+	int v_minor;
+	int v_bugfix;
+
+	if (version >= 0)
+		return version <= 0x0D02;
+
+	fp = fopen("/sys/module/v4l2loopback/version", "r");
```
Comment (tytan652) [inline plugins/linux-v4l2/v4l2-output.c:111]: This is not functional inside a Flatpak context, `/sys/module` is not reachable (and adding sandbox hole will not be accepted).

**Comment by kkartaltepe** [comment]
> Somewhat tidied up; also noticed that the dimensions (and pixel format) returned by S_FMT were being ignored; which can lead to unexpected behaviour if the (virtual) device chooses a different size (or pixel format) to the request. So that's fixed now, too.

Yea we probably need to just do this to support flatpak since we cannot query modules and at least from v4l2-ctrl it looks like v4l2loopback does not actually report its version in the device query.

File: plugins/linux-v4l2/v4l2-output.c (hunk 3 above)
Comment (WizardCM) [reply plugins/linux-v4l2/v4l2-output.c:111]: Additionally, the `/version` file doesn't exist for me at all in v4l2loopback-dkms 0.12.7 on Ubuntu 24.04.

Comment (stephematician) [reply plugins/linux-v4l2/v4l2-output.c:111]: > Additionally, the `/version` file doesn't exist for me at all in v4l2loopback-dkms 0.12.7 on Ubuntu 24.04.

Interesting, I'll double check this on a fresh 24.04 with the dkms package. In any case; if the version isn't reported in earlier loopback modules, it'll behave as it it did before.

**Comment by stephematician** [comment]
> > FWIW: the "simpler" fix would be to treat the failed STREAMON (or STREAMOFF) as an info/warning message and not an error; e.g. in v4l2-output.c:
> 
> Yea we probably need to just do this to support flatpak since we cannot query modules 

Good to know. I haven't been able to figure out how to test in Flatpak (is there a guide?).

I assume when you say:

> adding a new sandbox hole won't be accepted

you mean to say that it's not worth it to resolve this bug? 

Would it makes sense to do a "hybrid" of the two fixes? E.g. attempt to read the version;

1.  if we can't read it - keep the existing behaviour (workaround) _except_ ignore the _expected_ error for loopback versions >= 0.14.0 (probably with a warning), otherwise;
2.  if we _can_ read the version; skip the workaround (i.e. the non-compliant STREAMON/OFF)?

This means that at least for non-flatpak; the non-compliant calls are eliminated.

> and at least from v4l2-ctrl it looks like v4l2loopback does not actually report its version in the device query.

Correct; most (?) devices report the kernel version; not the "out-of-tree" version - so it doesn't seem useful to us.

There is also a third possibility that might be better altogether... Instead of testing the _version_ of the loopback module - test for the _fault_ that occurs when the STREAMON is _not_ called in earlier versions. If the fault appears; _then_ try the STREAMON as a potential fix. Only _then_ declare that the device could not be opened.

**Comment by stephematician** [comment]
> **There is also a third possibility that might be better altogether...** Instead of testing the _version_ of the loopback module - test for the _fault_ that occurs when the STREAMON is _not_ called in earlier versions. If the fault appears; _then_ try the STREAMON as a potential fix. Only _then_ declare that the device could not be opened.

The more I think about it; the more I'd rather go in this direction.

The original problem was that a virtual camera could not be (re)started; it would report no OUTPUT capability.

By some quirk of the 0.12.5 loopback code; this could be avoided by calling STREAMON _every_ time the device was opened, because this had the result that _when the device was closed_ it would reset its capabilities correctly.

When the loopback is opened; the OUTPUT capability is tested:

-   If NO OUTPUT: 
    1.  Log "attempting to reset loopback output caps":
    2.  Call STREAMON (with output buffer) then STREAMOFF, and close the device; then re-open and query OUTPUT again.
        -   NO OUTPUT capability or any errors: report that the device could not be opened.
        -   YES OUTPUT: set a flag that the STREAMON should be invoked each time the loopback is opened (after format is set, of course).
-   If YES OUTPUT; proceed with V4L2-compliant approach OR use the non-compliant STREAMON kludge if flagged.

File: plugins/linux-v4l2/v4l2-output.c (hunk 3 above)
Comment (stephematician) [reply plugins/linux-v4l2/v4l2-output.c:111]: @WizardCM - confirmed; looks like this wasn't introduced until later version.

I'll await feedback, but I'm thinking that we need a fix that doesn't rely on detecting version. See https://github.com/obsproject/obs-studio/pull/11906#issuecomment-2727237666

**Comment by tytan652** [comment]
> you mean to say that it's not worth it to resolve this bug?

Just in case to avoid a misunderstanding:
Our lowest common denominator is the Flatpak environment, while we do have some sandbox holes their number is only allowed to decrease.

At no point I said, it was no worth it to fix it. I technically said that the fix must fit within the limitation of the Flatpak.

**Comment by stephematician** [comment]
@tytan652 - understood; I'm totally naive about Flatpak, but I think I hear what you're saying about the limitation coming from Flatpak (environment) rather than OBS.

File: plugins/linux-v4l2/v4l2-output.c (hunk 3 above)
Comment (stephematician) [reply plugins/linux-v4l2/v4l2-output.c]: This should be fixed in 52d57cf7 - I've tested this with loopback 0.12.5, 0.12.7, 0.13.0, and 0.14.0. We don't attempt to detect the version anymore; instead we test output capabilities - if they aren't there, we try to reset them (with the STREAMON/OFF workaround), if successful, then we make sure we use the workaround each time the device is opened/closed.

Note: I believe the workaround is only needed for loopback 0.12.5-0.12.7.

**Comment by brauliobo** [comment]
I just changed the `PKGBUILD` manually with your patch @stephematician. It was not a quick process to get OBS v4l back working, but it worked, thanks!

**Comment by stephematician** [comment]
FWIW reviewers - I've updated the description to match what the changes are.

**Comment by end3r-man** [comment]
+1

**Comment by fritz-fritz** [comment]
FWIW: Just built, packaged, and tested this PR against obs 31.0.2 and it worked for both v4l2loopback-dkms v0.13.2-1 and v0.14.0-1 on a debian based system.

+1 :heavy_check_mark:

**Comment by EvergreenTheTree** [comment]
Here's the upstream Arch `obs-studio` PKGBUILD with a change to apply the updates in this PR in patch format: https://gist.github.com/EvergreenTheTree/90182e76bafecdd4de9dd21adf72a3e7

**Comment by HuronExplodium** [comment]
> Here's the upstream Arch `obs-studio` PKGBUILD with modified to apply the changes in this PR in patch format: https://gist.github.com/EvergreenTheTree/90182e76bafecdd4de9dd21adf72a3e7

confirm working on Arch

**Review by y4my4my4m — COMMENTED** [review]
this worked. thank you

**Comment by stephematician** [comment]
@RytoEX @kkartaltepe @WizardCM - just checking if there's someone more appropriate for review. I simply went with you three as you had performed previous review(s).

**Comment by FineWolf** [comment]
Is there anything we can do to get this MR past the finish line?

Anyone who relies on Flatpak OBS and v4l2loopback have had their workflow broken for 2 months now.

**Comment by tiberium-v** [comment]
> Is there anything we can do to get this MR past the finish line?
> 
> Anyone who relies on Flatpak OBS and v4l2loopback have had their workflow broken for 2 months now.

To be more precise, it's mainly on arch system the problem, because they are on v14 of v4l2-loopback-dkms. You can also downgrade the v4l2-loopback package as a temporary fix (and put the package as ignore in your pacman.conf). Then (after a reboot / module restart) everything is functional again.

**Comment by archerallstars** [comment]
@tiberium-v This is also broken in openSUSE Tumbleweed, and there is not possible to downgrade the v4l2loopback package anymore for someone who hadn't locked the package. 

http://download.opensuse.org/history

File: plugins/linux-v4l2/v4l2-output.c [hunk 4]
```diff
@@ -130,6 +174,13 @@ static bool try_connect(void *data, const char *device)
 	if (ioctl(vcam->device, VIDIOC_QUERYCAP, &capability) < 0)
 		goto fail_close_device;
 
+	if (!use_caps_workaround && !(capability.device_caps & V4L2_CAP_VIDEO_OUTPUT)) {
+		if (!try_reset_output_caps(device))
+			goto fail_close_device;
+		use_caps_workaround = true;
```
Comment (RytoEX) [inline plugins/linux-v4l2/v4l2-output.c:180]: To distinguish the `if` from subsequent code, either add a blank line after the `if` statement contents, or enclose it in braces.

**Review by RytoEX — CHANGES_REQUESTED** [review]

**Comment by sur5r** [comment]
Debian Trixie is currently in freeze as well and is affected by this (https://bugs.debian.org/1101351). An official fix would be very welcome.

File: plugins/linux-v4l2/v4l2-output.c (hunk 4 above)
Comment (stephematician) [reply plugins/linux-v4l2/v4l2-output.c]: resolved in 26b447718

**Comment by stephematician** [comment]
Thanks for your patience everyone; I'm the monster that broke this when fixing up v4l2loopback - but there was no other way to keep the module compliant with the kernel.

I wasn't expecting an OBS PR to fall on my shoulders, too, so this has taken much longer than if someone with experience in flatpak environment development was running the lead.

**Comment by FineWolf** [comment]
@stephematician

You have nothing to apologize for, nor has anyone else here for that matter. Software development does take time.

My message was simply to offer my help if there needed to be extra work to be done, and, since this issue has sat idle waiting for reviews for the past month, it was an attempt to bring it back to the forefront.

Yes, rolling releases do get breaking changes faster than other distros, but it's also an opportunity to catch them and fix them before it affects point release distros. Unfortunately, this MR has sat in review phase without much interest for long enough that point release distros are now encountering this issue as well, so a little reminder was needed.

**Comment by FineWolf** [comment]
@tytan652 

Artifact `obs-studio-flatpak-90516132a-x86_64.flatpak` tested on two systems.

---

## System 1:

Arch Linux (up to date as of this morning)
❯ v4l2loopback-ctl --version
v4l2loopback-ctl v0.14.0
v4l2loopback module v0.14.0

Virtual camera starts properly; both from a fresh run after a reboot, and after the module has been initialized.

---

## System 2:

Bazzite 42.20250417
❯ v4l2loopback-ctl --version
v4l2loopback-ctl v0.14.0
v4l2loopback module v0.14.0

Virtual camera starts properly; both from a fresh run after a reboot, and after the module has been initialized.

---

I don't have a system with v0.13.2; however I can spin one up if you are lacking testers.

**Review by RytoEX — APPROVED** [review]
Looks okay. Received approvals off-thread.

**Comment by akrz** [comment]
Is there a way to have this in flathub?

**Comment by philg-dev** [comment]
@akrz  this is not part of any official release yet. As you can see above, it's been added to the 31.1 milestone when the PR got merged into the master branch.

You'll have to wait until that version gets released or build it yourself from source.

**Comment by JacobCallahan** [comment]
@akrz you can also download the flatpak build artifact from the GitHub actions in this pull request and use that to install an alternate version locally.

**Comment by stephematician** [comment]
@JacobCallahan @akrz FWIW - navigating to artifacts always seems tricky - I find them by navigating to the `checks` tab at the top of the PR, then selecting `Pull` on the left. You should end up here; https://github.com/obsproject/obs-studio/actions/runs/14606426833

**Comment by p-m-j** [comment]
@jpVm5jYYRE1VIKL why not just run the pre-release as was previously suggested? [obs-studio-flatpak-90516132a-x86_64.flatpak](https://github.com/obsproject/obs-studio/actions/runs/14606426833/artifacts/2991455870)

**Comment by dbear496** [comment]
> @jpVm5jYYRE1VIKL why not just run the pre-release as was previously suggested? [obs-studio-flatpak-90516132a-x86_64.flatpak](https://github.com/obsproject/obs-studio/actions/runs/14606426833/artifacts/2991455870)

A hotfix release could get this fix into package repositories faster than waiting until the next minor version release. Sure, everyone could uninstall the obs-studio package provided by their distribution repository and install the pre-release version; then when the next release comes, uninstall the pre-release and re-install the repository package. But no one wants to go through that.

**Comment by akrz** [comment]
I tried the artifact build but had issues with plugins (droidcam). I just removed the flatpak and went with the native fedora package, I think some other distros backported this as a patch too.

I'm a bit surprised that the official flatpak image of obs doesn't have this fix yet in the stable version. This broke the workflow of several users and it wasn't trivial to know what was going on.

**Comment by stephematician** [comment]
> Hey . Can you please form HOTFIX release because whole functionality in current moment broken .

I'd say that unless you can build OBS, use the flatpak artefact, or are on a distribution which has a backported patch (i.e. Fedora); then roll _v4l2loopback_ to 0.13.2 and hold it there.

**Comment by burtonis** [comment]
Garuda Linux (Arch-based) and I upgraded to aur/obs-studio-git.  The v4l2loopback module no longer complains.
`6.14.9-zen1-1-zen`
`aur/obs-studio-git 31.0.3.r236.g000437f-1`
`extra/v4l2loopback-dkms 0.14.0-1`

Is there any way to do a minor point release to include just this fix?

**Comment by stephematician** [comment]
> Garuda Linux (Arch-based) and I upgraded to aur/obs-studio-git. The v4l2loopback module no longer complains. `6.14.9-zen1-1-zen` `aur/obs-studio-git 31.0.3.r236.g000437f-1` `extra/v4l2loopback-dkms 0.14.0-1`
> 
> Is there any way to do a minor point release to include just this fix?

There are beta releases on GitHub with the fix, e.g.: https://github.com/obsproject/obs-studio/releases/tag/31.1.0-beta2

**Comment by jpVm5jYYRE1VIKL** [comment]
> @jpVm5jYYRE1VIKL why not just run the pre-release as was previously suggested? [obs-studio-flatpak-90516132a-x86_64.flatpak](https://github.com/obsproject/obs-studio/actions/runs/14606426833/artifacts/2991455870)

@p-m-j . Because nobody want to fill OS with multiply garbage packages which are in reality not needed. And nobody want to install it only to have posibility to start OBS.

**Comment by farnoy** [comment]
Just experiencing this issue now - so this is a regression that's been fixed nearly two months ago but there's still no stable release since then that includes it? How is it not a red flag when some distros are pulling in patches like this directly?

**Comment by stephematician** [comment]
> Just experiencing this issue now - so this is a regression that's been fixed nearly two months ago but there's still no stable release since then that includes it? How is it not a red flag when some distros are pulling in patches like this directly?

@farnoy - I would be a little frustrated, too. I can accept a little bit of muddling around if I'm on a rolling distro, but, yes, even _Debian Trixie_ (testing) has backported this fix. 

I think it's clear there won't be releases between now and 31.1 (which will have this fix). So I guess fingers crossed OBS 31.1 lands soon 🤞!

**Comment by jpVm5jYYRE1VIKL** [comment]
Well done OBS . IN current fresh kernel not possble anymore to use old v4l2loopback-0.13.2 . So DKMS not build anymore. 
OBS completely broken and no release.

**Comment by tiberium-v** [comment]
> Well done OBS . IN current fresh kernel not possble anymore to use old v4l2loopback-0.13.2 . So DKMS not build anymore. OBS completely broken and no release.

That is the reason for the LTS Kernel on a bleeding edge distro... and the fix is in the beta and target the supported platform Linux:Ubuntu and Linux:Flatpak. 

All other obs packages are not provided by the obs team itself. So when a distro use an incompatible dependency, they have to fix it - what some distro already did.

**Comment by stephematician** [comment]
> Well done OBS . IN current fresh kernel not possble anymore to use old v4l2loopback-0.13.2 . So DKMS not build anymore. OBS completely broken and no release.

The solution in your case is either; roll back the kernel (and then loopback), or use flatpak (which I note you don't want to do), or build OBS. If you don't like having development libraries sitting around on your system, you can build within a container instead (then delete the container).

**Comment by tqwewe** [comment]
Thanks so much for this PR!

I'm just going to share a snippet of nix code if anyone wants to use this PR before OBS 31.1 is released:
```nix
programs.obs-studio.package = unstable.obs-studio.overrideAttrs (oldAttrs: {
  src = pkgs.fetchFromGitHub {
    owner = "obsproject";
    repo = "obs-studio";
    rev = "12c6febae21f369da50f09d511b54eadc1dc1342"; # https://github.com/obsproject/obs-studio/pull/11906
    sha256 = "sha256-DIlAMCdve7wfbMV5YCd3qJnZ2xwJMmQD6LamGP7ECOA=";
    fetchSubmodules = true;
  };
  version = "31.1.0-beta1";
  patches = builtins.filter (
    patch:
    !(
      builtins.baseNameOf (toString patch) == "Enable-file-access-and-universal-access-for-file-URL.patch"
    )
  ) oldAttrs.patches;
});
```

**Comment by dbear496** [comment]
Can we please get a hotfix release for this? Virtual camera has been **broken** for 4 months, and for 2 months it has been fixed in master but no release. How hard could it be to release a 31.0.1, instead of having each user individually go through installing the pre-release version manually.
