### PR TITLE
Don't trigger hotkeys without modifiers if user is holding down modifiers (strict)

### LINKED ISSUE #4408: Hotkeys trigger even when extra meta/modifier keys are held
### Operating System Info

Windows 10

### Other OS

_No response_

### OBS Studio Version

26.1.2

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

there is no need

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

1) Assign F3 to start recording
2) Assign ALT+F3 to start virtual cam
3) When pressing ALT+F3, start virtual cam but not start recording.

### Current Behavior

Because OBS treats ALT+F3 as F3 as well, both start v cam and start recording fire when hitting ALT+F3

### Steps to Reproduce

Already described in expected behaviour.

### Anything else we should know?

Support channel members in Discord said it is expected behaviour. I politely discord.

### PR DESCRIPTION
**Pull request by OldBaldGeek**
### Description
(This description has been revised from the original, since a proposed UI component has been removed)
Trigger hotkeys only when the key and modifiers pressed by the user exactly match the hotkey definition.

### Motivation and Context

To fix #4408.

Suppose a user defines hotkey actions for "1", "Ctrl-1", "Alt-1", and "Ctrl-Alt-1." With the code in OBS 27 or earlier, if they then press "Ctrl-Alt-1", ALL FOUR actions will be triggered, in an order that may change between runs of OBS (presumably due to how the json is loaded).

While there may be some use case for this, requiring exact matches greatly expands the number of actions that can be invoked independently by hotkeys.

Bug reports
[https://github.com/obsproject/obs-studio/issues/4408](url)
[https://obsproject.com/mantis/view.php?id=925](url)
[https://obsproject.com/mantis/view.php?id=1468](url)
[https://obsproject.com/mantis/view.php?id=1571](url) (duplicate of 1468)

Forum posts complaining about the current behavior
[https://ideas.obsproject.com/posts/...at-ctrl-alt-x-doesnt-trigger-ctrl-x-and-alt-x](url)
[https://obsproject.com/forum/thread...iably-for-scene-selection.146242/#post-535412](url)
[https://obsproject.com/forum/threads/hotkey-modifier-bug.79197/#post-333409](url)
[https://obsproject.com/forum/threads/please-fix-the-hotkeys.79150/#post-333256](url)
[https://obsproject.com/forum/threads/hotkey-modifier-issue.78002/#post-329251](url)

There is a pull request from 2020 that attempts to fix this 
[https://github.com/obsproject/obs-studio/pull/2785](url)
This pull has a number of problems, both in functionality and in coding), as noted in my comment on the pull request.

### How Has This Been Tested?

Tested using
- A scene collection with scenes showing white text at different positions
- A Lua script that logs changes to the Program scene, and with handlers for four hotkeys that simply log the hotkey.

After assigning hotkeys with various modifiers to change scenes and trigger the Lua script, you can observe the script log window and see the behavior of v27 and modified code. In many cases you can see flashes caused by transient scene switching when in v28, or with the fix in legacy mode.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [X] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [X] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [X] My code is not on the master branch.
- [X] The code has been tested.
- [X] All commit messages are properly formatted and commits squashed where appropriate.
- [X] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by Fenrirthviti** [comment]
Please squash your commits and title them appropriately per the contributing document.

**Comment by cg2121** [comment]
I really don't think this should be an option, as it was a bug that caused the modifier problems in the first place. I don't see any use case where the user would want it otherwise.

**Comment by OldBaldGeek** [comment]
> 
> 
> I really don't think this should be an option, as it was a bug that caused the modifier problems in the first place. I don't see any use case where the user would want it otherwise.

Like you, I do not see a use case for the current mode. However, there seem to be some defenders of this mode of operation among the comment on issue 4408 and in the forum, and I thought preserving the current mode might satisfy more people.

**Comment by Fenrirthviti** [comment]
Since this is a bug fix, I'd also say it should not be an option. There are plenty of workarounds for preserving the old behavior (by just adding multiple hotkeys) that it doesn't need the added complexity.

**Comment by OldBaldGeek** [comment]
I am new to github and open source, so I could use some help:

1. I didn't see anything about squashing in the OBS development docs or in the "how to do pull requests" tutorials I looked at. Can anyone suggest any process documents or tutorials to guide me?
  
2. Sorry I muffed the commit titles. My commits included changes to libobs, and to ui. For a commit like that, or in a squash of multiple commits to various components, should I include BOTH in the commit title?

3. There are several comments above suggesting that hotkey mode should not be an option. That would eliminate several of the files in my request. If we decide to go that way, do I abandon this pull request in favor of a new one, or revert the unneeded changes and keep going here?

**Comment by Fenrirthviti** [comment]
No worries! Completely understand being new to all this, it can be a bit overwhelming. Answering best I can in order here:

1: Squashing/rebasing and renaming commits, as well as force-pushing branches to amend are basic functionality provided by Git itself, not necessarily github or specific to the repo, so we don't have any guides ourselves on it.

https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

You'll want to squash the commits using an interactive rebase, selecting the squash action, and then force-push the branch to update. It will automatically update this PR. If that guide isn't sufficient, the keywords "squash commits" are standard terminology, and there's thousands of tutorials available on it.

Naming conventions and commit prefix guidelines are in our contributing document. Best practice is to usually just look at the history of the file you're modifying to see what the format/prefix is for previous modifications to that file.

2: The gist is that you want to group commits by logical function, not necessarily by file. Since all of these modifications, despite being in separate files, are for the same relatively minor change, you'd make them all in a single commit.

3: If you squash/rebase after making changes it's not necessary to make a new pull request. Force-pushing those changes to your github repo after making them locally will overwrite the previous changes, so no need to make a new PR for them.

As a final note, we have quite an active developer community on our [Discord](https://obsproject.com/discord) and I'm sure folks would be happy to help with any additional questions you might have in the #development channel.

**Comment by OldBaldGeek** [comment]
>> I really don't think this should be an option, as it was a bug that caused the modifier problems in the first place.

Since day 1, struct obs_core_hotkeys has had a bool strict_modifiers. My two-line change to obs-hotkeys.c corrects a bug in processing when strict_modifiers is true. 

Currently, the only way to SET strict_modifiers is via the (undocumented) function obs_hotkey_enable_strict_modifiers, which isn't called from within OBS, but IS exported to Lua and Python, so one might argue that there was some intent of this being an option.

But if we don't want a UI option, I see a couple options after removing my proposed UI additions:

1. Leave strict_modifiers in place, along with obs_hotkey_enable_strict_modifiers, but with my logic corrections, and adding code to set strict_modifiers true at startup (or perhaps to load it from global.ini as 06da87e... does)  A UI option could be added in the future, should a plausible use case for legacy behavior be identified.

2. Remove strict_modifiers, obs_hotkey_enable_strict_modifiers and related code. This would also remove obs_hotkey_enable_strict_modifiers from the Lua and Python interface

Option two leads to simpler code going forward, but about a dozen changes, adding some risk to this pull.

Does OBS development culture argue one way or the other?

**Comment by Warchamp7** [comment]
Weighing in as the resident UX person, I do not think this should be an option. As far as I'm concerned the current behavior is a bug and this is a fix.

Jim can weigh in on whether it should still exist internally for Lua / Python, but this shouldn't be an available toggle in the UI

**Comment by ClayJarCom** [comment]
Okay, I've been sitting around watching this bug fix for months like it's an official Red Ryder, carbine action, 200-shot, range model air rifle, with a compass in the stock and this thing that tells time.  Is there anything a normal person like me can do to help this along?

In our streaming control room, we have a whole deck of custom panels that we use to control various parts of the stream.  They're built using Raspberry Pi Pico boards that send keyboard codes via USB, with the keyboard codes assigned as hotkeys in OBS.  One board, for example, is a large panel with 45 buttons, each of which triggers a particular name in a highly customized "Animated Lower Thirds" system.  Having physical buttons assigned to the dozens of potential speakers that could have the floor without warning really helps us stay on top of our school board meeting streams.

I _could_ rebuild our stack so it does all the triggering outside OBS, but that would just add potential failure points.  It would be _very_ useful if this bug fix were applied, as that would _vastly_ increase the number of non-conflicting key combinations we can use for our wonderfully large and useful physical interfaces.  It's a bit of a niche case to most observers, I imagine, which is why the bug survives, but fixing it would make at least some of us extremely grateful.

So, is there anything I can do to help this along?  I really don't want it to get pushed back again, and I promise, I won't shoot my eye out.

File: libobs/obs-hotkey.c [hunk 1]
```diff
@@ -1194,8 +1194,11 @@ static inline bool modifiers_match(obs_hotkey_binding_t *binding,
...
 {
 	uint32_t modifiers = binding->key.modifiers;
-	return !modifiers ||
-	       (!strict_modifiers && (modifiers & modifiers_) == modifiers) ||
+	// If not strict, require only the modifiers (including NO modifiers)
+	//   requested by the hotkey definition. (legacy behavior)
+	// If strict, the current modifiers (including NO modifiers) must
+	//   match the hotkey definition. ("shortcut" behavior)
+	return (!strict_modifiers && (modifiers & modifiers_) == modifiers) ||
 	       (strict_modifiers && modifiers == modifiers_);
```
Comment (norihiro) [inline libobs/obs-hotkey.c:1202]:
```suggestion
	if (!strict_modifiers)
		return !modifiers || (modifiers & modifiers_) == modifiers;
	else
		return modifiers == modifiers_;
```
Rather than adding comments, I'd like to recommend to use an `if`-`else` statement.

Comment (norihiro) [reply libobs/obs-hotkey.c:1202]: To reviewers,
`!modifiers || (modifiers & modifiers_) == modifiers` is equivalent to `(modifiers & modifiers_) == modifiers` so that it is ok to remove `!modifiers ||`.

Comment (norihiro) [reply libobs/obs-hotkey.c:1202]: I think squash/rebase is preferable in this project to keep the history of the master branch as simple as possible.

Comment (OldBaldGeek) [reply libobs/obs-hotkey.c]: if/then incorporated, squash/rebase done

**Comment by gxalpha** [comment]
Seeing this makes me wonder why there even is an internal option for `strict_modifiers`.
Currently, the only way to set it to true is when a script or plugin calls `obs_hotkey_enable_strict_modifiers`. As Warchamp said this shouldn't be a user-facing option, I'm wondering if it should even be a developer facing option. What we're currently doing is just wrong, personally I don't think there's a need to keep it around honestly.
Not speaking for the team here, but I wouldn't mind deprecating `obs_hotkey_enable_strict_modifiers` as part of this PR.

**Comment by OldBaldGeek** [comment]
> Seeing this makes me wonder why there even is an internal option for `strict_modifiers`.

Like you, I don't see a use case for non-strict modifiers. However:
1. The author of the code presumably thought that strict/non-strict should be an option or they wouldn't have included the strict-modifiers flag
2.  When I first asked about this behavior on the OBS forum [https://obsproject.com/forum/threads/hotkeys-using-control-and-alt-dont-work-reliably-for-scene-selection.146242/#post-535398](url), FerretBomb responded that it was SUPPOSED to be non-strict, so at least they presumably like it that way. Retaining the flag and the function to set/clear it lets people do that.
3. Removing all traces of strict_modifiers would entail more changes to obs_hotkey.c, potentially adding risk. I would argue that it also changes this PR from a "bug fix" to a "bug fix, and removal of (admittedly lame) feature"

If the team want me to remove the option, I can do so. 

(Which makes me ask a more general question: how do I differentiate between comments, suggestions, and the decisions of the team?)

**Comment by gxalpha** [comment]
> Removing all traces of strict_modifiers would entail more changes to obs_hotkey.c, potentially adding risk. I would argue that it also changes this PR from a "bug fix" to a "bug fix, and removal of (admittedly lame) feature"

Sorry, I wasn't suggesting you remove all traces of it (as that would break the API), but rather just adding an `OBS_DEPRECATED` to the function export so that we could safely remove it at a later stage. However, for that it would first have to be decided that want to get rid of it, and don't want to make such a call myself (so for now, no action is required. I noted it mostly so that others can leave their thoughts on it).

> When I first asked about this behavior on the OBS forum [https://obsproject.com/forum/threads/hotkeys-using-control-and-alt-dont-work-reliably-for-scene-selection.146242/#post-535398](https://github.com/obsproject/obs-studio/pull/url), FerretBomb responded that it was SUPPOSED to be non-strict, so at least they presumably like it that way. Retaining the flag and the function to set/clear it lets people do that.

I read the forum comment and I'm a bit torn on it. They are mostly suggesting that the current behaviour is correct and that what this PR would introduce the wrong behaviour (and it already got decided that it doesn't further up in the thread; this PR does it correctly). I don't think having a feature that can only be enabled via a script makes sense from a UX perspective - I feel it should either be an option that's exposed to the user or not at all. But again, likely not my decision.

> (Which makes me ask a more general question: how do I differentiate between comments, suggestions, and the decisions of the team?)

Difficult to say, which is why I try to make it very clear when I'm not in a position to make calls. If someone wants you to make changes, they'll usually express it in a "Please do x" / "Try to avoid y" way, and often use the "Request changes" button on GitHub. Could look like this:
image
Otherwise, they are probably suggestions.

**Comment by norihiro** [comment]
> I don't think having a feature that can only be enabled via a script makes sense from a UX perspective - I feel it should either be an option that's exposed to the user or not at all.

To be honest, I second gxalpha's idea to have an option to expose to users. However, I'm just one of contributors. You can freely ignore comments, suggestions, and even request-changes from outside members or owner.

According to Warchamp7's https://github.com/obsproject/obs-studio/pull/5095#issuecomment-899800988, current implementation is ok. They think it's a bug that should be fixed by this PR.

**Comment by Fenrirthviti** [comment]
FerretBomb doesn't speak for and isn't part of the OBS development team, so comments from them should be largely ignored with it comes to development decisions. Warchamp is currently the final say in any user-facing UI/UX decisions. That's not to say we don't welcome discussion that might contradict with those decisions, however.

**Comment by gxalpha** [comment]
> To be honest, I second gxalpha's idea to have an option to expose to users.

I wasn't saying that this should be exposed to the user. I agree with Warchamp, and I think that if it's not exposed to the user it shouldn't be exposed via functions either. On a second thought, this is perhaps a bit out of scope for this PR. Should we decide to deprecate `obs_hotkey_enable_strict_modifiers` we'll do it after this PR.

As is, this PR is probably fine feature wise. I can't test on macOS since hotkeys with modifiers (and modifier-only hotkeys) are broken there, but this is not the fault of this PR.
