### PR TITLE
UI: Explicitly convert profile config path via u8path

### LINKED ISSUE #11363: [Nightly Build] OBS crashes when using non-ASCII characters in profile name
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

Git

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://gist.github.com/style1925/ecc6a1acb1dda1602c2bd6389576ee69

### OBS Studio Crash Log URL

https://gist.github.com/style1925/06c56b562b0ec52715212b98c5bc7d93

### Expected Behavior

OBS does not crash

### Current Behavior

OBS crashes

### Steps to Reproduce

1. Nightly Build Download.
2. Launch OBS.
3. Use a profile name with non-ASCII characters, e.g., '日本語', 'てすと', or 'テスト'.
*日本語 (kanji) = Japanese / てすと (hiragana) = test / テスト (katakana) = test
4. Exit OBS.
5. OBS crashes and will not Launch.

If the profile folder already uses non-ASCII characters.
1. Nightly Build Download.
2. OBS crashes and will not Launch.

### Anything else we should know?

Change the folder name of the profile to English and OBS will start.
Example: テスト (katakana) → test

This issue does not occur in version 30.2.3.

memo (if the profile name is “test”)
Pressing “File → Show Profile Folder” does not open the folder for the selected profile.

Version 30.2.3
C:\Users\Admin\AppData\Roaming\obs-studio\basic\profiles\test
test folder opens

Version 31.0 (Nightly)
C:\Users\Admin\AppData\Roaming\obs-studio\basic\profiles
test folder is not opened

### PR DESCRIPTION
**Pull request by derrod**
### Description

Fixes implicit conversion from `std::string` to `std::filesystem::path`, which is incorrect on Windows due to lack of UTF-8 to UTF-16 conversion.

### Motivation and Context

Fixes #11363

### How Has This Been Tested?

Created a profile with one of the names provided by the reporter.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: UI/window-basic-main-profiles.cpp [hunk 1]
```diff
@@ -333,8 +333,9 @@ void OBSBasic::RefreshProfileCache()
 			candidateName = entry.path().filename().u8string();
 		}
 
+		auto candidatePath = std::filesystem::u8path(profileCandidate);
 		foundProfiles.try_emplace(candidateName, OBSProfile{candidateName, entry.path().filename().u8string(),
-								    entry.path(), profileCandidate});
+								    entry.path(), candidatePath});
```
Comment (PatTheMav) [inline UI/window-basic-main-profiles.cpp:338]: This change is good in two ways - it fixes the crash and also avoids relying on implicit type conversion by the `OBSProfile` constructor.

**Review by PatTheMav — APPROVED** [review]

**Comment by RytoEX** [comment]
Are there any further fixes coming, or can this be merged as is?

**Comment by derrod** [comment]
> Are there any further fixes coming, or can this be merged as is?

I just did a quick update with the proposed cleanup to avoid the unnecessary path->string->path round-trip.

File: UI/window-basic-main-profiles.cpp [hunk 2]
```diff
@@ -314,13 +315,11 @@ void OBSBasic::RefreshProfileCache()
 			continue;
 		}
 
-		std::string profileCandidate;
-		profileCandidate.reserve(entry.path().u8string().size() + OBSProfileSettingsFile.size() + 1);
-		profileCandidate.append(entry.path().u8string()).append("/").append(OBSProfileSettingsFile);
+		auto profileCandidate = entry.path() / profileSettingsFile;
```
Comment (PatTheMav) [inline UI/window-basic-main-profiles.cpp:318]: Shouldn't this be `const` as it's not mutated anywhere?

Comment (derrod) [reply UI/window-basic-main-profiles.cpp:318]: It could be constified, yeah. It could probably also be `std::move`d in the construction of `OBSProfile`.

**Review by RytoEX — APPROVED** [review]
