### PR TITLE
linux-pipewire: Make camera framerate non-mandatory

### LINKED ISSUE #12700: PipeWire IPU6 camera broken in 32.0.1 (Linux)
### Operating System Info

Other

### Other OS

Arch Linux

### OBS Studio Version

32.0.0

### OBS Studio Version (Other)

32.0.1

### OBS Studio Log URL

https://obsproject.com/logs/76VBNB3dhG4zQLKy

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

PipeWire IPU6 camera was working in previous versions.

### Current Behavior

PipeWire IPU6 camera is broken in latest version. There is no video output, just black rectangle.

### Steps to Reproduce

1. Open OBS
2. Select PipeWire Camera source
3. Only black rectangle is visible in video preview

### Anything else we should know?

_No response_

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Formats can be without any framerate options, so ensure that those are not required.

> [!NOTE]  
> **Review without whitespace changes is recommended.**

### Motivation and Context

May fix #12700

### How Has This Been Tested?

I don't have any device with this kind of framerate-less format, but my cheap capture card still show framerates properly.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [ ] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/linux-pipewire/camera-portal.c [hunk 1]
```diff
@@ -845,7 +850,16 @@ static bool format_selected(void *data, obs_properties_t *properties, obs_proper
...
 
 	property = obs_properties_get(properties, "framerate");
-	framerate_list(device, camera_source->format.spa_format, &camera_source->resolution.rect, property);
+	obs_property_set_modified_callback2(property, NULL, NULL);
+
+	has_framerates =
+		framerate_list(device, camera_source->format.spa_format, &camera_source->resolution.rect, property);
+	obs_property_set_enabled(property, has_framerates);
+
+	if (has_framerates) {
```
Comment (pobrn) [inline plugins/linux-pipewire/camera-portal.c:859]: I think `obs_pipewire_stream_set_framerate()` should be called with `NULL` to remove any previously set frame rate completely if `!has_framerates`.

Comment (tytan652) [reply plugins/linux-pipewire/camera-portal.c:859]: Good idea, added in the next push.

File: plugins/linux-pipewire/camera-portal.c [hunk 2]
```diff
@@ -378,61 +373,68 @@ static void camera_format_list(struct camera_device *dev, obs_property_t *prop)
 		obs_data_set_int(data, "height", resolution.height);
 
 		framerate_prop = spa_pod_find_prop(p->param, NULL, SPA_FORMAT_VIDEO_framerate);
-		if (!framerate_prop)
-			continue;
+		if (framerate_prop) {
+			struct spa_pod *framerate_pod;
+			uint32_t n_framerates;
```
Comment (PatTheMav) [inline plugins/linux-pipewire/camera-portal.c:378]: What does the `n_` stand for here? The variable stands out as the others surrounding it use the `framerate_<semantic meaning>` form, but this one uses an unexplained single letter as a prefix.

File: plugins/linux-pipewire/camera-portal.c [hunk 3]
```diff
@@ -378,61 +373,68 @@ static void camera_format_list(struct camera_device *dev, obs_property_t *prop)
...
+			enum spa_choice_type framerate_choice;
+			const struct spa_fraction *framerate_values;
+			g_autoptr(GArray) framerates = NULL;
+
+			framerate_pod = spa_pod_get_values(&framerate_prop->value, &n_framerates, &framerate_choice);
+			if (framerate_pod->type != SPA_TYPE_Fraction) {
+				blog(LOG_WARNING, "Framerate is not a fraction");
```
Comment (PatTheMav) [inline plugins/linux-pipewire/camera-portal.c:385]: Is `blog` a macro here or the native `libobs` function call? The message used here is too ambiguous otherwise and would require a supporter to search source code for the specific invocation of `blog` to figure out which framerate this refers to.

File: plugins/linux-pipewire/camera-portal.c [hunk 4]
```diff
@@ -378,61 +373,68 @@ static void camera_format_list(struct camera_device *dev, obs_property_t *prop)
...
+			framerates = g_array_new(FALSE, FALSE, sizeof(struct spa_fraction));
 
-		framerate_values = SPA_POD_BODY(framerate_pod);
-		framerates = g_array_new(FALSE, FALSE, sizeof(struct spa_fraction));
+			switch (framerate_choice) {
+			case SPA_CHOICE_None:
+				g_array_append_val(framerates, framerate_values[0]);
+				break;
+			case SPA_CHOICE_Range:
+				blog(LOG_WARNING, "Ranged framerates not supported");
```
Comment (PatTheMav) [inline plugins/linux-pipewire/camera-portal.c:397]: See above - log messages, particularly public ones (`WARNING` and `ERROR`) need to carry enough context to be valuable to users attempting to self-help or supporters as our logging system is non-structured and cannot carry context information otherwise.

File: plugins/linux-pipewire/camera-portal.c
Comment (PatTheMav) [inline plugins/linux-pipewire/camera-portal.c:1]: If I read this right, this change will ensure that even if no framerate properties are available that at the very least an entry with the format string is added to the property list so the combobox isn't empty?

File: plugins/linux-pipewire/camera-portal.c (hunk 3 above)
Comment (tytan652) [reply plugins/linux-pipewire/camera-portal.c:385]: Out of scope, those lines are marked as addition due to whitespace change

File: plugins/linux-pipewire/camera-portal.c (hunk 4 above)
Comment (tytan652) [reply plugins/linux-pipewire/camera-portal.c:397]: Out of scope, those lines are marked as addition due to whitespace change

File: plugins/linux-pipewire/camera-portal.c (hunk 2 above)
Comment (tytan652) [reply plugins/linux-pipewire/camera-portal.c:378]: The number of values that will be found in pod a few lines later.

Those lines are also just moved around in the `if` scope.

File: plugins/linux-pipewire/camera-portal.c
Comment (tytan652) [reply plugins/linux-pipewire/camera-portal.c:1]: #12700 introduce the assumption that a format always had a framerates property, but this is not the case which leads to a regression between 31.1 and 32.

**Comment by wanhongqing123** [comment]
#12700 There are two problems here: one is the UI display, and the other is that Linux does not support RGBX.

See Log：
Clipboard_Screenshot_1767526483
I would also like you to check if issue #12781, regarding the lack of support for RGBx, has been resolved.

**Review by GeorgesStavracas — APPROVED** [review]
