### PR TITLE
vlc-video: Fix video rotation and aspect ratio

### LINKED ISSUE #3843: OBS doesn't use aspect ratio metadata in video files when using vlc video source
## Platform
Operating system and version: Windows 10
OBS Studio version: 26.0.2.

## Expected Behavior
Use aspect ratio of media file's metadata

## Current Behavior
aspect ratios in video files metadata does get ignored. the used aspect ratio gets defined by the resolution

## Steps to Reproduce
1. use any videofile
2. change the aspect ratio by e.g. mkvtoolnix to anything else that's not the resolution
3. play it in VLC standalone w/o OBS -> ar gets respected
4. play it in VLC built in -> ar gets ignored

## Additional information
I'm using OBS to stream a bunch of video files with different aspect ratios. Some older files e.g. dvd muxes have different aspect ratios than the video file resolution. I need a way to make OBS have an option to use the aspect ratio metadata, that the video files have.

### LINKED ISSUE #5250: VLC Video Source renders portrait video with incorrect aspect ratio
### Operating System Info

Windows 10

### Other OS

Also macOS 11.5.2 on M1

### OBS Studio Version

27.0.1

### OBS Studio Log URL

https://obsproject.com/logs/iMtIcCPaUcbCFDtI

### Expected Behavior

Portrait video from phone (mov/mp4 containing h.264/AVC and h.265/HEVC) should be rendered correctly in VLC Video Source.

### Current Behavior

Video is rotated to the correct orientation, but height and width are taken from the unrotated source, so the image is stretched horizontally.

image

### Steps to Reproduce

1. VLC Video Source to a scene.
2. Select the attached video as source.
3. Observe incorrect aspect ratio.

https://user-images.githubusercontent.com/18594548/132258725-4ef35599-fab2-44c3-8262-60d5914ea876.MOV

### Anything else we should know?

Metadata in the affected videos specifies `rotation` of `90` or `270`.

Using VLC source to stream user-uploaded content (which is often but not always taken in portrait on a phone) and "fit to screen" transform, so I can't work around by applying fixed transforms as the media dimensions and orientation change constantly.

VLC itself plays the videos correctly.

Reproduced on Windows 10 and MacOS 15.2.1 on M1.

### PR DESCRIPTION
**Pull request by pmcgaley**
### Description
Fixes rotation and aspect ratio of VLC Video Source videos. Only works for local video files - video streams will still be incorrect (https://github.com/obsproject/obs-studio/issues/2933) and will need to be dealt with separately.

Cause: previously, the buffer size passed from libvlc was being used as the video size, but this was often incorrect as the buffer size could be rounded up to the next multiple of 32. This was then "fixed" by getting the pixel size of the original video file, however it didn't take into account rotation or aspect ratio attributes. This PR addresses this.

#### Before
image
#### After
image

### Motivation and Context
Fixes #5250 - portrait videos (e.g. from phones) being rendered with incorrect aspect ratio.
Also fixes #3843

### How Has This Been Tested?
Tested on macOS 11.5.2 on Intel and 12.3.1 on Apple silicon. Ran several videos of different dimensions and rotations through VLC Video Source and aspect ratio is now correct for all of them.

Test videos generated with:

```
ffmpeg -f lavfi -i "testsrc=duration=10,drawtext=text='rotation 180':fontcolor=white,transpose=clock,transpose=clock" -c libx264 -f mpegts - | ffmpeg -i - -c copy -metadata:s:v rotate=180 rotation180.mp4
ffmpeg -f lavfi -i "testsrc=duration=10,drawtext=text='rotation 270':fontcolor=white,transpose=clock" -c libx264 -f mpegts - | ffmpeg -i - -c copy -metadata:s:v rotate=90 rotation270.mp4
ffmpeg -f lavfi -i "testsrc=duration=10,drawtext=text='rotation 90':fontcolor=white,transpose=cclock" -c libx264 -f mpegts - | ffmpeg -i - -c copy -metadata:s:v rotate=270 rotation90.mp4
ffmpeg -f lavfi -i "testsrc=duration=10,drawtext=text='aspect ratio':fontcolor=white,scale=iw*2:ih,setsar=1/2" aspect.mp4
```

Add to VLC Video Source - these should all render the same size:

https://user-images.githubusercontent.com/18594548/166231717-7b57e1b7-4ae6-4e7d-bd10-35d24841e975.mp4

https://user-images.githubusercontent.com/18594548/166231721-3f56123d-9012-479b-870a-4ce18c8c0143.mp4

https://user-images.githubusercontent.com/18594548/166231722-e8d1a670-4291-48a6-86ab-ebbb2cce433e.mp4

https://user-images.githubusercontent.com/18594548/166231723-8cab08c4-32cc-462e-ae42-2ba739484ec1.mp4

Other example videos:

https://user-images.githubusercontent.com/18594548/132258725-4ef35599-fab2-44c3-8262-60d5914ea876.MOV

https://user-images.githubusercontent.com/18594548/166114798-722719c5-d38f-4f07-af25-d920d8c957f3.mov

### Types of changes
Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/vlc-video/vlc-video-plugin.c [hunk 1]
```diff
@@ -24,8 +24,10 @@ LIBVLC_MEDIA_NEW_PATH libvlc_media_new_path_;
 LIBVLC_MEDIA_NEW_LOCATION libvlc_media_new_location_;
 LIBVLC_MEDIA_ADD_OPTION libvlc_media_add_option_;
 LIBVLC_MEDIA_RELEASE libvlc_media_release_;
-LIBVLC_MEDIA_RELEASE libvlc_media_retain_;
+LIBVLC_MEDIA_RETAIN libvlc_media_retain_;
```
Comment (pmcgaley) [inline plugins/vlc-video/vlc-video-plugin.c:27]: this just seems to have been a copy/paste error

**Review by RytoEX — CHANGES_REQUESTED** [review]
Nit: Please use ending punctuation in the commit message body.

**Comment by pmcgaley** [comment]
> Nit: Please use ending punctuation in the commit message body.

Third time lucky. Wasn't sure if I should hit re-request review on a nit, apologies if it was inappropriate

File: plugins/vlc-video/vlc-video-source.c [hunk 2]
```diff
@@ -382,6 +382,57 @@ static void vlcs_video_display(void *data, void *picture)
...
+			/* Adjust for Sample Aspect Ratio (SAR) */
+			if (track->video->i_sar_num > 0 &&
+			    track->video->i_sar_den > 0) {
+				display_width = display_width *
+						track->video->i_sar_num /
+						track->video->i_sar_den;
+			}
+
+			/* ORIENT_IS_SWAP definition taken from VLC */
+			if ((track->video->i_orientation & 4) != 0) {
```
Comment (WizardCM) [inline plugins/vlc-video/vlc-video-source.c:419]: Please include the vlc_es header and use `ORIENT_IS_SWAP()` directly.

File: plugins/vlc-video/vlc-video-plugin.c (hunk 1 above)
Comment (RytoEX) [reply plugins/vlc-video/vlc-video-plugin.c:27]: Is this change related to the other changes in this PR?

Comment (pmcgaley) [reply plugins/vlc-video/vlc-video-plugin.c:27]: Only in passing. There's no functional difference because they both resolve to the same type

```
typedef void (*LIBVLC_MEDIA_RETAIN)(libvlc_media_t *p_md);
typedef void (*LIBVLC_MEDIA_RELEASE)(libvlc_media_t *p_md);
```

Note that vlc-video-plugin.h already declares it as

```
extern LIBVLC_MEDIA_RETAIN libvlc_media_retain_;
```

So it's pretty clearly just a typo. Happy to revert if preferred.

File: plugins/vlc-video/vlc-video-source.c (hunk 2 above)
Comment (pmcgaley) [reply plugins/vlc-video/vlc-video-source.c:419]: I couldn't figure out how to do that, or even if I should since it doesn't appear to be part of the exported libvlc stuff, hence copying the logic here. I just spent another chunk of time trying to figure it out and failed and I'm going to have to give up at this point. If it's easy/appropriate do to could you point me in the right direction please?

Comment (pmcgaley) [reply plugins/vlc-video/vlc-video-source.c]: I've pushed a different, more explicit implementation that I actually prefer to VLC's own - I never really liked the obscure bitmask check anyway, and this one doesn't require anything that's not included with libvlc.h. Will that do?

**Comment by pmcgaley** [comment]
added some more test videos, generated with ffmpeg

File: plugins/vlc-video/vlc-video-plugin.c (hunk 1 above)
Comment (RytoEX) [reply plugins/vlc-video/vlc-video-plugin.c:27]: Revert isn't needed. I was just trying to understand it better to decide if it warranted its own commit so that `git blame` is clearer.
