### PR TITLE
libobs: Set channel layout for remux output

### LINKED ISSUE #10384: auto-remuxing mkv with PCM produces invalid file
### Operating System Info

Windows 11

### Other OS

_No response_

### OBS Studio Version

30.1.0

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/lTuF3pnasBavtZul

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

Auto-remuxing should produce a playable file

### Current Behavior

When recording to mkv with PCM 32 bit float with auto-remuxing on windows, the remuxed file is an invalid .mp4 file.
As can be seen in the log, OBS' media source itself refuses to play it, so this is likely not an issue of player support

### Steps to Reproduce

1. Enable auto-remux and PCM 32-bit audio encoder
2. Record
3. Try playing the remuxed file.
...

### Anything else we should know?

This does not reproduce on ubuntu 22.04, presumably because of the ifdef that checks for libavformat version

### PR DESCRIPTION
**Pull request by derrod**
### Description

Set the channel layout when remuxing.

### Motivation and Context

Fixes muxing PCM in MP4 failing.

Fixes #10384

### How Has This Been Tested?

Remuxed file that previously failed.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: libobs/media-io/media-remux.c [hunk 1]
```diff
@@ -152,6 +152,18 @@ static inline bool init_output(media_remux_job_t job, const char *out_filename)
 			// Otherwise tag 0 to let FFmpeg automatically select the appropriate tag
 			out_stream->codecpar->codec_tag = 0;
 		}
+
+		if (in_stream->codecpar->codec_type == AVMEDIA_TYPE_AUDIO) {
+#if LIBAVCODEC_VERSION_INT < AV_VERSION_INT(59, 24, 100)
```
Comment (RytoEX) [inline libobs/media-io/media-remux.c:157]: Writing mostly for my own notes.

It seems `av_get_default_channel_layout` was deprecated in avutil, not avcodec.
https://github.com/FFmpeg/FFmpeg/commit/086a8048061bf9fb4c63943f6962db48175f655c

The version of avcodec when this commit landed was 59.23.100.
https://github.com/FFmpeg/FFmpeg/blob/086a8048061bf9fb4c63943f6962db48175f655c/libavcodec/version.h#L30-L32

The version of avutil was 57.23.100.
https://github.com/FFmpeg/FFmpeg/blob/086a8048061bf9fb4c63943f6962db48175f655c/libavutil/version.h#L81-L83

I suppose this is going based off of the changelog entry where it notes that [the changes for AVCodecParameters occurred in lavc 59.24.100](https://github.com/FFmpeg/FFmpeg/blob/n6.1.1/doc/APIchanges#L352-L360) (add `ch_layout`, deprecate `channels` and `channel_layout`), and we need to account for _that_ change (which this PR is doing). The libraries are normally shipped together rather than updated independently, so this is probably fine.

**Review by RytoEX — APPROVED** [review]
Writing notes for posterity. Will finish review in a moment. Fixes the linked Issue.
