### PR TITLE
libobs: Don't save removed sources

### LINKED ISSUE #2724: [BUG] OBS duplicates scenes and corrupts scene collections when using groups
When using groups with nested scenes in OBS, the conditions can arise where OBS will corrupt both the active scene collection as well as any other scene collections that are configured.  Over time the corruption gathers multiple duplicate copies of scenes and spreads through the collection until finally OBS starts crashing, and eventually wont even start any more, crashing on start every time.  The problem appears to occur primarily with people who use Groups in scenes, which would explain why it isn't more widespread.  People who are more advanced users doing more advanced layered/nested scene setups are most likely to encounter this problem.

The problem for a long time was thought to be caused by 3rd party addons but has now been reproduced with pristine OBS installation without any 3rd party plugins/scripts/filters etc. and we have a reproducible minimal test case to provide.

## Platform

Operating system and version:  Windows 10 x64 (1909)
OBS Studio version:  25.0.4

## Expected Behavior

OBS should never corrupt the active or inactive scene collection configuration data under any circumstances, when users (advanced or otherwise) are using the program to create scenes using built in features in a manner that it permits.

## Current Behavior

OBS will corrupt the scene collection(s) by adding duplicates of a particular scene to the same scene collection, and sometimes spreading those dupes into  other scene collections that are not in use, adding scenes that they don't contain, eventually corrupting the entire scene collections which may become unstable, crash and unusable.

https://obsproject.com/logs/msN9RZEizUNnbt7W

## Steps to Reproduce

I've been working hard to try to make a reproducible test case for this for a while which did not use 3rd party filters etc. but whenever I thought I had a solid test case, it wouldn't always happen, so I've hesitated to report the bug formally until I could nail a reliable test case that was potentially actionable.  I've gotten close recently, but today in Discord user Lindenkron provided a very simple reproducible test case that I was able to reproduce on a fresh pristine OBS install.  Here are the steps:

1.  Create scene collection "Bug Test 1"
2.  Create 2 scenes named "Scene" and "Scene Nested"
3.  In "Scene", add a single Group, and then add scene source "Scene Nested" inside the group.
4.  Create new scene collection and name it "Bug Test 2", with just the default "Scene" present.
5.  Switch back to "Bug Test 1" scene collection.
6.  Drag the "Scene Nested" scene to be above "Scene" in the scenes pane.
7.  Switch back to scene collection "Bug Test 2"
8.  Close OBS, then open OBS back up.

When OBS opens it will be in scene collection "Bug Test 2" which previously only had a single empty scene in it named "Scene".   It now has been corrupted to have "Scene Nested" in it also, which was from scene collection "Bug Test 1".

## Additional information

If you have multiple groups in use and more complex setup, the amount and level of corruption that occurs becomes much larger, with many scenes being copied into other scene collections, and multiple duplicates of them showing up and spreading throughout different scene collections in OBS, until the program becomes unstable and eventually wont even start anymore, crashing on startup until you delete the Scene collection configuration directory and start over from scratch until the problem starts to happen again.

This problem appears to be related to the use of Groups, which seems to be a feature that has a number of bugs related to it.  As a heavy user of this feature I'll try to do my part to file bug reports for any other Group related problems I encounter in the future and hopefully we can work towards stabilizing these awesome features.

Thanks so much to the OBS developers, Xaymar, Surn, Lindenkron, MrGregles, ihazabeard, R1CH and any other creators or developers who have helped to diagnose this problem and/or work on fixing it.  This will mean a lot to so many people out there when it's eventually fixed, and will lead to a huge amount of creativity being possible in OBS.  Very much appreciated guys, thanks for looking into this!

### PR DESCRIPTION
**Pull request by exeldro**
### Description
Don't save removed sources

### Motivation and Context
Sources can keep references due to various problems like bad plugins.
If that is the case and the source is removed the source should still not be saved.
This does not fix the root problem of #2724 and #2709, but prevents the bad results.

### How Has This Been Tested?
With the steps in #2724

### Types of changes
- Bug fix (non-breaking change which fixes an issue)

### Checklist:
- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.

### CODE REVIEW

**Comment by notr1ch** [comment]
While this does prevent removed items from being saved, the removed items should not be present in the first place. So while this is a workaround, it does not fix the core issue of https://github.com/obsproject/obs-studio/issues/2724.

**Comment by exeldro** [comment]
I agree that this does not fix the root problem of #2724.
Changed the "Motivation and Context" to reflect that.

File: UI/window-basic-main.cpp [hunk 1]
```diff
@@ -3921,6 +3921,7 @@ void OBSBasic::ClearSceneData()
 		return true;
 	};
 
+	obs_enum_scenes(cb, nullptr);
```
Comment (notr1ch) [inline UI/window-basic-main.cpp:3924]: This should perhaps be split into a separate commit, as it is unrelated to saving removed sources.
