### PR TITLE
Contain simde diagnostic pragmas and replace variable-length arrays

### LINKED ISSUE #9160: FTBFS: variable length arrays are treated as errors
### Operating System Info

Other

### Other OS

Debian

### OBS Studio Version

29.1.3

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

n.n.

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

i expect to be able to compile obs-studio with all it's bundled plugins

### Current Behavior

build fails with:

```
cd /build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/obj-x86_64-linux-gnu/plugins/linux-pipewire && /usr/bin/ccache /usr/bin/cc -DENABLE_HEVC -DHAVE_OBSCONFIG_H -Dlinux_pipewire_EXPORTS -I/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/libobs -I/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/obj-x86_64-linux-gnu/config -I/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/deps/glad/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/glib-2.0 -isystem /usr/lib/x86_64-linux-gnu/glib-2.0/include -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/gio-unix-2.0 -g -O2 -ffile-prefix-map=/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -DSIMDE_ENABLE_OPENMP -fopenmp-simd -O3 -Wdate-time -D_FORTIFY_SOURCE=2 -DFFMPEG_MUX_FIXED=\"/usr/lib/x86_64-linux-gnu/obs-plugins/obs-ffmpeg/obs-ffmpeg-mux\" -std=gnu17 -fPIC -Werror -Wextra -Wvla -Wswitch -Wno-error=switch -Wformat -Wformat-security -Wunused-parameter -Wno-unused-function -Wno-missing-field-initializers -fno-strict-aliasing -Werror-implicit-function-declaration -Wno-missing-braces -Wno-error=maybe-uninitialized -mmmx -msse -msse2 -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -D_REENTRANT -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -pthread -MD -MT plugins/linux-pipewire/CMakeFiles/linux-pipewire.dir/pipewire.c.o -MF CMakeFiles/linux-pipewire.dir/pipewire.c.o.d -o CMakeFiles/linux-pipewire.dir/pipewire.c.o -c /build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/plugins/linux-pipewire/pipewire.c
/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/plugins/linux-pipewire/pipewire.c: In function ‘on_process_cb’:
/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/plugins/linux-pipewire/pipewire.c:596:17: error: ISO C90 forbids variable length array ‘offsets’ [-Werror=vla]
  596 |                 uint32_t offsets[planes];
      |                 ^~~~~~~~
/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/plugins/linux-pipewire/pipewire.c:597:17: error: ISO C90 forbids variable length array ‘strides’ [-Werror=vla]
  597 |                 uint32_t strides[planes];
      |                 ^~~~~~~~
/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/plugins/linux-pipewire/pipewire.c:598:17: error: ISO C90 forbids variable length array ‘modifiers’ [-Werror=vla]
  598 |                 uint64_t modifiers[planes];
      |                 ^~~~~~~~
/build/obs-studio-2j3wxb/obs-studio-29.1.3+dfsg/plugins/linux-pipewire/pipewire.c:599:17: error: ISO C90 forbids variable length array ‘fds’ [-Werror=vla]
  599 |                 int fds[planes];
      |                 ^~~
cc1: all warnings being treated as errors
```

The error is obviously triggered because
- the code uses variable length arrays https://github.com/obsproject/obs-studio/blob/19d7a96de38e40d89cc953db84452b53ec63487d/plugins/linux-pipewire/pipewire.c#L614-L617
- the code is compiled with `-Werror -Wvla`
presumable because of https://github.com/obsproject/obs-studio/blob/19d7a96de38e40d89cc953db84452b53ec63487d/cmake/Modules/CompilerConfig.cmake#L110-L113

cmake is invoked with:
```sh
cd obj-x86_64-linux-gnu && cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_SYSCONFDIR=/etc -DCMAKE_INSTALL_LOCALSTATEDIR=/var -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DFETCHCONTENT_FULLY_DISCONNECTED=ON -DCMAKE_INSTALL_RUNSTATEDIR=/run -DCMAKE_SKIP_INSTALL_ALL_DEPENDENCY=ON "-GUnix Makefiles" -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_INSTALL_LIBDIR=lib/x86_64-linux-gnu -DOBS_MULTIARCH_SUFFIX=/x86_64-linux-gnu -DUNIX_STRUCTURE=TRUE -DCMAKE_SKIP_RPATH=TRUE -DDISABLE_UPDATE_MODULE=TRUE -DBUILD_VST=OFF -DENABLE_AJA=OFF -DENABLE_SNDIO=OFF -DENABLE_JACK=TRUE -DOBS_VERSION_OVERRIDE=29.1.3.1-1 -DAPPDATA_RELEASE_DATE=2023-06-27 ..
```

### Steps to Reproduce

https://salsa.debian.org/multimedia-team/obs-studio/-/jobs/4368844

### Anything else we should know?

given that these compiler warnings and errors are mostly for development of obs-studio, should/could they be disabled for release-builds?

### PR DESCRIPTION
**Pull request by tytan652**
### Description

Fixes #9160

- Replace linux-pipewire variable-length arrays with dynamic arrays, those were not generating errors because of our in-tree simde that makes some warning ignored.
- Contain simde diagnostic pragmas

### Motivation and Context

I was trying to use my system simde rather than the in-tree and discover how to reproduce #9160.

So I tried to fix the vla issue and the pragma contamination.

### How Has This Been Tested?

Pipewire captures seems to work fine.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested on Linux.
- [ ] The code has been tested on macOS.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

**Comment by tytan652** [comment]
@PatTheMav, @gxalpha if you have a better fix rather than calming the virtualcam warning, please submit it.

**Comment by PatTheMav** [comment]
There are no vla-related warnings in ObjC/ObjC++ code iirc, so I don't think those need to be fixed.

**Comment by tytan652** [comment]
> I _do_ wonder why we warn about variable-length arrays though and why we consider that an error. If it's supposed to be a warning (because of the care it requires to be used correctly), then it shouldn't be an error, because you're not supposed to fix it, but acknowledge it.

`-Wvla` is added explicitly in CMake, simde just put some mess by making them ignored through pragmas. And `-Werror` intervene so they should be fixed at some point.

**Comment by PatTheMav** [comment]
> > I _do_ wonder why we warn about variable-length arrays though and why we consider that an error. If it's supposed to be a warning (because of the care it requires to be used correctly), then it shouldn't be an error, because you're not supposed to fix it, but acknowledge it.
> 
> `-Wvla` is added explicitly in CMake, simde just put some mess by making them ignored through pragmas. And `-Werror` intervene so they should be fixed at some point.
> 
> Edit: I ping you and Sebastian because of the warning that I met in ObjC/ObjC++.

I get that, my question is why we make it a warning in the first place? I never spent much time pondering that and just carried it forward, but the question is whether we actually need the warning.

**Comment by tytan652** [comment]
Related to #1465

**Comment by PatTheMav** [comment]
> > vla must be avoided at all cost
> 
> Seems like Apple disagrees with that take, since I’m fairly sure what we’re doing is exactly what they expect you to do. I’d agree with Pat here, that warning shouldn’t be added then, at least on macOS (or to macOS-only modules).

I'm not so sure about that, an alternative would be to use `NSMutableData`:
```
NSMutableData *cmioDevices = [NSMutableData dataWithLength:size];
CMIOObjectGetPropertyData(kCMIOObjectSystemObject, &address, 0, NULL, size, &used, &cmioDevices);
        
for (size_t i = 0; i < num_devices; i++) {
    CMIOObjectID cmioDevice;
            
    [cmioDevices getBytes:&cmioDevice range:NSMakeRange(i * sizeof(CMIOObjectID), sizeof(CMIOObjectID))];
            
    [...]
}
```
(Or you go more low-level and `malloc`/`free` manually, though `NSMutableData` has the benefit of being ARC managed).

It is correct that Xcode's proposed compiler settings do not warn about VLAs though.

File: libobs/obs-cocoa.m [hunk 1]
```diff
@@ -461,8 +461,11 @@ static bool code_to_str(int code, struct dstr *str)
 
 void obs_key_to_str(obs_key_t key, struct dstr *str)
 {
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wvla"
     const UniCharCount max_length = 16;
```
Comment (PatTheMav) [inline libobs/obs-cocoa.m:466]: I wonder if in this case it wouldn't be simpler to just do `UniChar buffer[16]` given that the value is very much static.

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm [hunk 2]
```diff
@@ -370,7 +370,10 @@ static bool virtualcam_output_start(void *data)
                                            .mElement = kCMIOObjectPropertyElementMain};
         CMIOObjectGetPropertyDataSize(kCMIOObjectSystemObject, &address, 0, NULL, &size);
         size_t num_devices = size / sizeof(CMIOObjectID);
+#pragma clang diagnostic push
```
Comment (PatTheMav) [inline plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm:373]: Use `NSMutableData` approach instead.

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm [hunk 3]
```diff
@@ -404,7 +407,10 @@ static bool virtualcam_output_start(void *data)
 
         address.mSelector = kCMIODevicePropertyStreams;
         CMIOObjectGetPropertyDataSize(vcam->deviceID, &address, 0, NULL, &size);
+#pragma clang diagnostic push
```
Comment (PatTheMav) [inline plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm:410]: Use `NSMutableData` approach instead.

File: libobs/obs-cocoa.m (hunk 1 above)
Comment (PatTheMav) [reply libobs/obs-cocoa.m]: This is not resolved - it replaced a variable-length array with a magic number and preprocessor statements, all of which are superfluous. The number doesn't change, so it can and should be represented in code.

Comment (tytan652) [reply libobs/obs-cocoa.m:464]: No, it doesn't become a VLA since it's a macro and the magic number was already there before the macro statement.

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm [hunk 4]
```diff
@@ -370,15 +370,17 @@ static bool virtualcam_output_start(void *data)
                                            .mElement = kCMIOObjectPropertyElementMain};
         CMIOObjectGetPropertyDataSize(kCMIOObjectSystemObject, &address, 0, NULL, &size);
         size_t num_devices = size / sizeof(CMIOObjectID);
-        CMIOObjectID cmio_devices[num_devices];
-        CMIOObjectGetPropertyData(kCMIOObjectSystemObject, &address, 0, NULL, size, &used, &cmio_devices);
+        NSMutableData *cmioDevices = [NSMutableData dataWithLength:size];
```
Comment (PatTheMav) [inline plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm:373]: This code doesn't work - the example I posted was more or less pseudocode, this needs to be implemented properly and tested as well (`CMIOObjectGetPropertyData` expects a void pointer, not an `NSMutableData` pointer).

Comment (tytan652) [reply plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm]: I don't a have a Apple machine so I can't test this code.
I reverted to pragmas, feel free to do a PR which use NSMutableData.

Comment (gxalpha) [reply plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm]: If desired (I think it would be a better fix than throwing `pragma clang diagnostic push` all over the code), I can look into this.

Comment (tytan652) [reply plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm]: It surely does but I don't have what is needed to correctly test that, so feel free.

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm (hunk 2 above)
Comment (PatTheMav) [inline plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm:373]:
```suggestion
        NSMutableData *cmioDevices = [NSMutableData dataWithLength:size];
        void *device_data = [cmioDevices mutableBytes];
        CMIOObjectGetPropertyData(kCMIOObjectSystemObject, &address, 0, NULL, size, &used, device_data);
        
        vcam->deviceID = 0;
        NSString *OBSVirtualCamUUID = [[NSBundle bundleWithIdentifier:@"com.obsproject.mac-virtualcam"] objectForInfoDictionaryKey:@"OBSCameraDeviceUUID"];

        for (size_t i = 0; i < (used * sizeof(CMIOObjectID)); i++) {
            CMIOObjectID cmioDevice;

            [cmioDevices getBytes:&cmioDevice range:NSMakeRange(i * sizeof(CMIOObjectID), sizeof(CMIOObjectID))];
            
            address.mSelector = kCMIODevicePropertyDeviceUID;

            UInt32 device_name_size;
            CMIOObjectGetPropertyDataSize(cmioDevice, &address, 0, NULL, &device_name_size);

            CFStringRef uid;
            CMIOObjectGetPropertyData(cmioDevice, &address, 0, NULL, device_name_size, &used, &uid);

            const char *uid_string = CFStringGetCStringPtr(uid, kCFStringEncodingUTF8);
            if (uid_string && strcmp(uid_string, OBSVirtualCamUUID.UTF8String) == 0) {
                vcam->deviceID = cmioDevice;
                CFRelease(uid);
                break;
            } else {
                CFRelease(uid);
            }
        }
```

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm [hunk 5]
```diff
@@ -370,7 +370,10 @@ static bool virtualcam_output_start(void *data)
                                            .mElement = kCMIOObjectPropertyElementMain};
         CMIOObjectGetPropertyDataSize(kCMIOObjectSystemObject, &address, 0, NULL, &size);
         size_t num_devices = size / sizeof(CMIOObjectID);
+#pragma clang diagnostic push
+#pragma clang diagnostic ignored "-Wvla"
```
Comment (PatTheMav) [inline plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm:374]:
```suggestion
        NSMutableData *streamIds = [NSMutableData dataWithLength:size];
        void *stream_data = [streamIds mutableBytes];
        CMIOObjectGetPropertyData(vcam->deviceID, &address, 0, NULL, size, &used, stream_data);
        
        if (used < (2 * sizeof(CMIOStreamID))) {
            obs_output_set_last_error(vcam->output, obs_module_text("Error.SystemExtension.CameraNotStarted"));
            return false;
        }

        [streamIds getBytes:&vcam->streamID range:NSMakeRange(sizeof(CMIOStreamID), sizeof(CMIOStreamID))];
```

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm (hunk 2 above)
Comment (tytan652) [reply plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm]: Patch applied

File: plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm (hunk 5 above)
Comment (tytan652) [reply plugins/mac-virtualcam/src/obs-plugin/plugin-main.mm]: Patch applied

**Comment by PatTheMav** [comment]
macOS changes look good to me, if @gxalpha can't find fault with them they might be good to go.

**Comment by tytan652** [comment]
Added `da_reserve`s in PipeWire code.
