### PR TITLE
mac-capture: Set minimum frame interval in capture initialization

### LINKED ISSUE #11778: "MacOS screen capture" only captures up to 60fps, despite using higher (120) fps configuration
### Operating System Info

macOS 15

### Other OS

_No response_

### OBS Studio Version

31.0.1

### OBS Studio Version (Other)

_No response_

### OBS Studio Log URL

https://obsproject.com/logs/7Pr0BNkOIYe3ZsUE

### OBS Studio Crash Log URL

_No response_

### Expected Behavior

The video recorded is 120fps, and shows a "smoother" 120fps footage

### Current Behavior

The video recorded is in 120fps, however the footage appears to be capped at 60fps

### Steps to Reproduce

1. Set the recording frame rate to 120fps
2. Set the MacOS frame rate to ProMotion (120fps)
3. Record a short clip, preferably action based
4. Rewatch the recording, and you can notice the recording not being as smooth as the display

### Anything else we should know?

The MacBook I use is an M1 Pro.

This issue has started happening as early as November of 2024. 

While on the other hand, using the _deprecated_ "Window Capture" and "Display Capture" to record keeps the full 120fps video footage.

Also this is the last video recorded from the uploaded log:

https://github.com/user-attachments/assets/dc48b996-7680-46f9-84d1-d0f7f85b54ad

Lastly, despite using the Intel version (of OBS) to reproduce the bug, the same issue persists after switching to the Apple Silicon version.

### PR DESCRIPTION
**Pull request by jcm93**
### Description

When creating a macOS Screen Capture source, set the `minimumFrameInterval` property in the capture stream properties based on OBS's currently configured output FPS.

### Motivation and Context

Because OBS does not set a `minimumFrameInterval` on the `SCStreamConfiguration` object, we are subject to whatever defaults ScreenCaptureKit imposes on capture streams. At some point, perhaps in macOS 15, a change in macOS seems to have made this default `1/60`, even if the host display has a higher refresh rate or if the content is updating more frequently than 60 times per second.

OBS allows frame rates higher than 60, as does macOS, so we should set this property in accordance to OBS's configured FPS and ensure greater-than-60 frame rate captures are possible.

Importantly, setting this property to the exact inverse of our frame rate seems to provide a capture that drops many frames, so this PR targets a slightly shorter minimum interval. Presumably this allows the OBS and macOS render loops to better deal with timing variations between them.

The chosen buffer is 10% of our target interval. This value was determined through subjective testing. Oddly, setting a target interval significantly shorter than our target update rate (e.g. `1 / (target frame rate * 2)`) also led to significant amounts of dropped frames, though less than with the exact interval.
 
Multiple rounds of testing were performed under different conditions (and between macOS 15.2 and 15.3) to verify that these results were as consistent as macOS would allow. As we have limited introspection ability for the internals of ScreenCaptureKit, we unfortunately do not seem to have better options here than significant amounts of trial-and-error testing.

Fixes #11778

### How Has This Been Tested?

On an M1 Max MacBook Pro  with "ProMotion" display on macOS 15.3.1, various trial recordings were made using https://www.testufo.com and the Display, Window and Application Capture modes of macOS Screen Capture and with OBS's target FPS set to 120. Verified that the chosen minimum frame interval value led to a relatively smooth capture at 120 fps.

Test recordings:

Existing behavior (default 1/60 minimum interval, OBS at 120 fps):

https://github.com/user-attachments/assets/feb9064c-db3e-45c3-98ad-43171a6fb6be

PR behavior (1/132 minimum interval, OBS at 120 fps):

https://github.com/user-attachments/assets/930d5786-a998-4893-9b54-32eb9d77aa09

Matching interval behavior (1/120 minimum interval, OBS at 120 fps):

https://github.com/user-attachments/assets/f32db778-a21b-480e-a409-417b922395f6

Doubled interval behavior (1/240 minimum interval, OBS at 120 fps):

https://github.com/user-attachments/assets/41ce3920-6366-40d8-8249-6dc6aed8d4e4

Since the 10% buffer seemed to have the subjectively best pacing across multiple rounds of testing, and presumably also asks less of the API than a doubled interval, it is what I went with for this PR.

### Types of changes

- Bug fix (non-breaking change which fixes an issue)

- Tweak (non-breaking change to improve existing functionality)

### Checklist:

- [x] My code has been run through [clang-format](https://github.com/obsproject/obs-studio/blob/master/.clang-format).
- [x] I have read the [**contributing** document](https://github.com/obsproject/obs-studio/blob/master/CONTRIBUTING.rst).
- [x] My code is not on the master branch.
- [x] The code has been tested.
- [x] All commit messages are properly formatted and commits squashed where appropriate.
- [x] I have included updates to all appropriate documentation.

### CODE REVIEW

File: plugins/mac-capture/mac-sck-video-capture.m [hunk 1]
```diff
@@ -194,11 +194,22 @@
...
+
     CGColorRef background = CGColorGetConstantColor(kCGColorClear);
     [sc->stream_properties setQueueDepth:8];
     [sc->stream_properties setShowsCursor:!sc->hide_cursor];
     [sc->stream_properties setColorSpaceName:kCGColorSpaceDisplayP3];
     [sc->stream_properties setBackgroundColor:background];
+    if (foundOutputFPS) {
+        CMTime frameTimeInterval = CMTimeMake((int64_t) video_info.fps_den, video_info.fps_num);
+        CMTime updateTimePadding = CMTimeMultiplyByFloat64(frameTimeInterval, 0.1);
+        CMTime minimumUpdateTime = CMTimeSubtract(frameTimeInterval, updateTimePadding);
```
Comment (PatTheMav) [inline plugins/mac-capture/mac-sck-video-capture.m:208]: As this does effectively `a - (a * 0.1)`, wouldn't it be simpler to just do `a * 0.9`, especially as you're already doing a multiplication operation anyway?

Comment (jcm93) [reply plugins/mac-capture/mac-sck-video-capture.m:208]: Yes, it would.

Comment (jcm93) [reply plugins/mac-capture/mac-sck-video-capture.m]: Fixed.

**Review by PatTheMav — COMMENTED** [review]
So this effectively forces SCK to always capture slightly faster than OBS' current canvas frame rate, thus preventing macOS from throttling capture for energy efficiency or other reasons (because usually ProMotion wants to rapidly change the current device frame rate based on user interaction and thus be more reactive to what happens visually).

How does this cope when the canvas is set to a very high frame rate, say 360fps?

**Comment by jcm93** [comment]
> So this effectively forces SCK to always capture slightly faster than OBS' current canvas frame rate,

I think we have to be wary of phrasing it this way; we can't ever force SCK to *deliver* a frame by any particular time or with any particular cadence. From the best of my understanding, SCK gets every frame that the internal macOS rendering system decides needs to be created, and if certain conditions are met, it passes that frame along to client applications. All minimumFrameInterval says is "don't pass this update to clients if we already had an update `n` or fewer seconds ago".

In my testing, ScreenCaptureKit will not ever deliver updates faster than there are 'genuine' updates to the captured frame content that are available. In other words, if we had content constantly updating at display refresh (120 Hz), and a minimum frame interval of `1/360`, we would still receive new frames at (best case) 120 Hz. If we have static content not being updated whatsoever by macOS, we won't receive any new frames via SCK at any time even if the minimumFrameInterval is `1/9000`.

**Comment by PatTheMav** [comment]
> > So this effectively forces SCK to always capture slightly faster than OBS' current canvas frame rate,
> 
> I think we have to be wary of phrasing it this way; we can't ever force SCK to _deliver_ a frame by any particular time or with any particular cadence. From the best of my understanding, SCK gets every frame that the internal macOS rendering system decides needs to be created, and if certain conditions are met, it passes that frame along to client applications. All minimumFrameInterval says is "don't pass this update to clients if we already had an update `n` or fewer seconds ago".
> 
> In my testing, ScreenCaptureKit will not ever deliver updates faster than there are 'genuine' updates to the captured frame content that are available. In other words, if we had content constantly updating at display refresh (120 Hz), and a minimum frame interval of `1/360`, we would still receive new frames at (best case) 120 Hz. If we have static content not being updated whatsoever by macOS, we won't receive any new frames via SCK at any time even if the minimumFrameInterval is `1/9000` (any artificially high value).

Got it. Sounds uncontroversial to me then.

File: plugins/mac-capture/mac-sck-video-capture.m [hunk 2]
```diff
@@ -194,11 +194,21 @@
     }
     os_sem_post(sc->shareable_content_available);
 
+    struct obs_video_info video_info;
+    bool foundOutputFPS = obs_get_video_info(&video_info);
```
Comment (PatTheMav) [inline plugins/mac-capture/mac-sck-video-capture.m]:
```suggestion
    bool hasVideoInfo = obs_get_video_info(&video_info);
```
Seems more semantically correct to me - the FPS data is obviously part of the video info data, but the boolean return value informs whether `libobs` has a main video mix with associated output video info data.

Comment (jcm93) [reply plugins/mac-capture/mac-sck-video-capture.m]: Agreed; changed. Also rebased in order to build again locally.

**Review by PatTheMav — APPROVED** [review]
The code looks fine to me and it seems to have been tested to a decent amount as well.
